/**
 * GENERATED by scripts/brand/build.mjs — do not hand-edit, and do not treat the
 * literals below as a place to change the brand. The geometry, the colours and
 * the rasters all come out of scripts/brand/akbaral-mark.mjs, which is why the
 * favicon and the header tile cannot drift apart.
 *
 * `npm run brand:build` regenerates this file; `npm run brand:check` (run by
 * src/app/brand-assets.test.ts) fails when a checked-in asset no longer matches
 * its source.
 */

/** Square grid the monogram is authored on. */
export const BRAND_MARK_VIEWBOX = 64;

/** Ink box inside that grid — the mark never touches the edge of its own frame. */
export const BRAND_MARK_INK = { x: 8, y: 8, width: 48, height: 48 } as const;

/** The monogram: three solids, nonzero fill, nothing knocked out. */
export const BRAND_MARK_PATH = 'M26 8L34 8L16 56L8 56ZM30 8L38 8L56 56L48 56ZM20 42L44 38L44 46L20 50Z';

/** Horizontal lockup — monogram plus the AKBARAL! wordmark in authored glyphs. */
export const BRAND_LOGO_VIEWBOX = '0 0 436 64';
export const BRAND_LOGO_MARK_PATH = 'M26 8L34 8L16 56L8 56ZM30 8L38 8L56 56L48 56ZM20 42L44 38L44 46L20 50Z';
export const BRAND_LOGO_WORD_PATH = 'M98 8L106 8L88 56L80 56ZM102 8L110 8L128 56L120 56ZM92 42L116 38L116 46L92 50ZM135 8L146 8L146 56L135 56ZM145 26.5L174 8L174 19L145 37.5ZM153 20.5L177 45L177 56L153 31.5ZM184 8L195 8L195 56L184 56ZM192 8L210 8L218 16L218 38L192 38ZM192 27L218 27L218 48L210 56L192 56ZM195 27L207 27L207 19L195 19ZM195 45L207 45L207 38L195 38ZM243 8L251 8L233 56L225 56ZM247 8L255 8L273 56L265 56ZM237 42L261 38L261 46L237 50ZM280 8L291 8L291 56L280 56ZM288 8L306 8L314 16L314 33L306 41L288 41ZM291 30L303 30L303 19L291 19ZM299 28.5L322 45L322 56L299 39.5ZM347 8L355 8L337 56L329 56ZM351 8L359 8L377 56L369 56ZM341 42L365 38L365 46L341 50ZM384 8L395 8L395 56L384 56ZM384 45L418 45L418 56L384 56ZM425 8L436 8L436 35L425 35ZM425 45L436 45L436 56L425 56Z';

/** Public file paths, kept next to the geometry so a wiring test can pin them. */
export const BRAND_ASSETS = {
  mark: '/brand/akbaral-mark.svg',
  markLight: '/brand/akbaral-mark-light.svg',
  icon: '/brand/akbaral-icon.svg',
  logo: '/brand/akbaral-logo.svg',
  logoMono: '/brand/akbaral-logo-mono.svg',
  logoInk: '/brand/akbaral-logo-ink.svg',
  favicon: '/favicon.ico',
  favicon16: '/brand/akbaral-icon-16.png',
  favicon32: '/brand/akbaral-icon-32.png',
  favicon48: '/brand/akbaral-icon-48.png',
  appleTouchIcon: '/apple-touch-icon.png',
  icon192: '/brand/akbaral-icon-192.png',
  icon512: '/brand/akbaral-icon-512.png',
  iconMaskable512: '/brand/akbaral-icon-maskable-512.png',
  ogImage: '/brand/akbaral-og-1200x630.png',
  manifest: '/manifest.webmanifest',
} as const;

export const BRAND_ICON_PNGS = ['/brand/akbaral-icon-16.png', '/brand/akbaral-icon-32.png', '/brand/akbaral-icon-48.png', '/brand/akbaral-icon-180.png', '/brand/akbaral-icon-192.png', '/brand/akbaral-icon-512.png'] as const;

export const BRAND_MANIFEST_ICONS = [
  {
    "src": "/brand/akbaral-icon-192.png",
    "sizes": "192x192",
    "type": "image/png",
    "purpose": "any"
  },
  {
    "src": "/brand/akbaral-icon-maskable-512.png",
    "sizes": "512x512",
    "type": "image/png",
    "purpose": "maskable"
  }
] as const;
