import type { ReactNode } from 'react';
import { ContactForm } from '../_components/contact-form';
import { FeedbackForm } from '../_components/feedback-form';
import { PublicSiteFooter, PublicSiteHeader } from '../_components/public-site-chrome';
import styles from './public-info.module.css';

export type PublicKind = 'about' | 'contact' | 'documentation' | 'faq' | 'features' | 'feedback' | 'privacy' | 'security' | 'terms' | 'team' | 'blog';

const pageCopy: Record<PublicKind, { eyebrow: string; title: string; intro: string }> = {
  about: { eyebrow: 'About AKBARAL!', title: 'One intelligence. Every solution.', intro: 'AKBARAL! is an orchestration product for turning a goal into a reviewable result — without asking you to become the operator of every tool.' },
  contact: { eyebrow: 'Contact', title: 'Tell us what happened.', intro: 'Send a message through the real contact channel. Submissions are validated, rate-limited, and queued for the team.' },
  documentation: { eyebrow: 'Product guide', title: 'Understand the system before you run it.', intro: 'A concise guide to Chat, Work, the agent registry, credits, and the lifecycle behind a result.' },
  faq: { eyebrow: 'FAQ', title: 'Clear answers for the important bits.', intro: 'What is real today, when credits count, and where to look when you need to understand a run.' },
  features: { eyebrow: 'Product', title: 'The work surface, not a feature wall.', intro: 'AKBARAL! keeps the useful parts of orchestration close to the goal: conversation, tasks, agents, files, verification, and history.' },
  feedback: { eyebrow: 'Feedback', title: 'Help us make the product more useful.', intro: 'Signed-in feedback is attached to your account so its status can be shown honestly. Anonymous notes belong in Contact.' },
  privacy: { eyebrow: 'Privacy', title: 'A factual view of your product data.', intro: 'This page describes the data boundaries implemented by the product. It is not a promise that a feature exists when the API does not support it.' },
  security: { eyebrow: 'Security', title: 'Boundaries are part of the interface.', intro: 'AKBARAL! makes permissions, provider availability, sandboxed previews, and verification visible instead of implying certainty.' },
  terms: { eyebrow: 'Terms', title: 'Use the product with care.', intro: 'Outputs can be wrong, providers can be unavailable, and successful Work tasks consume the credits shown by your account.' },
  team: { eyebrow: 'Our team', title: 'People behind the product.', intro: 'We publish contributor information only when it is verified and approved for the public site.' },
  blog: { eyebrow: 'Blogs', title: 'Notes from the work.', intro: 'Only posts that exist in the repository are listed here. Empty is more honest than a made-up newsroom.' },
};

export function PublicFrame({ kind, children }: { kind: PublicKind; children: ReactNode }) {
  const copy = pageCopy[kind];
  return <main className={styles.page}><PublicSiteHeader /><div className={styles.pageBody}><div className={styles.heading}><span>{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.intro}</p></div>{children}</div><PublicSiteFooter /></main>;
}

export function PublicInfoPage({ kind }: { kind: PublicKind }) {
  if (kind === 'contact') return <PublicFrame kind={kind}><div className={styles.formPanel}><ContactForm /></div></PublicFrame>;
  if (kind === 'feedback') return <PublicFrame kind={kind}><div className={styles.formPanel}><FeedbackForm /></div></PublicFrame>;
  if (kind === 'about') return <PublicFrame kind={kind}><div className={styles.aboutStack}>
    <section className={styles.story}><h2>A workspace for the whole handoff.</h2><p>AKBARAL! brings conversation, tracked Work tasks, configured capabilities, files, review, and history into one product. The aim is practical: make the next useful step easier to see without hiding the limits of the system.</p><p>The registry contains <strong>4,001 registered agent contracts</strong>. That is a count of registered contracts; it does not promise availability or revenue for every account.</p></section>
    <div className={styles.aboutGrid}><section className={styles.aboutCard}><span>WHO IT IS FOR</span><h2>People with work to clarify.</h2><p>Use it when a goal needs a conversation first, or when a task needs stages, an output, and a record you can inspect.</p></section><section className={styles.aboutCard}><span>HOW IT WORKS</span><h2>Chat or Work.</h2><p><b>Chat</b> is the open conversation. <b>Work</b> turns a goal into a tracked task with the state and output returned by the configured product path.</p></section><section className={styles.aboutCard}><span>WHAT IT DOES NOT DO</span><h2>No invented certainty.</h2><p>It does not promise every provider is available, turn an empty state into activity, or claim that an output is correct without the verification the configured flow can actually provide.</p></section></div>
  </div></PublicFrame>;
  if (kind === 'features') return <PublicFrame kind={kind}><FeatureSections /></PublicFrame>;
  if (kind === 'documentation') return <PublicFrame kind={kind}><DocSections /></PublicFrame>;
  if (kind === 'faq') return <PublicFrame kind={kind}><FaqSections /></PublicFrame>;
  if (kind === 'privacy') return <PublicFrame kind={kind}><PolicySections title="Product data boundaries" items={[['Account and access', 'Authentication records and account settings are handled by the existing account and session services. Keep credentials and tokens private.'], ['Workspace content', 'Messages, attachments, tasks, projects, and artifacts are shown only through authenticated product routes that return them.'], ['Honest states', 'Provider availability, task failures, empty data, and credit behavior are surfaced as returned by the backend rather than replaced with invented activity.']]}/></PublicFrame>;
  if (kind === 'security') return <PublicFrame kind={kind}><PolicySections title="Implemented safeguards" items={[['Permission checks', 'Authenticated routes use account identity and role checks. Agent Factory mutations require the owner or an authorized role.'], ['Safer output', 'Work previews render in sandboxed frames, and exports use authenticated endpoints.'], ['Verification', 'Tool activity, provider fallback, task state, and verification appear only where the configured flow returns them.']]}/></PublicFrame>;
  return <PublicFrame kind={kind}><PolicySections title="Using AKBARAL! responsibly" items={[['Review important outputs', 'AI can make mistakes. Validate decisions, facts, code, and documents before relying on them.'], ['Credits', 'Published plans are USD-only. Work task credits are consumed on successful Work tasks; failures refund automatically where the backend supports that path.'], ['Boundaries', 'Do not submit secrets or credentials in prompts, contact forms, feedback, or attachments.']]}/></PublicFrame>;
}

function FeatureSections() { return <div className={styles.cardGrid}>{[['Chat', 'A real conversation surface with streaming, model availability, attachments where supported, tool activity, and honest failure states.'], ['Work', 'A tracked task with lifecycle stages, output, preview, history, and authenticated export where the result supports it.'], ['Agents', 'A server-searchable registry of configured contracts with category, status, and pagination — not decorative activity.'], ['Agent Factory', 'Templates, creation, security review, benchmarks, versions, status, and rollback through the existing factory contracts.'], ['Dashboard', 'A compact account view for plan, credits, recent work, conversations, and sessions.'], ['Billing', 'USD-only plans, invoices, payments, and account-level credit context when returned by the billing API.']].map(([title, text]) => <article className={styles.card} key={title}><span>AKBARAL!</span><h2>{title}</h2><p>{text}</p></article>)}</div>; }
function DocSections() { return <div className={styles.docGrid}><article className={styles.docCard}><h2>Chat or Work?</h2><p>Use Chat when you want to explore a problem in conversation. Use Work when you want a goal to become a tracked task with lifecycle state and an output surface.</p></article><article className={styles.docCard}><h2>What happens next?</h2><ol><li>Goal understanding</li><li>Planning</li><li>MASTER orchestration and routing</li><li>Specialist agents and tools</li><li>Provider fallback and verification</li><li>Result, lifecycle, and credit record</li></ol></article><article className={styles.docCard}><h2>Where can I inspect it?</h2><p>Dashboard shows account context. Agents shows the registered capability catalog. Work shows task state and output. Agent Factory shows the configured agent lifecycle.</p></article></div>; }
function FaqSections() { return <div className={styles.faqGrid}>{[['Does Chat spend Work credits?', 'No. Chat is a conversation surface. Work task credits are separate.'], ['When do credits count?', 'Published behavior is success-based for Work. Failed tasks refund automatically where the execution path supports it.'], ['Can I create an agent?', 'Yes, through Agent Factory. Creation and lifecycle actions use authenticated factory APIs; browsing templates does not create anything.'], ['Why is a page empty?', 'Empty states are real. The account may have no rows, a provider may be unavailable, or the current API may not support that action.'], ['Are plans in USD?', 'Yes. AKBARAL! publishes Free Trial, Starter, Pro, Business, Scale, and Enterprise in USD only.']].map(([q, a]) => <details className={styles.faq} key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>; }
function PolicySections({ title, items }: { title: string; items: Array<[string, string]> }) { return <section className={styles.policy}><h2>{title}</h2>{items.map(([label, text]) => <div className={styles.policyRow} key={label}><h3>{label}</h3><p>{text}</p></div>)}</section>; }
