/**
 * Agent Registry catalog.
 *
 * Agent definitions are NOT handwritten duplicates: they are generated from a
 * combinatorial matrix of real domain blueprints (80 professional domains) and
 * genuinely different specialization profiles (50 specialist archetypes).
 * Each combination yields a unique id, specialization, system instructions,
 * capabilities, inputs/outputs, model requirements, tools, workflow, verification,
 * security profile, cost metadata, fallback, version, health and eval config.
 *
 * This keeps 4,000+ agents genuinely differentiated without 4,000 duplicated
 * source files, while preserving extensibility for custom agents.
 */

export interface AgentDefinition {
  key: string;
  slug: string;
  name: string;
  categorySlug: string;
  specialization: string;
  systemInstructions: string;
  capabilities: string[];
  inputs: string[];
  outputs: string[];
  modelRequirements: string[];
  toolPermissions: string[];
  apiRequirements: string[];
  workflow: string[];
  verificationRules: string[];
  securityPermissions: string[];
  costUsage: { estimatedTokens: number; estimatedCents: number; priority: 'low' | 'medium' | 'high' };
  fallbackStrategy: string;
  evaluationConfig: { metrics: string[]; rubric: string; testCases: string[] };
}

interface DomainBlueprint {
  slug: string;
  name: string;
  description: string;
  domainBusiness: string;
  domainKnowledge: string;
  domainTools: string[];
  domainModelCapabilities: string[];
  domainSecurity: string[];
  domainVerification: string[];
  domainOutput: string[];
  domainCostBase: number;
}

interface SpecializationProfile {
  key: string;
  name: string;
  responsibility: string;
  inputs: string[];
  outputs: string[];
  workflow: string[];
  verification: string[];
  security: string[];
  modelCapabilities: string[];
}

const DOMAINS: DomainBlueprint[] = [
  { slug: 'software-engineering', name: 'Software Engineering', description: 'Build, maintain and harden production software systems.', domainBusiness: 'software development life cycle, architecture, code quality, release engineering', domainKnowledge: 'design patterns, type systems, algorithms, security, observability, CI/CD', domainTools: ['code_repository_read', 'knowledge_search'], domainModelCapabilities: ['coding', 'reasoning'], domainSecurity: ['sandboxed code reading only', 'no arbitrary shell execution'], domainVerification: ['unit/type/test evidence', 'security review', 'architecture fit'], domainOutput: ['implementation plans', 'review reports', 'refactor diffs'], domainCostBase: 2 },
  { slug: 'web-development', name: 'Web Development', description: 'Design, build and optimize modern web applications and sites.', domainBusiness: 'web app architecture, UX performance, accessibility, SEO, conversion', domainKnowledge: 'HTML/CSS/JS, frameworks, web standards, performance, accessibility', domainTools: ['code_repository_read', 'web_search', 'knowledge_search'], domainModelCapabilities: ['coding', 'vision', 'research'], domainSecurity: ['no secrets in code', 'safe URL handling'], domainVerification: ['browser/accessibility checks', 'responsive review', 'build verification'], domainOutput: ['web specs', 'code plans', 'SEO/accessibility audits'], domainCostBase: 2 },
  { slug: 'mobile-development', name: 'Mobile Development', description: 'Architect and build cross-platform and native mobile applications.', domainBusiness: 'mobile UX, device performance, app-store compliance, offline behavior', domainKnowledge: 'React Native/Flutter/native, push, storage, permissions, store policies', domainTools: ['code_repository_read', 'knowledge_search'], domainModelCapabilities: ['coding', 'vision'], domainSecurity: ['no secret in app', 'secure storage review'], domainVerification: ['platform audit', 'permission review', 'store checklist'], domainOutput: ['mobile specs', 'architecture plans', 'release checklists'], domainCostBase: 2 },
  { slug: 'ai-ml-engineering', name: 'AI/ML Engineering', description: 'Design, train, evaluate and ship AI/ML systems.', domainBusiness: 'model lifecycle, data pipelines, training, evaluation, serving', domainKnowledge: 'transformers, evaluation, MLOps, data ethics, latency/cost', domainTools: ['code_repository_read', 'knowledge_search', 'file_parse_text'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['no training data leaks', 'model permission review'], domainVerification: ['evaluation reports', 'ablation evidence', 'regression metrics'], domainOutput: ['model specs', 'training plans', 'eval reports'], domainCostBase: 3 },
  { slug: 'data-science', name: 'Data Science', description: 'Turn data into insights, models and decisions.', domainBusiness: 'data analysis, statistics, hypothesis testing, visualization', domainKnowledge: 'statistics, SQL, pandas, ML, experimentation, causality', domainTools: ['file_parse_text', 'knowledge_search', 'excel_build'], domainModelCapabilities: ['research', 'reasoning', 'coding'], domainSecurity: ['privacy of datasets', 'no raw PII exposure'], domainVerification: ['statistical checks', 'sample validation', 'visualization review'], domainOutput: ['analysis reports', 'dashboards', 'model briefs'], domainCostBase: 2 },
  { slug: 'research', name: 'Research', description: 'Discover, synthesize and verify information from web and documents.', domainBusiness: 'source evaluation, evidence synthesis, citation integrity', domainKnowledge: 'search, source grading, fact-checking, citation standards', domainTools: ['web_search', 'page_fetch', 'knowledge_search'], domainModelCapabilities: ['research', 'reasoning', 'long_context'], domainSecurity: ['no fabricated sources', 'no private data exfiltration'], domainVerification: ['source verification', 'citation check', 'claim evidence'], domainOutput: ['research reports', 'source comparisons', 'briefs'], domainCostBase: 1 },
  { slug: 'scientific-research', name: 'Scientific Research', description: 'Support rigorous scientific investigation and literature analysis.', domainBusiness: 'peer-reviewed evidence, methodology, replication, reporting', domainKnowledge: 'scientific method, statistics, reproducibility, citation of literature', domainTools: ['web_search', 'page_fetch', 'knowledge_search'], domainModelCapabilities: ['research', 'reasoning'], domainSecurity: ['respect dataset licenses', 'no patient/private data'], domainVerification: ['methodology soundness', 'statistical rigor', 'reference verification'], domainOutput: ['literature reviews', 'protocols', 'method critiques'], domainCostBase: 3 },
  { slug: 'business-strategy', name: 'Business Strategy', description: 'Formulate market, growth and operating strategy.', domainBusiness: 'strategy frameworks, market positioning, resource allocation', domainKnowledge: 'business models, market analysis, competitive strategy, unit economics', domainTools: ['web_search', 'knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'research'], domainSecurity: ['no confidential client data leak'], domainVerification: ['assumption audit', 'market evidence', 'financial modeling'], domainOutput: ['strategy documents', 'market entries', 'option analyses'], domainCostBase: 2 },
  { slug: 'startup', name: 'Startup', description: 'Drive early-stage venture discovery, product-market fit and growth.', domainBusiness: 'validation, minimum viable product, traction, fundraising, operations', domainKnowledge: 'startup frameworks, fundraising, rapid iteration, growth loops', domainTools: ['web_search', 'knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'research'], domainSecurity: ['keep investor/company data confidential'], domainVerification: ['evidence of demand', 'unit economics', 'risk mapping'], domainOutput: ['startup plans', 'pitch outlines', 'runway models'], domainCostBase: 2 },
  { slug: 'ceo-executive-ops', name: 'CEO / Executive Operations', description: 'Support executive decision-making, planning and business operations.', domainBusiness: 'prioritization, delegation, ops design, strategic cadence', domainKnowledge: 'executive communication, OKRs, decision templates, process design', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'research'], domainSecurity: ['strict confidentiality for strategy'], domainVerification: ['decision-logic review', 'stakeholder alignment'], domainOutput: ['briefing decks', 'decision memos', 'operating plans'], domainCostBase: 2 },
  { slug: 'sales', name: 'Sales', description: 'Build pipelines, proposals, outreach and revenue playbooks.', domainBusiness: 'lead qualification, objection handling, deal strategy, CRM', domainKnowledge: 'sales methodologies, prospecting, negotiation, pricing', domainTools: ['knowledge_search', 'web_search'], domainModelCapabilities: ['writing', 'reasoning'], domainSecurity: ['protect customer/contact data'], domainVerification: ['buyer-fit checks', 'message compliance', 'pipeline hygiene'], domainOutput: ['sales plays', 'outreach sequences', 'deal briefs'], domainCostBase: 1 },
  { slug: 'crm', name: 'CRM', description: 'Design and operate customer relationship management systems.', domainBusiness: 'contact data quality, pipeline stages, automation, reporting', domainKnowledge: 'CRM data models, lead lifecycle, automation, enrichment', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['no sensitive contact export'], domainVerification: ['data hygiene rules', 'stage consistency'], domainOutput: ['CRM designs', 'workflows', 'report specs'], domainCostBase: 1 },
  { slug: 'customer-support', name: 'Customer Support', description: 'Deliver accurate, empathetic, resolvable customer assistance.', domainBusiness: 'ticket triage, resolution, escalation, knowledge base, SLAs', domainKnowledge: 'support workflows, FAQ, root-cause, empathy, documentation', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing', 'reasoning'], domainSecurity: ['no PII leakage', 'safe escalation'], domainVerification: ['policy compliance', 'resolution completeness'], domainOutput: ['answers', 'escalation paths', 'playbooks'], domainCostBase: 1 },
  { slug: 'marketing', name: 'Marketing', description: 'Plan, create and measure end-to-end marketing programs.', domainBusiness: 'segmentation, positioning, campaign ops, funnel analytics', domainKnowledge: 'growth loops, funnel analysis, content, attribution', domainTools: ['web_search', 'knowledge_search', 'excel_build'], domainModelCapabilities: ['writing', 'research', 'vision'], domainSecurity: ['no false claims', 'brand compliance'], domainVerification: ['campaign measurement', 'content approvals', 'audience fit'], domainOutput: ['marketing plans', 'campaigns', 'KPI frameworks'], domainCostBase: 2 },
  { slug: 'advertising', name: 'Advertising', description: 'Plan compliant advertising across paid channels.', domainBusiness: 'creative strategy, bidding, targeting, budget allocation', domainKnowledge: 'paid search/social, ROAS, creative testing, ad policies', domainTools: ['web_search', 'knowledge_search', 'excel_build'], domainModelCapabilities: ['writing', 'research'], domainSecurity: ['ad-policy compliant', 'no misleading claims'], domainVerification: ['policy check', 'ROAS model', 'creative coverage'], domainOutput: ['ad plans', 'copy variants', 'budget models'], domainCostBase: 2 },
  { slug: 'seo', name: 'SEO', description: 'Produce search-engine optimization strategies and content.', domainBusiness: 'keyword research, technical SEO, content authority, SERP intent', domainKnowledge: 'search algorithms, structured data, page speed, backlinks', domainTools: ['web_search', 'page_fetch'], domainModelCapabilities: ['research', 'writing'], domainSecurity: ['no spam/black-hat promotion'], domainVerification: ['keyword coverage', 'technical checks', 'content quality'], domainOutput: ['SEO audits', 'content briefs', 'keyword plans'], domainCostBase: 1 },
  { slug: 'search-content-strategy', name: 'Search & Content Strategy', description: 'Design content ecosystems aligned with search and audience behavior.', domainBusiness: 'content architecture, topical authority, funnel mapping, distribution', domainKnowledge: 'content strategy, topic clusters, information architecture, analytics', domainTools: ['web_search', 'page_fetch', 'knowledge_search'], domainModelCapabilities: ['research', 'writing'], domainSecurity: ['respect copyright'], domainVerification: ['topical coverage', 'authority mapping', 'distribution plan'], domainOutput: ['content strategies', 'topic maps', 'editorial calendars'], domainCostBase: 1 },
  { slug: 'social-media', name: 'Social Media', description: 'Build audience-led social media programs across platforms.', domainBusiness: 'community, platform norms, social copy, engagement analytics', domainKnowledge: 'platform algorithms, community guidelines, social listening', domainTools: ['web_search', 'knowledge_search'], domainModelCapabilities: ['writing', 'vision'], domainSecurity: ['no impersonation', 'safe disclosures'], domainVerification: ['platform safety', 'brand tone', 'engagement metrics'], domainOutput: ['social strategies', 'calendars', 'copy decks'], domainCostBase: 1 },
  { slug: 'youtube', name: 'YouTube', description: 'Plan and create strategy for YouTube channels and video.', domainBusiness: 'channel strategy, content formats, retention, monetization', domainKnowledge: 'YouTube algorithm, thumbnails, hooks, packaging, studio metrics', domainTools: ['web_search', 'knowledge_search'], domainModelCapabilities: ['research', 'writing', 'vision'], domainSecurity: ['respect music/asset rights'], domainVerification: ['retention analysis', 'ad-policy review', 'package quality'], domainOutput: ['channel strategies', 'video briefs', 'scripts'], domainCostBase: 1 },
  { slug: 'tiktok', name: 'TikTok', description: 'Create platform-native short-form video and trends strategy.', domainBusiness: 'trend mechanics, hooks, pacing, sound strategy, virality signals', domainKnowledge: 'TikTok editing, hooks, audio, hashtags, community standards', domainTools: ['web_search', 'knowledge_search'], domainModelCapabilities: ['writing', 'vision'], domainSecurity: ['no harmful trends', 'copyright-safe audio'], domainVerification: ['viral structure review', 'engagement modeling', 'policy compliance'], domainOutput: ['TikTok plans', 'scripts', 'trend briefs'], domainCostBase: 1 },
  { slug: 'instagram', name: 'Instagram', description: 'Build Instagram brand, reels and community strategy.', domainBusiness: 'visual identity, relationships, reels, story funnels, profile conversion', domainKnowledge: 'Instagram formats, aesthetics, captions, hashtags, DM marketing', domainTools: ['web_search', 'knowledge_search'], domainModelCapabilities: ['writing', 'vision'], domainSecurity: ['no fake endorsements'], domainVerification: ['brand consistency', 'profile conversion', 'content compliance'], domainOutput: ['Instagram plans', 'caption sets', 'feed concepts'], domainCostBase: 1 },
  { slug: 'x', name: 'X', description: 'Create high-signal content, threads and community strategy for X.', domainBusiness: 'timely insight, thread architecture, replies, lists, growth', domainKnowledge: 'X community norms, thread structure, engagement loops', domainTools: ['web_search', 'knowledge_search'], domainModelCapabilities: ['writing', 'research'], domainSecurity: ['no misinformation', 'disclosure rules'], domainVerification: ['thread flow', 'source accuracy', 'tone audit'], domainOutput: ['X strategies', 'thread scripts', 'post systems'], domainCostBase: 1 },
  { slug: 'e-commerce', name: 'E-commerce', description: 'Optimize online stores, listings, conversion and operations.', domainBusiness: 'catalog, conversion, product data, marketplace compliance', domainKnowledge: 'ecommerce metrics, product photos, SEO, payment/shipping ops', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['research', 'writing'], domainSecurity: ['avoid inventory/margin leakage'], domainVerification: ['listing accuracy', 'conversion analysis', 'policy compliance'], domainOutput: ['store audits', 'listing packs', 'pricing/comparisons'], domainCostBase: 1 },
  { slug: 'product-management', name: 'Product Management', description: 'Define, prioritize and drive product decisions and roadmaps.', domainBusiness: 'customer problems, prioritization, specs, metrics, releases', domainKnowledge: 'product discovery, PRDs, north-star metrics, experimentation', domainTools: ['knowledge_search', 'web_search'], domainModelCapabilities: ['reasoning', 'research', 'writing'], domainSecurity: ['no confidential roadmap leaks'], domainVerification: ['problem evidence', 'scope feasibility', 'metric precision'], domainOutput: ['PRDs', 'roadmaps', 'prioritization matrices'], domainCostBase: 2 },
  { slug: 'finance', name: 'Finance', description: 'Support financial planning, analysis and funding strategy.', domainBusiness: 'budgets, forecasting, valuation, fundraising, risk', domainKnowledge: 'financial statements, modeling, capital structure, tax basics', domainTools: ['excel_build', 'knowledge_search'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['no sensitive financial info exposure'], domainVerification: ['model accuracy', 'assumption tags', 'risk notes'], domainOutput: ['financial models', 'forecasts', 'funding notes'], domainCostBase: 2 },
  { slug: 'accounting', name: 'Accounting', description: 'Support bookkeeping, reconciliation and reporting workflows.', domainBusiness: 'ledgers, reconciliations, accruals, compliance timelines', domainKnowledge: 'double-entry, GAAP basics, tax periods, audit trails', domainTools: ['excel_build', 'knowledge_search'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['never disclose full credentials'], domainVerification: ['reconciliation checks', 'period review', 'evidentiary support'], domainOutput: ['ledger summaries', 'reconciliations', 'report frames'], domainCostBase: 1 },
  { slug: 'business-analytics', name: 'Business Analytics', description: 'Measure performance and translate metrics into decisions.', domainBusiness: 'dashboards, funnels, cohort analysis, KPIs, executive reporting', domainKnowledge: 'analytics, SQL, spreadsheets, visualization, experimentation', domainTools: ['file_parse_text', 'excel_build', 'knowledge_search'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['privacy-safe data'], domainVerification: ['metric definitions', 'statistical checks', 'data completeness'], domainOutput: ['analytics reports', 'dashboards', 'decision memos'], domainCostBase: 1 },
  { slug: 'legal-information', name: 'Legal Information', description: 'Provide accessible general legal information, not legal advice.', domainBusiness: 'legal research summaries, contract plain-language, compliance alerts', domainKnowledge: 'general law areas, contract clauses, regulatory awareness', domainTools: ['web_search', 'knowledge_search'], domainModelCapabilities: ['reasoning', 'research'], domainSecurity: ['disclaimers; attorney review', 'no privileged advice'], domainVerification: ['jurisdiction caveats', 'citation checks', 'disclaimer present'], domainOutput: ['legal information briefs', 'plain-language contracts', 'checklists'], domainCostBase: 2 },
  { slug: 'education', name: 'Education', description: 'Design learning experiences and instructional content.', domainBusiness: 'curriculum design, pedagogy, assessment, accessibility', domainKnowledge: 'learning objectives, pedagogy, assessment design, learning science', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing', 'reasoning'], domainSecurity: ['child-safety compliant', 'no overclaiming outcomes'], domainVerification: ['learning outcome alignment', 'assessment validity', 'accessibility'], domainOutput: ['lesson plans', 'curricula', 'rubrics'], domainCostBase: 1 },
  { slug: 'tutoring', name: 'Tutoring', description: 'Tutor learners with adaptive explanations and practice.', domainBusiness: 'mastery learning, scaffolding, feedback, progress tracking', domainKnowledge: 'subject-matter accuracy, Socratic questioning, misconception repair', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing', 'reasoning'], domainSecurity: ['no answers-only shortcuts', 'child-safe'], domainVerification: ['step accuracy', 'misconception correction', 'mastery check'], domainOutput: ['tutoring sessions', 'practice sets', 'progress notes'], domainCostBase: 1 },
  { slug: 'career', name: 'Career', description: 'Build career strategy, job-search and professional positioning.', domainBusiness: 'career direction, networking, job search, positioning', domainKnowledge: 'job market, interviewing, personal branding, negotiation', domainTools: ['knowledge_search', 'web_search'], domainModelCapabilities: ['writing', 'research', 'reasoning'], domainSecurity: ['no fabricated credentials'], domainVerification: ['role fit', 'resume truthfulness', 'application relevance'], domainOutput: ['career strategies', 'applications', 'positioning notes'], domainCostBase: 1 },
  { slug: 'recruitment-hr', name: 'Recruitment / HR', description: 'Design hiring funnels and people operations.', domainBusiness: 'requisitions, sourcing, screening, onboarding, retention', domainKnowledge: 'talent acquisition, equity hiring, HR compliance, interviews', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'writing'], domainSecurity: ['no bias', 'candidate data protection'], domainVerification: ['bias checks', 'interview rubric', 'compliance review'], domainOutput: ['recruiting plans', 'screen guides', 'HR playbooks'], domainCostBase: 1 },
  { slug: 'cv-resume', name: 'CV / Resume', description: 'Create evidence-based, tailored resumes and profiles.', domainBusiness: 'resume positioning, ATS compliance, quantified impact', domainKnowledge: 'resume formats, ATS, achievement writing, LinkedIn', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing'], domainSecurity: ['no invented experience'], domainVerification: ['ATS-friendly', 'proofreading', 'impact quantification'], domainOutput: ['resumes', 'CV rewrites', 'LinkedIn profiles'], domainCostBase: 1 },
  { slug: 'interview', name: 'Interview', description: 'Prepare candidates for behavioral and technical interviews.', domainBusiness: 'question prediction, answer frameworks, mock practice', domainKnowledge: 'STAR method, technical drills, communication, evaluation', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing', 'reasoning'], domainSecurity: ['no leaking live questions'], domainVerification: ['answer structure', 'technical accuracy', 'delivery practice'], domainOutput: ['interview prep', 'mock answers', 'question banks'], domainCostBase: 1 },
  { slug: 'translation', name: 'Translation', description: 'Translate content with cultural and linguistic accuracy.', domainBusiness: 'meaning preservation, terminology, tone, localization', domainKnowledge: 'linguistics, cultural context, registers, machine translation review', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing', 'reasoning'], domainSecurity: ['protect source confidentiality'], domainVerification: ['back-translation', 'term consistency', 'native review'], domainOutput: ['translations', 'glossaries', 'transcreation'], domainCostBase: 1 },
  { slug: 'localization', name: 'Localization', description: 'Adapt products and content for target regions.', domainBusiness: 'locale adoption, UI strings, dates/currency, cultural adaptation', domainKnowledge: 'localization workflows, locale standards, content adaptation', domainTools: ['knowledge_search', 'file_parse_text'], domainModelCapabilities: ['writing', 'reasoning'], domainSecurity: ['protect proprietary strings'], domainVerification: ['locale QA', 'fit-for-market', 'string consistency'], domainOutput: ['localization kits', 'locale QA reports', 'adaptation guides'], domainCostBase: 1 },
  { slug: 'writing', name: 'Writing', description: 'Produce clear, structured and audience-aware writing.', domainBusiness: 'articles, briefs, docs, storytelling, messaging', domainKnowledge: 'rhetoric, structure, grammar, audience research, tone', domainTools: ['knowledge_search', 'web_search'], domainModelCapabilities: ['writing', 'research'], domainSecurity: ['no plagiarism'], domainVerification: ['readability', 'source check', 'voice alignment'], domainOutput: ['articles', 'briefs', 'documents'], domainCostBase: 1 },
  { slug: 'copywriting', name: 'Copywriting', description: 'Write persuasive marketing and conversion copy.', domainBusiness: 'value propositions, messaging hierarchy, CTA optimization', domainKnowledge: 'copy frameworks, persuasion, brand voice, A/B copy', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing'], domainSecurity: ['no misleading claims'], domainVerification: ['benefit clarity', 'call-to-action', 'claim accuracy'], domainOutput: ['copy decks', 'headlines', 'landing copy'], domainCostBase: 1 },
  { slug: 'documents', name: 'Documents', description: 'Create and structure professional documents.', domainBusiness: 'proposals, reports, contracts, manuals, formatting', domainKnowledge: 'document architecture, templates, standards, versioning', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing', 'reasoning'], domainSecurity: ['no sensitive data exposure'], domainVerification: ['structure check', 'consistency', 'review readiness'], domainOutput: ['documents', 'templates', 'report packs'], domainCostBase: 1 },
  { slug: 'pdf', name: 'PDF', description: 'Process, summarize and transform PDF documents.', domainBusiness: 'extraction, page structure, forms, conversion, metadata', domainKnowledge: 'PDF layout, OCR, text extraction, accessibility', domainTools: ['file_parse_text', 'knowledge_search'], domainModelCapabilities: ['reasoning', 'vision'], domainSecurity: ['protect document contents'], domainVerification: ['extraction fidelity', 'redaction check', 'page integrity'], domainOutput: ['summaries', 'extracts', 'converted docs'], domainCostBase: 1 },
  { slug: 'excel-spreadsheet', name: 'Excel / Spreadsheet', description: 'Build, analyze and audit spreadsheets.', domainBusiness: 'models, formulas, data pipelines, reporting, reconciliation', domainKnowledge: 'spreadsheet engineering, formula design, data validation, charts', domainTools: ['file_parse_text', 'excel_build'], domainModelCapabilities: ['coding', 'reasoning'], domainSecurity: ['no data leakage to third parties'], domainVerification: ['formula audit', 'error checks', 'sample validation'], domainOutput: ['workbooks', 'analysis sheets', 'reconciliation tables'], domainCostBase: 1 },
  { slug: 'data-analysis', name: 'Data Analysis', description: 'Analyze datasets for patterns and decision support.', domainBusiness: 'data profiling, statistics, segmentation, anomalies', domainKnowledge: 'statistics, SQL, pandas, visualization, reliability of data', domainTools: ['file_parse_text', 'excel_build', 'knowledge_search'], domainModelCapabilities: ['reasoning', 'coding', 'research'], domainSecurity: ['privacy-safe handling'], domainVerification: ['data quality', 'statistical validity', 'interpretation rigor'], domainOutput: ['analysis reports', 'visualizations', 'decision memos'], domainCostBase: 1 },
  { slug: 'image-generation', name: 'Image Generation', description: 'Generate concept and production-ready imagery through real image models.', domainBusiness: 'creative direction, prompt engineering, brand consistency', domainKnowledge: 'composition, art styles, prompt discipline, licensing', domainTools: ['image_render'], domainModelCapabilities: ['image', 'vision'], domainSecurity: ['no IP infringement', 'license-aware prompts'], domainVerification: ['prompt fidelity', 'brand consistency', 'asset rights'], domainOutput: ['image prompts', 'compositions', 'asset briefs'], domainCostBase: 5 },
  { slug: 'image-editing', name: 'Image Editing', description: 'Plan precise image edits using real image-editing tooling.', domainBusiness: 'retouch, compositing, resizing, product images', domainKnowledge: 'editing tools, layers, masks, color, export settings', domainTools: ['image_render'], domainModelCapabilities: ['image', 'vision'], domainSecurity: ['no misuse of likeness'], domainVerification: ['edit instructions accuracy', 'QA checklist', 'asset output'], domainOutput: ['edit briefs', 'retouch steps', 'asset specs'], domainCostBase: 4 },
  { slug: 'graphic-design', name: 'Graphic Design', description: 'Create cohesive visual design systems and deliverables.', domainBusiness: 'brand visual language, layouts, print/digital formats', domainKnowledge: 'design principles, typography, grids, color, tooling', domainTools: ['image_render'], domainModelCapabilities: ['image', 'vision', 'design'], domainSecurity: ['font/license compliance'], domainVerification: ['design brief match', 'asset quality', 'accessibility'], domainOutput: ['design systems', 'layout specs', 'visual kits'], domainCostBase: 4 },
  { slug: 'ui-ux', name: 'UI/UX', description: 'Design usable, accessible and delightful digital experiences.', domainBusiness: 'user research, information architecture, usability, accessibility', domainKnowledge: 'UX principles, WCAG, design systems, prototypes, research', domainTools: ['knowledge_search'], domainModelCapabilities: ['vision', 'reasoning', 'writing'], domainSecurity: ['no sensitive user research reuse'], domainVerification: ['usability check', 'WCAG review', 'task success'], domainOutput: ['UX specs', 'wireframes', 'usability plans'], domainCostBase: 2 },
  { slug: 'branding', name: 'Branding', description: 'Build brand platforms, identity and messaging.', domainBusiness: 'brand strategy, identity, voice, positioning, guidelines', domainKnowledge: 'brand archetypes, visual identity, messaging hierarchy', domainTools: ['knowledge_search', 'web_search', 'image_render'], domainModelCapabilities: ['reasoning', 'vision', 'writing'], domainSecurity: ['trademark caution'], domainVerification: ['strategy fit', 'identity consistency', 'voice check'], domainOutput: ['brand platforms', 'guidelines', 'messaging maps'], domainCostBase: 3 },
  { slug: 'video', name: 'Video', description: 'Plan and script professional video content.', domainBusiness: 'storytelling, pacing, visual narrative, distribution', domainKnowledge: 'video formats, storyboarding, editing language, platform specs', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing', 'vision', 'reasoning'], domainSecurity: ['music/asset rights'], domainVerification: ['story clarity', 'platform timing', 'script accuracy'], domainOutput: ['video strategies', 'scripts', 'shot lists'], domainCostBase: 2 },
  { slug: 'short-form-video', name: 'Short-form Video', description: 'Create platform-native short video systems.', domainBusiness: 'hooks, retention, vertical storytelling, trend adaptation', domainKnowledge: 'vertical editing, hooks, loops, captions, platform metrics', domainTools: ['knowledge_search'], domainModelCapabilities: ['writing', 'vision'], domainSecurity: ['trend safety', 'asset rights'], domainVerification: ['retention design', 'platform compliance', 'caption clarity'], domainOutput: ['short-form plans', 'scripts', 'edit briefs'], domainCostBase: 2 },
  { slug: 'film-production', name: 'Film / Production', description: 'Plan production pipelines from concept to deliverables.', domainBusiness: 'pre-prod, scheduling, shot design, post-production', domainKnowledge: 'production planning, cinematography, editing workflows, deliverables', domainTools: ['knowledge_search'], domainModelCapabilities: ['vision', 'reasoning', 'writing'], domainSecurity: ['asset licensing', 'safety considerations'], domainVerification: ['storyboard coverage', 'schedule feasibility', 'deliverable spec'], domainOutput: ['production plans', 'shot lists', 'post schedules'], domainCostBase: 3 },
  { slug: 'audio', name: 'Audio', description: 'Plan and produce audio content and sound design.', domainBusiness: 'podcasts, sound design, mixing, accessibility', domainKnowledge: 'audio formats, compression, dialogue, music, loudness', domainTools: ['knowledge_search'], domainModelCapabilities: ['audio', 'reasoning'], domainSecurity: ['royalty-safe audio'], domainVerification: ['loudness standards', 'clarity', 'format compliance'], domainOutput: ['audio plans', 'scripts', 'mix notes'], domainCostBase: 2 },
  { slug: 'music', name: 'Music', description: 'Support music creation, structure and release planning.', domainBusiness: 'songwriting, arrangement, genre study, distribution', domainKnowledge: 'music theory, arrangement, mixing basics, rights', domainTools: ['knowledge_search'], domainModelCapabilities: ['audio', 'reasoning'], domainSecurity: ['respect rights'], domainVerification: ['structural review', 'rights check', 'reference match'], domainOutput: ['music briefs', 'lyrics', 'arrangement notes'], domainCostBase: 3 },
  { slug: 'voice', name: 'Voice', description: 'Plan and produce voice-driven content.', domainBusiness: 'tone, performance, casting, voice identity', domainKnowledge: 'voice direction, pronunciation, pacing, licensing', domainTools: ['knowledge_search'], domainModelCapabilities: ['speech', 'audio'], domainSecurity: ['consent/licensing'], domainVerification: ['pronunciation', 'performance fit', 'format'], domainOutput: ['voice briefs', 'scripts', 'cast specs'], domainCostBase: 2 },
  { slug: 'speech', name: 'Speech', description: 'Create speech and transcription workflows.', domainBusiness: 'TTS, ASR, accessibility, multi-language', domainKnowledge: 'speech synthesis, transcription, diarization, subtitles', domainTools: ['knowledge_search'], domainModelCapabilities: ['speech', 'audio'], domainSecurity: ['recording consent', 'PII redaction'], domainVerification: ['transcription accuracy', 'sync', 'privacy'], domainOutput: ['transcripts', 'subtitles', 'speech plans'], domainCostBase: 2 },
  { slug: '3d', name: '3D', description: 'Plan 3D asset creation and visualization.', domainBusiness: 'geometry, materials, lighting, rendering, pipelines', domainKnowledge: '3D modeling, materials, texturing, lighting, formats', domainTools: ['knowledge_search'], domainModelCapabilities: ['vision', 'reasoning'], domainSecurity: ['asset licensing'], domainVerification: ['geometry/UV check', 'pipeline fit', 'render spec'], domainOutput: ['3D briefs', 'asset specs', 'render plans'], domainCostBase: 4 },
  { slug: 'gaming', name: 'Gaming', description: 'Plan games, mechanics and player experiences.', domainBusiness: 'design pillars, game loops, tuning, monetization', domainKnowledge: 'game design, systems, player psychology, economy balance', domainTools: ['knowledge_search'], domainModelCapabilities: ['reasoning', 'vision'], domainSecurity: ['no false monetization promises'], domainVerification: ['design coherence', 'economy balance', 'player-fairness'], domainOutput: ['game designs', 'systems docs', 'tuning plans'], domainCostBase: 3 },
  { slug: 'automation', name: 'Automation', description: 'Design and operate workflows and business automation.', domainBusiness: 'process mapping, triggers, rules, audits', domainKnowledge: 'automation architectures, integrations, idempotency, error handling', domainTools: ['excel_build', 'knowledge_search'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['safe scopes', 'no destructive changes'], domainVerification: ['trigger logic', 'idempotency', 'failure recovery'], domainOutput: ['automation specs', 'rules', 'runbooks'], domainCostBase: 2 },
  { slug: 'computer-use', name: 'Computer Use', description: 'Plan safe computer-use and controlled agent workflows.', domainBusiness: 'UI actions, accessibility, approval gates, recovery', domainKnowledge: 'GUI context, safe permissions, confirmations, logging', domainTools: ['knowledge_search'], domainModelCapabilities: ['vision', 'reasoning'], domainSecurity: ['approval gates', 'no credential capture'], domainVerification: ['action safety', 'audit record', 'completion evidence'], domainOutput: ['computer-use plans', 'step specs', 'safety protocols'], domainCostBase: 3 },
  { slug: 'browser-automation', name: 'Browser Automation', description: 'Build safe browser workflows and scraping plans.', domainBusiness: 'navigation, forms, extraction, monitoring, robots respect', domainKnowledge: 'browser automation, selectors, rate limits, sites ToS', domainTools: ['web_search', 'page_fetch'], domainModelCapabilities: ['coding', 'reasoning'], domainSecurity: ['robots/ToS aware', 'rate-limit respect', 'no credential steal'], domainVerification: ['selector robustness', 'compliance', 'data quality'], domainOutput: ['automation plans', 'extraction specs', 'compliance notes'], domainCostBase: 2 },
  { slug: 'maps-local-business', name: 'Maps / Local Business', description: 'Plan local business discovery and location intelligence.', domainBusiness: 'local SEO, reputation, proximity, store operations', domainKnowledge: 'local search, citations, reviews, geospatial data', domainTools: ['web_search', 'knowledge_search'], domainModelCapabilities: ['research', 'reasoning'], domainSecurity: ['no private address exposure'], domainVerification: ['location accuracy', 'review evidence', 'local ranking notes'], domainOutput: ['local plans', 'citation lists', 'reputation plans'], domainCostBase: 1 },
  { slug: 'travel', name: 'Travel', description: 'Design itineraries and travel planning workflows.', domainBusiness: 'destinations, logistics, budget, safety, booking options', domainKnowledge: 'travel logistics, itinerary design, local context, risk', domainTools: ['web_search', 'knowledge_search'], domainModelCapabilities: ['research', 'reasoning'], domainSecurity: ['no fabricated availability'], domainVerification: ['route feasibility', 'budget realism', 'safety notes'], domainOutput: ['itineraries', 'trip plans', 'comparisons'], domainCostBase: 1 },
  { slug: 'security', name: 'Security', description: 'Assess and design application, data and operation security.', domainBusiness: 'threat modeling, controls, incident response, compliance', domainKnowledge: 'OWASP, cloud security, secrets, RBAC, monitoring', domainTools: ['knowledge_search', 'code_repository_read'], domainModelCapabilities: ['reasoning', 'research', 'coding'], domainSecurity: ['never output live secrets', 'defense-in-depth'], domainVerification: ['threat coverage', 'control evidence', 'remediation priority'], domainOutput: ['security reports', 'policies', 'IaC checks'], domainCostBase: 3 },
  { slug: 'devops', name: 'DevOps', description: 'Design production deployment and reliability systems.', domainBusiness: 'CI/CD, infrastructure, SRE, observability, rollback', domainKnowledge: 'Docker, K8s, pipelines, monitoring, runbooks', domainTools: ['code_repository_read', 'knowledge_search'], domainModelCapabilities: ['coding', 'reasoning'], domainSecurity: ['least privilege', 'secret injection review'], domainVerification: ['pipeline correctness', 'observability', 'rollback design'], domainOutput: ['deployment plans', 'CI/CD specs', 'runbooks'], domainCostBase: 3 },
  { slug: 'cloud', name: 'Cloud', description: 'Plan cloud architecture, cost and operations.', domainBusiness: 'architectures, cost, security, reliability, migration', domainKnowledge: 'AWS/Azure/GCP, IAM, networking, cost optimization', domainTools: ['knowledge_search'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['IAM least privilege', 'no credentials'], domainVerification: ['cost model', 'reliability', 'security baseline'], domainOutput: ['cloud architectures', 'migrations', 'cost plans'], domainCostBase: 3 },
  { slug: 'api-engineering', name: 'API Engineering', description: 'Design robust, secure and versioned APIs.', domainBusiness: 'contracts, error handling, auth, rate limits, monetization', domainKnowledge: 'REST/GraphQL, OpenAPI, idempotency, pagination, auth', domainTools: ['knowledge_search'], domainModelCapabilities: ['coding', 'reasoning'], domainSecurity: ['input validation', 'authz review'], domainVerification: ['contract tests', 'error coverage', 'security checks'], domainOutput: ['API specs', 'contracts', 'error matrices'], domainCostBase: 2 },
  { slug: 'integrations', name: 'Integrations', description: 'Design and map systems integrations.', domainBusiness: 'data flow, sync, middleware, error recovery, events', domainKnowledge: 'integration patterns, webhooks, queues, idempotency', domainTools: ['knowledge_search'], domainModelCapabilities: ['coding', 'reasoning'], domainSecurity: ['safe scopes', 'credential handling'], domainVerification: ['contract mapping', 'sync fidelity', 'failure recovery'], domainOutput: ['integration specs', 'sequence diagrams', 'error maps'], domainCostBase: 2 },
  { slug: 'agent-engineering', name: 'Agent Engineering', description: 'Build reliable agent workflows and orchestration.', domainBusiness: 'prompt design, tool use, memory, guardrails, eval', domainKnowledge: 'agent architecture, tool calling, context budgets, safety', domainTools: ['knowledge_search'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['tool allowlists', 'prompt injection defense'], domainVerification: ['completion rate', 'tool-use correctness', 'guardrail checks'], domainOutput: ['agent specs', 'prompt suites', 'eval plans'], domainCostBase: 3 },
  { slug: 'agent-testing', name: 'Agent Testing', description: 'Create agent test suites and internal validation harnesses.', domainBusiness: 'unit, integration, e2e, adversarial, regression tests', domainKnowledge: 'test design, fuzzing, scenarios, quality gates', domainTools: ['knowledge_search'], domainModelCapabilities: ['coding', 'reasoning'], domainSecurity: ['safe test fixtures'], domainVerification: ['coverage', 'adversarial coverage', 'regression evidence'], domainOutput: ['test plans', 'test cases', 'quality reports'], domainCostBase: 2 },
  { slug: 'agent-evaluation', name: 'Agent Evaluation', description: 'Benchmark and score agent quality.', domainBusiness: 'rubrics, grading, model choices, evals', domainKnowledge: 'eval metrics, human judgment, statistical confidence', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'research'], domainSecurity: ['no test data leakage'], domainVerification: ['inter-annotator agreement', 'statistical significance', 'score robustness'], domainOutput: ['eval reports', 'gradecards', 'benchmarks'], domainCostBase: 2 },
  { slug: 'knowledge-management', name: 'Knowledge Management', description: 'Build corpora, knowledge bases and retrieval systems.', domainBusiness: 'curation, taxonomy, search, retrieval quality', domainKnowledge: 'information architecture, indexing, RAG, content lifecycle', domainTools: ['knowledge_search', 'file_parse_text'], domainModelCapabilities: ['research', 'reasoning'], domainSecurity: ['access control', 'no sensitive leakage'], domainVerification: ['retrieval precision', 'coverage', 'freshness'], domainOutput: ['knowledge maps', 'taxonomies', 'RAG designs'], domainCostBase: 2 },
  { slug: 'personal-productivity', name: 'Personal Productivity', description: 'Organize priorities, time and workflow systems.', domainBusiness: 'tasks, time management, habits, review cycles', domainKnowledge: 'prioritization, timeboxing, systems, reflection', domainTools: ['knowledge_search'], domainModelCapabilities: ['reasoning', 'writing'], domainSecurity: ['keep personal data safe'], domainVerification: ['priority alignment', 'effort realism', 'review cadence'], domainOutput: ['productivity plans', 'systems', 'weekly reviews'], domainCostBase: 1 },
  { slug: 'enterprise-operations', name: 'Enterprise Operations', description: 'Design cross-functional enterprise processes.', domainBusiness: 'process standardization, governance, reporting, tooling', domainKnowledge: 'process excellence, governance, operational metrics, change management', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'writing'], domainSecurity: ['confidentiality controls'], domainVerification: ['process completeness', 'role clarity', 'governance check'], domainOutput: ['operating models', 'process maps', 'governance docs'], domainCostBase: 2 },
  { slug: 'procurement', name: 'Procurement', description: 'Plan sourcing, vendor and procurement workflows.', domainBusiness: 'vendor research, RFPs, comparison, negotiation, spend', domainKnowledge: 'source-to-pay, vendor evaluation, contracts, spend analytics', domainTools: ['web_search', 'knowledge_search', 'excel_build'], domainModelCapabilities: ['research', 'reasoning'], domainSecurity: ['no biased vendor info'], domainVerification: ['vendor evidence', 'cost model', 'risk review'], domainOutput: ['sourcing plans', 'RFPs', 'vendor matrices'], domainCostBase: 2 },
  { slug: 'marketplace', name: 'Marketplace', description: 'Design two-sided marketplace strategy and operations.', domainBusiness: 'supply/demand, liquidity, trust, pricing, fees', domainKnowledge: 'marketplace networks, incentives, trust signals, monetization', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'research'], domainSecurity: ['buyer/seller data protection'], domainVerification: ['liquidity logic', 'pricing fairness', 'trust mechanics'], domainOutput: ['marketplace strategies', 'fee structures', 'trust systems'], domainCostBase: 2 },
  { slug: 'ai-economy', name: 'AI Economy', description: 'Model the business and monetization of AI products.', domainBusiness: 'AI pricing, unit economics, cost per task, margin', domainKnowledge: 'AI economics, token costs, value pricing, adoption', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'research'], domainSecurity: ['no false revenue promises'], domainVerification: ['cost model', 'margin check', 'value evidence'], domainOutput: ['AI business models', 'pricing packs', 'margin analyses'], domainCostBase: 2 },
  { slug: 'compliance', name: 'Compliance', description: 'Build compliant controls and audit-ready processes.', domainBusiness: 'regulatory mapping, evidence collection, controls', domainKnowledge: 'GDPR, SOC2, accessibility, content policy, audit trails', domainTools: ['knowledge_search'], domainModelCapabilities: ['reasoning', 'research'], domainSecurity: ['no PII leakage'], domainVerification: ['control mapping', 'evidence completeness', 'audit flow'], domainOutput: ['compliance matrices', 'policies', 'evidenced controls'], domainCostBase: 3 },
  { slug: 'quality-assurance', name: 'Quality Assurance', description: 'Design and execute quality assurance workflows.', domainBusiness: 'test coverage, defect triage, release quality', domainKnowledge: 'QA methods, risk-based testing, defect management', domainTools: ['knowledge_search'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['safe test data'], domainVerification: ['coverage matrix', 'defect evidence', 'release gate'], domainOutput: ['QA plans', 'test matrices', 'quality reports'], domainCostBase: 2 },
  { slug: 'project-management', name: 'Project Management', description: 'Plan and track projects to completion.', domainBusiness: 'scope, milestones, risks, communications, stakeholders', domainKnowledge: 'project planning, scheduling, risk, status reporting', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'writing'], domainSecurity: ['confidentiality of materials'], domainVerification: ['scope discipline', 'risk coverage', 'deliverable tracking'], domainOutput: ['project plans', 'risk registers', 'status reports'], domainCostBase: 1 },
  { slug: 'workflow-automation', name: 'Workflow Automation', description: 'Build reusable workflows and integrations.', domainBusiness: 'workflow modeling, triggers, recovery, handoffs', domainKnowledge: 'BPMN, queues, idempotency, logging, versioning', domainTools: ['knowledge_search', 'excel_build'], domainModelCapabilities: ['reasoning', 'coding'], domainSecurity: ['scope-safe actions', 'audit logging'], domainVerification: ['step dependencies', 'failure handling', 'idempotency'], domainOutput: ['workflow designs', 'runbooks', 'recovery plans'], domainCostBase: 2 },
  { slug: 'specialized-industry', name: 'Specialized Industry', description: 'Deliver horizontal specialist work for specialized industries.', domainBusiness: 'industry-specific domain advisory and operations', domainKnowledge: 'industry verticals, workflows, compliance, terminology', domainTools: ['knowledge_search', 'web_search'], domainModelCapabilities: ['reasoning', 'research', 'writing'], domainSecurity: ['industry confidentiality'], domainVerification: ['industry evidence', 'workflow fit', 'compliance note'], domainOutput: ['industry advisories', 'workflows', 'references'], domainCostBase: 2 },
];

const SPECIALIZATIONS: SpecializationProfile[] = [
  { key: 'strategist', name: 'Strategic Architect', responsibility: 'Translate objectives into a complete, evidence-based plan.', inputs: ['goal', 'context', 'constraints'], outputs: ['strategy document', 'milestone plan', 'risk map'], workflow: ['clarify objective', 'scan context', 'select strategy', 'map milestones', 'define risks'], verification: ['objective alignment', 'evidence check', 'resource feasibility'], security: ['no sensitive data leakage'], modelCapabilities: ['reasoning', 'research'] },
  { key: 'researcher', name: 'Research Analyst', responsibility: 'Discover, compare and cite credible information.', inputs: ['question', 'scope', 'preferred sources'], outputs: ['research report', 'source table', 'evidence summary'], workflow: ['identify research question', 'search sources', 'grade credibility', 'extract evidence', 'rank findings'], verification: ['source verification', 'citation completeness', 'no fabrication'], security: ['no fabricated citations'], modelCapabilities: ['research', 'long_context'] },
  { key: 'analyst', name: 'Data Analyst', responsibility: 'Analyze structured data and produce readable operational insight.', inputs: ['dataset', 'metrics', 'question'], outputs: ['analysis report', 'tables', 'recommendations'], workflow: ['profile data', 'define metrics', 'compute segmentation', 'find anomalies', 'recommend'], verification: ['metric correctness', 'sample validation', 'no over-claiming'], security: ['privacy-safe data', 'no PII exposure'], modelCapabilities: ['research', 'coding', 'reasoning'] },
  { key: 'architect', name: 'Systems Architect', responsibility: 'Design the system/architecture required to achieve the goal.', inputs: ['requirements', 'existing architecture', 'constraints'], outputs: ['architecture diagram plan', 'component spec', 'tradeoffs'], workflow: ['capture requirements', 'evaluate alternatives', 'define components', 'specify interfaces', 'document tradeoffs'], verification: ['requirement coverage', 'scalability check', 'feasibility'], security: ['least-privilege', 'no secret exposure'], modelCapabilities: ['reasoning', 'coding'] },
  { key: 'designer', name: 'Experience Designer', responsibility: 'Design user-facing or content experiences with clarity and accessibility.', inputs: ['audience', 'content', 'brand'], outputs: ['design spec', 'content layouts', 'accessibility notes'], workflow: ['profile audience', 'define flow', 'design components', 'write copy', 'audit accessibility'], verification: ['audience fit', 'WCAG check', 'brand consistency'], security: ['respect content rights'], modelCapabilities: ['vision', 'writing'] },
  { key: 'author', name: 'Content Author', responsibility: 'Produce polished, accurate content for the objective.', inputs: ['topic', 'audience', 'tone'], outputs: ['content draft', 'revise pass', 'style notes'], workflow: ['outline', 'research evidence', 'write draft', 'proofread', 'polish'], verification: ['fact check', 'voice alignment', 'readability'], security: ['no plagiarism'], modelCapabilities: ['writing', 'research'] },
  { key: 'editor', name: 'Content Editor', responsibility: 'Edit for clarity, consistency and quality.', inputs: ['draft', 'goals', 'style guide'], outputs: ['edited content', 'edit log', 'quality score'], workflow: ['review structure', 'verify claims', 'improve clarity', 'apply style', 'flag issues'], verification: ['fact check', 'consistency', 'tone check'], security: ['preserve confidentiality'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'builder', name: 'Implementation Builder', responsibility: 'Turn plans into concrete deliverables.', inputs: ['plan', 'inputs', 'constraints'], outputs: ['deliverable', 'implementation note', 'next steps'], workflow: ['parse plan', 'prepare inputs', 'execute steps', 'verify output', 'document'], verification: ['requirement match', 'output completeness', 'evidence of execution'], security: ['safe scopes', 'no destructive actions'], modelCapabilities: ['coding', 'reasoning', 'vision'] },
  { key: 'auditor', name: 'Quality Auditor', responsibility: 'Audit quality, accuracy and consistency.', inputs: ['artifact', 'standard', 'checklist'], outputs: ['audit report', 'defect list', 'scorecard'], workflow: ['define standard', 'audit artifacts', 'categorize defects', 'prioritize fixes', 'report'], verification: ['audit traceability', 'defect evidence', 'risk prioritization'], security: ['no data leakage'], modelCapabilities: ['reasoning', 'coding', 'research'] },
  { key: 'optimizer', name: 'Performance Optimizer', responsibility: 'Identify and implement measurable improvement opportunities.', inputs: ['system/content/metrics', 'target'], outputs: ['optimization plan', 'recommendations', 'measurement plan'], workflow: ['baseline metrics', 'find bottlenecks', 'rank improvements', 'implement/plan', 'define measurement'], verification: ['metric improvement', 'cost/benefit', 'no regression'], security: ['safe changes'], modelCapabilities: ['reasoning', 'coding', 'research'] },
  { key: 'validator', name: 'Craft Validation Reviewer', responsibility: 'Validate outputs against declared expectations.', inputs: ['output', 'requirements', 'evidence'], outputs: ['validated report', 'gap list', 'recommended fixes'], workflow: ['extract requirements', 'test output', 'record gaps', 'rank severity', 'conclude'], verification: ['requirement testing', 'evidence strength', 'severity ranking'], security: ['no false approval'], modelCapabilities: ['reasoning', 'coding'] },
  { key: 'planner', name: 'Roadmap Planner', responsibility: 'Break goals into ordered, feasible milestones.', inputs: ['goal', 'timeline', 'resources'], outputs: ['roadmap', 'dependency map', 'estimate'], workflow: ['frame outcome', 'identify phases', 'order dependencies', 'estimate effort', 'set gates'], verification: ['dependency logic', 'effort realism', 'outcome alignment'], security: ['confidentiality'], modelCapabilities: ['reasoning'] },
  { key: 'communicator', name: 'Executive Communicator', responsibility: 'Turn complex outcomes into clear executive communication.', inputs: ['result', 'audience', 'decision'], outputs: ['briefing', 'summary', 'decision memo'], workflow: ['understand result', 'select key facts', 'shape narrative', 'draft briefing', 'verify accuracy'], verification: ['accuracy', 'audience fit', 'decision-readiness'], security: ['no unauthorized disclosure'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'reviewer', name: 'Critical Reviewer', responsibility: 'Render balanced critical review with actionable feedback.', inputs: ['artifact', 'criteria'], outputs: ['review notes', 'recommendations', 'risk notes'], workflow: ['define criteria', 'review artifact', 'identify strengths/risks', 'prioritize recommendations', 'write review'], verification: ['criteria coverage', 'balanced feedback', 'actionability'], security: ['confidentiality'], modelCapabilities: ['reasoning', 'research'] },
  { key: 'negotiator', name: 'Negotiation Analyst', responsibility: 'Prepare negotiation strategy and option analysis.', inputs: ['proposal', 'priorities', 'alternatives'], outputs: ['negotiation plan', 'ask/fallback matrix', 'risk notes'], workflow: ['define interests', 'identify tradeoffs', 'build options', 'rank fallbacks', 'prepare script'], verification: ['interest alignment', 'feasibility', 'risk coverage'], security: ['no leakage of confidential strategy'], modelCapabilities: ['reasoning', 'writing'] },
  { key: 'investigator', name: 'Evidence Investigator', responsibility: 'Dig into claims, comparisons and root causes.', inputs: ['claim', 'data', 'sources'], outputs: ['investigation report', 'evidence map', 'verdict'], workflow: ['frame question', 'collect evidence', 'test claims', 'rank evidence', 'conclude'], verification: ['evidence strength', 'source verification', 'no fabricated findings'], security: ['no hidden PII exposure'], modelCapabilities: ['research', 'reasoning'] },
  { key: 'educator', name: 'Learning Designer', responsibility: 'Design understandable learning experiences.', inputs: ['topic', 'audience', 'level'], outputs: ['learning plan', 'lesson', 'quiz'], workflow: ['define outcomes', 'break into concepts', 'design activities', 'build assessment', 'test understanding'], verification: ['outcome alignment', 'assessment validity', 'accessibility'], security: ['child-safety when relevant'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'coach', name: 'Practice Coach', responsibility: 'Coach practice and skill-building through structured support.', inputs: ['practice area', 'current level', 'goal'], outputs: ['coaching plan', 'practice prompts', 'feedback'], workflow: ['diagnose level', 'choose practice', 'guide attempts', 'give feedback', 'set next drill'], verification: ['progress evidence', 'feedback specificity', 'improvement direction'], security: ['safe personal support'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'translator', name: 'Translation Specialist', responsibility: 'Produce faithful, natural localized output.', inputs: ['source', 'target language', 'tone'], outputs: ['translated content', 'glossary', 'notes'], workflow: ['parse source meaning', 'translate', 'adapt cultural terms', 'back-check', 'finish'], verification: ['meaning fidelity', 'terminology consistency', 'naturalness'], security: ['source confidentiality'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'localizer', name: 'Localization Specialist', responsibility: 'Adapt content for regional context.', inputs: ['content', 'locale', 'requirements'], outputs: ['localized pack', 'QA report', 'adaptation notes'], workflow: ['understand locale', 'adapt content', 'check format/culture', 'QA locale', 'deliver'], verification: ['format/culture fit', 'QA coverage', 'locale standards'], security: ['copyright aware'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'forecaster', name: 'Forecast Modeler', responsibility: 'Build forecasts and scenario models.', inputs: ['history', 'assumptions', 'horizon'], outputs: ['forecast', 'scenario table', 'assumption log'], workflow: ['collect history', 'state assumptions', 'build model', 'run scenarios', 'document limits'], verification: ['assumption traceability', 'model sanity', 'scenario coverage'], security: ['no sensitive base data leak'], modelCapabilities: ['coding', 'reasoning', 'research'] },
  { key: 'risk-analyst', name: 'Risk Analyst', responsibility: 'Identify, grade and mitigate risk.', inputs: ['project', 'environment', 'controls'], outputs: ['risk register', 'score matrix', 'mitigation plan'], workflow: ['list risks', 'assess impact/likelihood', 'rank', 'design controls', 'track'], verification: ['risk coverage', 'probability grading', 'control feasibility'], security: ['confidentiality'], modelCapabilities: ['reasoning', 'research'] },
  { key: 'quality-engineer', name: 'Quality Engineer', responsibility: 'Design test and quality gates.', inputs: ['product', 'scope', 'criteria'], outputs: ['test plan', 'test cases', 'quality gate'], workflow: ['map requirements', 'design tests', 'execute', 'categorize defects', 'report'], verification: ['requirements coverage', 'failure evidence', 'gate clarity'], security: ['safe test data'], modelCapabilities: ['coding', 'reasoning'] },
  { key: 'systems-operator', name: 'Reliability Operator', responsibility: 'Operate systems reliably with runbooks and recovery.', inputs: ['system', 'status', 'incidents'], outputs: ['operating plan', 'runbook', 'recovery plan'], workflow: ['assess state', 'define procedures', 'monitor signals', 'escalate', 'recover'], verification: ['procedure coverage', 'error handling', 'rollback path'], security: ['least privilege', 'no secret exposure'], modelCapabilities: ['coding', 'reasoning'] },
  { key: 'compliance-officer', name: 'Compliance Officer', responsibility: 'Map requirements to controls and evidence.', inputs: ['policy', 'system', 'requirements'], outputs: ['control matrix', 'evidence plan', 'gap report'], workflow: ['identify requirements', 'map controls', 'check evidence', 'grade gaps', 'produce'], verification: ['requirement coverage', 'evidence validity', 'audit readiness'], security: ['no PII leakage'], modelCapabilities: ['reasoning', 'research'] },
  { key: 'sales-strategist', name: 'Sales Strategist', responsibility: 'Build qualification, outreach and closing strategies.', inputs: ['product', 'buyer', 'pipeline'], outputs: ['sales plan', 'outreach sequence', 'deal notes'], workflow: ['define buyer', 'build value message', 'qualify leads', 'sequence outreach', 'plan closing'], verification: ['buyer fit', 'message clarity', 'pipeline logic'], security: ['contact confidentiality'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'crm-specialist', name: 'CRM Specialist', responsibility: 'Design customer data flows and lifecycle automation.', inputs: ['contacts', 'processes', 'tools'], outputs: ['CRM design', 'automation flows', 'report spec'], workflow: ['map lifecycle', 'design data model', 'build automation', 'define reports', 'test'], verification: ['data integrity', 'stage consistency', 'automation coverage'], security: ['no contact sale'], modelCapabilities: ['reasoning', 'coding'] },
  { key: 'support-engineer', name: 'Support Engineer', responsibility: 'Resolve support issues and improve knowledge.', inputs: ['ticket', 'context', 'knowledge base'], outputs: ['resolution', 'answer', 'KB patch'], workflow: ['parse issue', 'consult KB', 'diagnose', 'resolve', 'document'], verification: ['root cause', 'usable answer', 'policy compliance'], security: ['no PII leak'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'growth-marketer', name: 'Growth Marketer', responsibility: 'Propose experiment-driven growth plans.', inputs: ['product', 'audience', 'data'], outputs: ['growth plan', 'experiment list', 'metrics'], workflow: ['find bottlenecks', 'generate ideas', 'prioritize', 'define metrics', 'plan'], verification: ['idea evidence', 'metric specificity', 'bias control'], security: ['no deceptive tactics'], modelCapabilities: ['research', 'writing'] },
  { key: 'ad-analyst', name: 'Advertising Analyst', responsibility: 'Analyze and build compliant ad strategies.', inputs: ['campaign', 'budget', 'audience'], outputs: ['ad plan', 'budget model', 'creative brief'], workflow: ['define goal', 'segment audience', 'build message', 'allocate budget', 'set measurement'], verification: ['policy compliance', 'budget logic', 'creative relevance'], security: ['no misleading claims'], modelCapabilities: ['research', 'writing'] },
  { key: 'seo-engineer', name: 'SEO Engineer', responsibility: 'Build search visibility strategies and audits.', inputs: ['website', 'keywords', 'goals'], outputs: ['SEO audit', 'strategy', 'content briefs'], workflow: ['crawl analysis', 'keyword map', 'technical audit', 'content plan', 'measure plan'], verification: ['keyword coverage', 'technical checks', 'no spam tactics'], security: ['no black-hat promotion'], modelCapabilities: ['research', 'writing'] },
  { key: 'content-strategist', name: 'Content Strategist', responsibility: 'Design content ecosystems and calendars.', inputs: ['brand', 'audience', 'channels'], outputs: ['content strategy', 'topic map', 'calendar'], workflow: ['map buyers', 'find themes', 'design clusters', 'prioritize', 'schedule'], verification: ['audience value', 'channel fit', 'topical coverage'], security: ['respect copyright'], modelCapabilities: ['research', 'writing'] },
  { key: 'social-strategist', name: 'Social Strategist', responsibility: 'Create platform-aware social programs.', inputs: ['brand', 'audience', 'channels'], outputs: ['social strategy', 'calendar', 'content system'], workflow: ['profile audience', 'review platform norms', 'build pillars', 'write system', 'measure'], verification: ['platform compliance', 'brand consistency', 'audience fit'], security: ['no impersonation'], modelCapabilities: ['writing', 'vision', 'research'] },
  { key: 'video-strategist', name: 'Video Strategist', responsibility: 'Plan video formats, scripts and distribution.', inputs: ['goal', 'audience', 'platform'], outputs: ['video strategy', 'script', 'shot list'], workflow: ['define outcome', 'select format', 'write hook', 'draft script', 'production list'], verification: ['story clarity', 'platform fit', 'ritual/CTA effectiveness'], security: ['asset rights'], modelCapabilities: ['writing', 'vision'] },
  { key: 'ecommerce-manager', name: 'E-commerce Analyst', responsibility: 'Optimize store performance and product assets.', inputs: ['store data', 'products', 'target'], outputs: ['store audit', 'listing plan', 'growth plan'], workflow: ['audit store', 'find conversion gaps', 'optimize listings', 'plan merchandising', 'measure'], verification: ['listing accuracy', 'conversion logic', 'clear call-to-action'], security: ['no price/inventory manipulation'], modelCapabilities: ['research', 'writing', 'coding'] },
  { key: 'product-manager', name: 'Product Manager', responsibility: 'Define product direction with evidence and discipline.', inputs: ['user problem', 'market', 'existing product'], outputs: ['PRD', 'roadmap', 'prioritization'], workflow: ['understand problem', 'evidence gather', 'scope options', 'define success', 'prioritize'], verification: ['problem evidence', 'success metric', 'feasibility'], security: ['no confidential plans'], modelCapabilities: ['reasoning', 'research', 'writing'] },
  { key: 'financial-modeler', name: 'Financial Modeler', responsibility: 'Build robust financial models and scenarios.', inputs: ['drivers', 'history', 'assumptions'], outputs: ['financial model', 'scenario', 'sensitivity'], workflow: ['define drivers', 'build assumptions', 'model flows', 'stress test', 'document'], verification: ['formula audit', 'assumption source', 'scenario logic'], security: ['no untrusted formula execution'], modelCapabilities: ['coding', 'reasoning'] },
  { key: 'accountant', name: 'Accounting Operations Analyst', responsibility: 'Support reconciliations and reporting integrity.', inputs: ['ledgers', 'rules', 'period'], outputs: ['reconciliation', 'report', 'issues'], workflow: ['pull data', 'reconcile', 'flag discrepancies', 'document', 'report'], verification: ['balance check', 'evidence trail', 'period accuracy'], security: ['confidential financial data'], modelCapabilities: ['reasoning', 'coding'] },
  { key: 'legal-researcher', name: 'Legal Information Researcher', responsibility: 'Produce general legal-information research with disclaimers.', inputs: ['question', 'jurisdiction', 'facts'], outputs: ['legal info brief', 'plain-language notes', 'checklist'], workflow: ['frame question', 'research general sources', 'synthesize', 'add caveats', 'deliver'], verification: ['source accuracy', 'disclaimer', 'jurisdiction note'], security: ['no attorney-client advice'], modelCapabilities: ['research', 'reasoning'] },
  { key: 'hr-adviser', name: 'HR Adviser', responsibility: 'Design fair recruitment and people processes.', inputs: ['role', 'company', 'requirements'], outputs: ['hiring plan', 'rubric', 'process docs'], workflow: ['define role', 'design assessment', 'build rubric', 'plan sourcing', 'document compliance'], verification: ['bias check', 'legality', 'rubric quality'], security: ['candidate data protection'], modelCapabilities: ['reasoning', 'writing'] },
  { key: 'interviewer', name: 'Interview Coach', responsibility: 'Prepare candidates with structured practice.', inputs: ['role', 'candidate', 'competencies'], outputs: ['prep plan', 'question set', 'feedback'], workflow: ['understand role', 'select questions', 'practice answers', 'give structured feedback', 'plan action'], verification: ['answer structure', 'relevance', 'actionability'], security: ['no leaked questions'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'writing-coach', name: 'Writing Coach', responsibility: 'Improve written work through concrete editing.', inputs: ['draft', 'goal', 'audience'], outputs: ['edits', 'rewrite', 'coaching'], workflow: ['assess goal', 'identify weak spots', 'rework', 'explain', 'provide next'], verification: ['message clarity', 'audience fit', 'improvement evidence'], security: ['no plagiarism'], modelCapabilities: ['writing', 'reasoning'] },
  { key: 'prompt-engineer', name: 'Prompt & Instruction Engineer', responsibility: 'Design crisp instructions that drive reliable outcomes.', inputs: ['task', 'context', 'output'], outputs: ['prompt', 'rules', 'evaluation'], workflow: ['define objective', 'write instruction', 'add constraints', 'test cases', 'refine'], verification: ['instruction clarity', 'edge cases', 'evaluation'], security: ['injection defense', 'no hidden secrets'], modelCapabilities: ['reasoning', 'writing'] },
  { key: 'tool-engineer', name: 'Tool & Integration Engineer', responsibility: 'Design safe tool schemas and integrations.', inputs: ['capability', 'permissions', 'system'], outputs: ['tool spec', 'integration plan', 'schema'], workflow: ['identify capability', 'define input/output', 'set permissions', 'map integration', 'document'], verification: ['schema correctness', 'permission safety', 'failure cases'], security: ['allowlist scopes', 'no credential leak'], modelCapabilities: ['coding', 'reasoning'] },
  { key: 'integration-architect', name: 'Integration Architect', responsibility: 'Map systems and design reliable data flows.', inputs: ['systems', 'data', 'objectives'], outputs: ['integration map', 'sequence', 'error plan'], workflow: ['map endpoints', 'define contracts', 'plan sync', 'design failure handling', 'document'], verification: ['contract coverage', 'idempotency', 'error recovery'], security: ['secret-safe', 'scope-safe'], modelCapabilities: ['coding', 'reasoning'] },
  { key: 'security-gate', name: 'Security Reviewer', responsibility: 'Review for security risks and unsafe behavior.', inputs: ['artifact/config', 'threats'], outputs: ['security review', 'findings', 'recommendations'], workflow: ['asset inventory', 'threat model', 'inspect', 'grade severity', 'recommend'], verification: ['threat coverage', 'evidence-based', 'no false positives'], security: ['never output live secrets'], modelCapabilities: ['reasoning', 'coding', 'research'] },
  { key: 'ux-evaluator', name: 'Experience Evaluator', responsibility: 'Evaluate usability and accessibility of deliverables.', inputs: ['experience', 'users', 'criteria'], outputs: ['UX review', 'usability findings', 'fix list'], workflow: ['set criteria', 'walk through', 'evaluate', 'grade accessibility', 'recommend'], verification: ['user task success', 'WCAG coverage', 'clarity'], security: ['no sensitive user data'], modelCapabilities: ['vision', 'reasoning', 'writing'] },
  { key: 'finance-director', name: 'Finance Director', responsibility: 'Direct financial planning and funding strategy.', inputs: ['financials', 'strategy', 'market'], outputs: ['budget', 'forecast', 'funding model'], workflow: ['gather financials', 'set assumptions', 'build budget', 'stress test', 'present'], verification: ['model integrity', 'assumption quality', 'scenario coverage'], security: ['confidential financials'], modelCapabilities: ['reasoning', 'coding'] },
  { key: 'procurement-specialist', name: 'Procurement Specialist', responsibility: 'Research and evaluate vendors and proposals.', inputs: ['need', 'vendors', 'budget'], outputs: ['vendor matrix', 'RFP', 'sourcing plan'], workflow: ['define requirement', 'research candidates', 'compare', 'negotiate plan', 'recommend'], verification: ['vendor evidence', 'cost completeness', 'risk review'], security: ['no vendor favoritism'], modelCapabilities: ['research', 'reasoning'] },
  { key: 'project-director', name: 'Project Director', responsibility: 'Direct large projects and stakeholders.', inputs: ['initiative', 'stakeholders', 'constraints'], outputs: ['project charter', 'plan', 'communications plan'], workflow: ['scope initiative', 'identify stakeholders', 'build plan', 'manage risks', 'set cadence'], verification: ['scope discipline', 'risk coverage', 'stakeholder alignment'], security: ['confidential materials'], modelCapabilities: ['reasoning', 'writing'] },
];

export const AGENT_CATEGORIES = DOMAINS.map((domain) => ({
  slug: domain.slug,
  name: domain.name,
  description: domain.description,
  icon: 'bot',
}));

function buildDefinition(domain: DomainBlueprint, spec: SpecializationProfile, index: number): AgentDefinition {
  const key = `${domain.slug}-${spec.key}`;
  const slug = `${domain.slug}-${spec.key}-${String(index + 1).padStart(3, '0')}`;
  const name = `${domain.name} ${spec.name}`;
  const capabilities = [...new Set([...spec.modelCapabilities, ...domain.domainModelCapabilities])];

  const systemInstructions = [
    `You are the ${name} within AKBARAL!, a specialist agent for the ${domain.name} domain.`,
    `Domain business: ${domain.domainBusiness}.`,
    `Domain knowledge: ${domain.domainKnowledge}.`,
    `Your role: ${spec.responsibility}.`,
    'You only use verified inputs; you never fabricate sources, credentials, metrics, or availability.',
    `Constraints: ${[...new Set([...domain.domainSecurity, ...spec.security])].join('; ')}.`,
    `Your verification rules: ${spec.verification.join('; ')}.`,
  ].join('\n');

  return {
    key,
    slug,
    name,
    categorySlug: domain.slug,
    specialization: `${domain.name} / ${spec.name}`,
    systemInstructions,
    capabilities,
    inputs: spec.inputs,
    outputs: spec.outputs,
    modelRequirements: capabilities.includes('reasoning') ? ['reasoning'] : ['writing'],
    toolPermissions: domain.domainTools,
    apiRequirements: domain.domainTools.includes('web_search') ? ['AKBARAL_WEB_SEARCH_ENDPOINT (optional proxy)'] : [],
    workflow: spec.workflow.map((step) => `${step} (${domain.slug})`),
    verificationRules: spec.verification,
    securityPermissions: [...new Set([...domain.domainSecurity, ...spec.security])],
    costUsage: {
      estimatedTokens: 2000 + domain.domainCostBase * 500,
      estimatedCents: domain.domainCostBase,
      priority: domain.domainCostBase >= 3 ? 'high' : domain.domainCostBase === 2 ? 'medium' : 'low',
    },
    fallbackStrategy: `If primary model/provider unavailable, reroute to default balanced model; if source/tool unavailable, return a structured gap report.`,
    evaluationConfig: {
      metrics: ['factual accuracy', 'specialization coverage', 'verification compliance', 'output completeness'],
      rubric: `Score output against ${domain.name} best practices and ${spec.responsibility}.`,
      testCases: [`${domain.name} task for "${spec.responsibility}"`, `edge case for ${domain.slug} target`, `missing-input test`],
    },
  };
}

/**
 * Generate the full agent catalog (domains x specialization profiles).
 */
export function generateAgentDefinitions(): AgentDefinition[] {
  const definitions: AgentDefinition[] = [];
  for (const domain of DOMAINS) {
    SPECIALIZATIONS.forEach((spec, index) => {
      definitions.push(buildDefinition(domain, spec, index));
    });
  }
  return definitions;
}

export function agentDefinitionCount(): number {
  return DOMAINS.length * SPECIALIZATIONS.length;
}

export function listDomainCount(): number {
  return DOMAINS.length;
}
