import {randomUUID} from 'node:crypto';
import path from 'node:path';import os from 'node:os';
process.env.ZA141251SA_DATABASE_URL=process.env.PG_TEST_DATABASE_URL||`file:${path.join(os.tmpdir(),`contra-${randomUUID()}.db`)}`;
process.env.ZA141251SA_SESSION_SECRET='synthetic-contra-tests-not-live-credentials';
import {before,beforeEach,after,it} from 'node:test';import assert from 'node:assert/strict';
import type {ContraAuthority,ContraProject,ContraDelivery,ContraRemittance,ContraReceivingProof,ContraReversal,ContraProvider,ContraUsdReceiver} from './contra-contracts';
const {ContraWorkflow,readContraProof,configuredContraWorkflow}=require('./contra-workflow') as typeof import('./contra-workflow');
const {missionDb:db,applyMissionMigrations,sha256,verifyMissionAudit}=require('../database') as typeof import('../database');
const money=require('../money') as typeof import('../money');
const {updatePolicy,setKillSwitch}=require('../policy') as typeof import('../policy');
import type {Row} from '../database';
const owner={kind:'owner' as const,id:'contra-fixture-owner'}, agent='contra-fixture-agent', other='contra-fixture-other';
const keepAlive=setInterval(()=>{},1000);
let authority:ContraAuthority,project:ContraProject,delivery:ContraDelivery,payout:ContraRemittance,receiving:ContraReceivingProof,reversal:ContraReversal;
let source:ContraProvider,receiver:ContraUsdReceiver,w:InstanceType<typeof ContraWorkflow>,beforeReceiving:(()=>void|Promise<void>)|undefined;
const now=()=>new Date().toISOString();
const tables=['mission_contra_events','mission_contra_payouts','mission_contra_work','mission_contra_accounts','mission_earning_jobs','mission_money_receipts','mission_cash_liabilities','mission_cash_entries','mission_money_transfers','mission_money_operations','mission_money_grants','mission_money_opportunities','mission_cash_accounts'];
before(()=>{applyMissionMigrations();db.run("INSERT INTO mission_owner (id,email,password_hash,role,status) VALUES (?,'fixture-contra@example.test','fixture','owner','active')",[owner.id]);for(const id of [agent,other])db.run("INSERT INTO mission_agents (id,slug,name,role_key,depth,generation,status,mission_role,origin_platform) VALUES (?,?,'Synthetic fixture','specialist',0,'custom','active','worker','fixture')",[id,id]);});
beforeEach(()=>{
  setKillSwitch(false,owner.id);for(const t of tables)db.run(`DELETE FROM ${t}`);
  updatePolicy({currency:'USD',killSwitch:false,autonomousEnabled:true,maxDailySpendCents:100000,maxExpenseCents:10000,requireApprovalAboveCents:500},owner.id);
  for(const id of [agent,other])money.setMoneyGrant(owner,id,{spendLimitCents:0,delegationCents:0,canCreate:false,expiresAt:new Date(Date.now()+86400000).toISOString(),status:'active'});
  const identity={accountId:'synthetic-account'},proof={evidenceRef:'synthetic-proof-not-money',verifiedAt:now(),authenticityVerified:true};
  authority={...identity,...proof,missionOwnerId:owner.id,ownerControlVerified:true,role:'independent',accountType:'individual',identityVerified:true,eligible:true,workflow:'human_assisted',goodStanding:true,evidenceUseAuthorized:true,projectReadApproved:true,deliveryReadApproved:true,paymentReadApproved:true,durableRecordsApproved:true,permissionExpiresAt:new Date(Date.now()+86400000).toISOString()};
  project={...identity,...proof,projectId:'synthetic-project',agreementId:'synthetic-agreement',agreementHash:sha256('synthetic signed agreement'),directEngagementVerified:true,workerClassificationVerified:true,activity:'software_development',upfrontReleasedCents:0,releasedGrossCents:0,clientAcceptance:'pending',acceptedDeliveryHash:null,paymentId:null,clientId:'synthetic-client',scopeHash:sha256('synthetic scope'),kind:'one_time_fixed_escrow',currency:'USD',state:'active',independentClientVerified:true,agreementSignedByBoth:true,rightsCleared:true,fundsStatus:'held',suspended:false,disputed:false,aiAssistanceAllowed:true,clientDataUseAllowed:true,grossCents:20000,escrowFundedCents:20000,independentNetCents:0};
  delivery={...identity,...proof,projectId:project.projectId,agreementId:project.agreementId,clientId:project.clientId,submissionId:'synthetic-submission',submittedAt:now(),state:'submitted',content:'// Synthetic test artifact, not paid work\nexport const answer = 42;'};
  payout={...identity,...proof,payoutId:'synthetic-payout',state:'paid',complete:true,currency:'USD',payoutFeeCents:300,netCents:18200,lines:[{kind:'project_release',projectId:project.projectId,agreementId:project.agreementId,paymentId:'synthetic-payment',currency:'USD',grossCents:20000,feeCents:1500,netCents:18500}]};
  receiving={...identity,...proof,source:'contra',payoutId:payout.payoutId,rail:'synthetic-bank',receivingAccount:'synthetic-mission-account',externalId:'synthetic-credit',state:'settled',direction:'credit',currency:'USD',missionOwnershipVerified:true,grossCents:18200,feeCents:100,netCents:18100,availableBalanceCents:1000000,fxApplied:false};
  reversal={...identity,...proof,source:'contra',payoutId:payout.payoutId,rail:receiving.rail,receivingAccount:receiving.receivingAccount,originalExternalId:receiving.externalId,reversalExternalId:'synthetic-debit',state:'settled',direction:'debit',currency:'USD',missionOwnershipVerified:true,amountCents:18100};
  source={...identity,authority:async()=>structuredClone(authority),project:async()=>structuredClone(project),delivery:async()=>structuredClone(delivery),remittance:async()=>structuredClone(payout)};
  beforeReceiving=undefined;receiver={rail:receiving.rail,receivingAccount:receiving.receivingAccount,verify:async()=>{const snapshot=structuredClone(receiving);await beforeReceiving?.();return snapshot;},reversal:async()=>structuredClone(reversal)};
  w=new ContraWorkflow(source,receiver);
});
after(()=>{try{db.close();}finally{clearInterval(keepAlive);}});
const auth=(id=agent)=>w.authorizeAccount(owner,{agentId:id,reviewRef:'synthetic-human-review',expiresAt:new Date(Date.now()+3600000).toISOString()});
async function assigned(){await auth();return w.assign(owner,project.projectId);}
async function prepared(){const row=await assigned(),draft=w.draft(owner,String(row.id),delivery.content);w.approve(owner,String(row.id),String(draft.content_hash),'synthetic-human-quality-review');await w.beginManualDelivery(owner,String(row.id));delivery.submittedAt=now();delivery.verifiedAt=now();await w.confirmDelivery(owner,String(row.id),delivery.submissionId);return String(row.id);}
async function confirmed(){const id=await prepared();project.independentNetCents=18500;project.fundsStatus='released';project.state='completed';project.clientAcceptance='explicit';project.acceptedDeliveryHash=sha256(delivery.content);project.releasedGrossCents=20000;project.paymentId='synthetic-payment';await w.observePayment(owner,id);return id;}
const settle=(id:string)=>w.reconcile(owner,id,payout.payoutId,receiving.externalId);
const balance=()=>Number(money.ensureCashAccount().available_cents);
const noCash=()=>{assert.equal(balance(),0);assert.equal(db.all('SELECT * FROM mission_money_receipts').length,0);assert.equal(db.all('SELECT * FROM mission_earning_jobs').length,0);};
it('default factory stays blocked; no credential flag registers a cash or spend provider',async()=>{const off=configuredContraWorkflow();assert.equal(off.overview(owner).cashBridgeEnabled,false);assert.equal(off.overview(owner).lifecycle.length,9);await assert.rejects(off.inspect(owner,'project'),/not_configured/);noCash();});
it('all commands require an actual active mission owner, not agent or owner-looking ID',async()=>{
  const actor={kind:'agent' as const,id:agent};assert.throws(()=>w.overview(actor),/owner_required/);await assert.rejects(w.inspect(actor,'project'),/owner_required/);await assert.rejects(w.authorizeAccount(actor,{agentId:agent,reviewRef:'fake',expiresAt:now()}),/owner_required/);await assert.rejects(w.reconcile(actor,'work','p','e'),/owner_required/);await assert.rejects(w.reconcileReversal(actor,'work','r'),/owner_required/);
});
const permissionFailures:Record<string,(a:ContraAuthority)=>void>={
  'no owner control':a=>{a.ownerControlVerified=false;},'different mission owner':a=>{a.missionOwnerId='other';},
  'no lawful record-use permission':a=>{a.evidenceUseAuthorized=false;},'no identity verification':a=>{a.identityVerified=false;},'no eligibility':a=>{a.eligible=false;},'suspended account':a=>{a.goodStanding=false;},
  'no project scope':a=>{a.projectReadApproved=false;},'no delivery scope':a=>{a.deliveryReadApproved=false;},'no payment scope':a=>{a.paymentReadApproved=false;},'no durable evidence permission':a=>{a.durableRecordsApproved=false;},
  'unauthenticated records':a=>{a.authenticityVerified=false;},'platform automation':a=>{a.workflow='bot' as 'human_assisted';},'wrong account':a=>{a.accountId='other';},
  'agency instead of individual':a=>{a.accountType='agency' as 'individual';},'expired permission':a=>{a.permissionExpiresAt='2000-01-01T00:00:00Z';},'stale evidence':a=>{a.verifiedAt='2000-01-01T00:00:00Z';},'future evidence':a=>{a.verifiedAt=new Date(Date.now()+60000).toISOString();},
};
for(const [name,mutate] of Object.entries(permissionFailures))it(`blocks ${name} before persisting provider-derived evidence`,async()=>{mutate(authority);await assert.rejects(auth());assert.equal(db.all('SELECT * FROM mission_contra_accounts').length,0);assert.equal(db.all('SELECT * FROM mission_contra_events').length,0);noCash();});
it('exclusive account and project assignments survive new workflow instances',async()=>{await auth();await assert.rejects(auth(other),/exclusive_account/);const row=await w.assign(owner,project.projectId);const next=new ContraWorkflow(source,receiver);await assert.rejects(next.assign(owner,project.projectId),/exclusive_project/);assert.equal(db.all('SELECT * FROM mission_contra_work').length,1);assert.ok(row.opportunity_id);});
it('inspection is non-executable and no stage before actual settlement credits cash',async()=>{assert.equal((await w.inspect(owner,project.projectId)).executable,false);const id=await confirmed();await w.observePayout(owner,id,payout.payoutId);noCash();});
const projectFailures:Record<string,(c:ContraProject)=>void>={
 'unverified buyer relationship':c=>{c.independentClientVerified=false;},'self purchase':c=>{c.clientId=c.accountId;},'missing rights':c=>{c.rightsCleared=false;},'foreign currency':c=>{c.currency='EUR';},'hourly work':c=>{c.kind='hourly' as 'one_time_fixed_escrow';},'unaccepted offer':c=>{c.agreementSignedByBoth=false;},'unfunded work':c=>{c.escrowFundedCents=0;},'suspended project':c=>{c.suspended=true;},'dispute':c=>{c.disputed=true;},'no AI permission':c=>{c.aiAssistanceAllowed=false;},'no data permission':c=>{c.clientDataUseAllowed=false;},'wrong identity':c=>{c.accountId='other';},'cancelled':c=>{c.state='cancelled';},'inexact gross':c=>{c.grossCents=20000.1;},
};
for(const [name,mutate] of Object.entries(projectFailures))it(`rejects assignment: ${name}`,async()=>{await auth();mutate(project);await assert.rejects(w.assign(owner,project.projectId));assert.equal(db.all('SELECT * FROM mission_contra_work').length,0);noCash();});
it('owner approvals bind exact real artifact bytes and freeze them after approval',async()=>{const r=await assigned(),id=String(r.id);await assert.rejects(w.beginManualDelivery(owner,id),/approved_work/);const draft=w.draft(owner,id,delivery.content);assert.throws(()=>w.approve(owner,id,sha256('wrong'),'review'),/approval_mismatch/);w.approve(owner,id,String(draft.content_hash),'review');assert.throws(()=>w.draft(owner,id,'replacement'),/immutable/);await w.beginManualDelivery(owner,id);await assert.rejects(w.beginManualDelivery(owner,id),/approved_work/);noCash();});
it('revocation while a delivery intent is awaiting proof blocks the outward handoff',async()=>{const r=await assigned(),id=String(r.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'review');source.project=async()=>{w.revokeAccount(owner);return project;};await assert.rejects(w.beginManualDelivery(owner,id),/authorization_required/);assert.equal(db.get<Row>('SELECT state FROM mission_contra_work WHERE id=?',[id])!.state,'approved');});
it('changing the authorized scope prevents delivery',async()=>{const r=await assigned(),id=String(r.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'review');project.scopeHash=sha256('changed');await assert.rejects(w.beginManualDelivery(owner,id),/project_changed/);});
const deliveryFailures:Record<string,(d:ContraDelivery)=>void>={'wrong bytes':d=>{d.content='metadata cannot prove bytes';},'wrong sender':d=>{d.accountId='other';},'wrong recipient':d=>{d.clientId='other';},'wrong submission':d=>{d.submissionId='other';},'wrong project':d=>{d.projectId='other';},'before authorization':d=>{d.submittedAt='2000-01-01T00:00:00Z';}};
for(const [name,mutate] of Object.entries(deliveryFailures))it(`delivery readback rejects ${name}`,async()=>{const r=await assigned(),id=String(r.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'review');await w.beginManualDelivery(owner,id);delivery.submittedAt=now();delivery.verifiedAt=now();mutate(delivery);await assert.rejects(w.confirmDelivery(owner,id,'synthetic-submission'));assert.equal(db.get<Row>('SELECT state FROM mission_contra_work WHERE id=?',[id])!.state,'awaiting_manual_delivery');noCash();});
it('read-only manual delivery recovery remains possible after grant revocation without authorizing more work',async()=>{const id=await prepared();w.revokeAccount(owner);setKillSwitch(true,owner.id);await w.confirmDelivery(owner,id,delivery.submissionId);assert.throws(()=>w.draft(owner,id,'new'),/policy_blocked/);noCash();});
it('complete chain credits only independent receiving net USD, once across concurrent/restarted callers',async()=>{const id=await confirmed();const results=await Promise.all([settle(id),new ContraWorkflow(source,receiver).reconcile(owner,id,payout.payoutId,receiving.externalId)]);assert.equal(results.filter(r=>!r.duplicated).length,1);assert.equal(balance(),18100);assert.equal(money.cashAccount(agent).available_cents,0);assert.equal((await settle(id)).duplicated,true);assert.equal(db.all('SELECT * FROM mission_earning_jobs').length,1);assert.equal(money.verifyCashLedger().ok,true);assert.equal(verifyMissionAudit().ok,true);});
it('earned settlement can be received after mission revocation/freeze without restoring spending authority',async()=>{const id=await confirmed();w.revokeAccount(owner);setKillSwitch(true,owner.id);await settle(id);assert.equal(balance(),18100);assert.throws(()=>money.allocateCash(owner,agent,1,'fixture'),/kill_switch/);});
const payoutFailures:Record<string,(p:ContraRemittance)=>void>={'pending':p=>{p.state='pending';},'partial':p=>{p.complete=false;},'mixed currency':p=>{p.currency='EUR';},'unattributed extra line':p=>{p.lines.push({...p.lines[0]});},'wrong project':p=>{p.lines[0].projectId='other';},'invalid fees':p=>{p.lines[0].feeCents=-1;},'wrong total':p=>{p.netCents=17999;},'wrong gross':p=>{p.lines[0].grossCents=19000;p.lines[0].feeCents=1000;},'wrong payout':p=>{p.payoutId='other';},'wrong owner':p=>{p.accountId='other';}};
for(const [name,mutate] of Object.entries(payoutFailures))it(`payout ${name} is not cash`,async()=>{const id=await confirmed();mutate(payout);await assert.rejects(w.reconcile(owner,id,'synthetic-payout','synthetic-credit'),/blocked_or_uncertain/);noCash();});
const receivingFailures:Record<string,(r:ContraReceivingProof)=>void>={'pending':r=>{r.state='pending';},'balance only':r=>{r.missionOwnershipVerified=false;},'non USD':r=>{r.currency='PKR';},'wrong source':r=>{r.source='freelancer' as 'contra';},'wrong account':r=>{r.receivingAccount='other';},'wrong rail':r=>{r.rail='other';},'wrong movement':r=>{r.externalId='other';},'wrong provider account':r=>{r.accountId='other';},'wrong direction':r=>{r.direction='debit' as 'credit';},'wrong payout':r=>{r.payoutId='other';},'fee mismatch':r=>{r.feeCents=0;},'gross mismatch':r=>{r.grossCents=18100;r.feeCents=0;},'insufficient bank funds':r=>{r.availableBalanceCents=18099;},'stale':r=>{r.verifiedAt='2000-01-01T00:00:00Z';},'future':r=>{r.verifiedAt=new Date(Date.now()+60000).toISOString();}};
for(const [name,mutate] of Object.entries(receivingFailures))it(`receiving ${name} cannot credit or leave partial bookkeeping`,async()=>{const id=await confirmed();mutate(receiving);await assert.rejects(w.reconcile(owner,id,'synthetic-payout','synthetic-credit'),/blocked_or_uncertain/);noCash();assert.equal(db.all('SELECT * FROM mission_contra_payouts').length,0);});
it('missing receiving adapter cannot be substituted by provider balance or caller flags',async()=>{const id=await confirmed();await assert.rejects(new ContraWorkflow(source).reconcile(owner,id,payout.payoutId,receiving.externalId),/not_configured/);noCash();});
it('provider permission loss during independent proof lookup blocks commit',async()=>{const id=await confirmed();beforeReceiving=()=>{authority.evidenceUseAuthorized=false;};await assert.rejects(settle(id),/blocked_or_uncertain/);noCash();});
it('work changes while bank lookup awaits block atomic admission',async()=>{const id=await confirmed();beforeReceiving=()=>{db.run('UPDATE mission_contra_work SET approved_hash=? WHERE id=?',[sha256('changed'),id]);};await assert.rejects(settle(id),/blocked_or_uncertain/);noCash();});
it('a deactivated owner cannot admit funds after an await',async()=>{const id=await confirmed();beforeReceiving=()=>{db.run("UPDATE mission_owner SET status='disabled' WHERE id=?",[owner.id]);};try{await assert.rejects(settle(id),/owner_required/);noCash();}finally{db.run("UPDATE mission_owner SET status='active' WHERE id=?",[owner.id]);}});
it('one physical bank movement cannot be credited by two connectors',async()=>{const id=await confirmed(),externalId='incoming:'+sha256(JSON.stringify([receiving.rail,receiving.receivingAccount,receiving.externalId]));db.run("INSERT INTO mission_money_receipts (provider,external_id,fingerprint,kind,amount_cents,created_at) VALUES ('awin-settlement',?,'synthetic','earning',18100,?)",[externalId,now()]);await assert.rejects(settle(id),/blocked_or_uncertain/);assert.equal(balance(),0);assert.equal(db.all('SELECT * FROM mission_contra_payouts').length,0);});
it('a booked payout cannot be assigned another receiving transfer or payout ID',async()=>{const id=await confirmed();await settle(id);receiving.externalId='other';await assert.rejects(settle(id),/blocked_or_uncertain/);assert.equal(balance(),18100);assert.equal(money.ensureCashAccount().frozen,1);});
it('changed or missing booked payment proof freezes access, not an invented debit',async()=>{const id=await confirmed();await settle(id);project.independentNetCents=0;await assert.rejects(w.observePayment(owner,id),/payment_unconfirmed/);assert.equal(balance(),18100);assert.equal(money.ensureCashAccount().frozen,1);});
it('duplicate reconciliation checks current bank sufficiency, not only original receipt',async()=>{const id=await confirmed();await settle(id);receiving.availableBalanceCents=0;await assert.rejects(settle(id),/blocked_or_uncertain/);assert.equal(balance(),18100);assert.equal(money.ensureCashAccount().frozen,1);});
it('independent reversals are exact, bounded and idempotent',async()=>{const id=await confirmed();await settle(id);assert.equal((await w.reconcileReversal(owner,id,reversal.reversalExternalId)).duplicated,false);assert.equal(balance(),0);assert.equal((await w.reconcileReversal(owner,id,reversal.reversalExternalId)).duplicated,true);assert.equal(money.verifyCashLedger().ok,true);assert.equal(verifyMissionAudit().ok,true);});
it('partial reversals cannot exceed original actual net and cannot restore earning credit',async()=>{const id=await confirmed();await settle(id);reversal.amountCents=10000;await w.reconcileReversal(owner,id,reversal.reversalExternalId);assert.equal(balance(),8100);reversal.reversalExternalId='second';await assert.rejects(w.reconcileReversal(owner,id,'second'),/blocked_or_uncertain/);assert.equal(balance(),8100);await assert.rejects(settle(id),/blocked_or_uncertain/);});
for(const field of ['missionOwnershipVerified','currency','source','state','originalExternalId','reversalExternalId','receivingAccount'] as const)it(`reversal rejects unverified ${field}`,async()=>{const id=await confirmed();await settle(id);(reversal as unknown as Record<string,unknown>)[field]=field==='missionOwnershipVerified'?false:'other';await assert.rejects(w.reconcileReversal(owner,id,'synthetic-debit'),/blocked_or_uncertain/);assert.equal(balance(),18100);});
it('original credit ID cannot masquerade as a reversal',async()=>{const id=await confirmed();await settle(id);await assert.rejects(w.reconcileReversal(owner,id,receiving.externalId),/original_settlement_required/);assert.equal(balance(),18100);});
it('adapter errors and getter failures cannot disclose credentials',async()=>{const id=await confirmed();source.remittance=async()=>{throw new Error('credential-SYNTHETIC-DO-NOT-EXPOSE');};await assert.rejects(settle(id),e=>e instanceof Error&&!e.message.includes('credential-'));source.authority=async()=>Object.defineProperty({...authority},'eligible',{enumerable:true,get(){throw new Error('credential-SYNTHETIC-DO-NOT-EXPOSE');}});await assert.rejects(auth(),e=>e instanceof Error&&e.message==='contra_verification_unavailable');noCash();});
it('proof deadline aborts ignored/late adapters and cannot admit later data',async t=>{t.mock.timers.enable({apis:['setTimeout']});let signal:AbortSignal|undefined,resolve!:(value:{n:number})=>void;const waiting=readContraProof(s=>{signal=s;return new Promise(r=>{resolve=r;});});const rejected=assert.rejects(waiting,/verification_unavailable/);await Promise.resolve();await Promise.resolve();t.mock.timers.tick(30001);await rejected;assert.equal(signal!.aborted,true);resolve({n:1});await Promise.resolve();noCash();});
it('pending provider payout observations never become cash and cannot be rebound to other work',async()=>{const id=await confirmed();payout.state='pending';assert.equal((await w.observePayout(owner,id,payout.payoutId)).cashCredited,false);await assert.rejects(settle(id));noCash();payout.state='paid';await settle(id);payout.payoutId='new-id';receiving.payoutId='new-id';await assert.rejects(settle(id));assert.equal(balance(),18100);});
it('owner authority and grant expiry are checked after account verification awaits',async()=>{source.authority=async()=>{db.run("UPDATE mission_money_grants SET status='revoked' WHERE agent_id=?",[agent]);return authority;};await assert.rejects(auth());assert.equal(db.all('SELECT * FROM mission_contra_accounts').length,0);});
it('lost booked delivery evidence freezes funds without inventing a bank debit',async()=>{const id=await confirmed();await settle(id);delivery.content='different';await assert.rejects(w.confirmDelivery(owner,id,delivery.submissionId),/delivery_unconfirmed/);assert.equal(balance(),18100);assert.equal(money.ensureCashAccount().frozen,1);});
it('verified reversal preserves nonnegative isolated ledgers after owner allocation',async()=>{const id=await confirmed();await settle(id);money.allocateCash(owner,agent,15000,'synthetic-allocation');await w.reconcileReversal(owner,id,reversal.reversalExternalId);assert.ok(db.all<Row>('SELECT available_cents,held_cents FROM mission_cash_accounts').every(a=>Number(a.available_cents)>=0&&Number(a.held_cents)>=0));assert.equal(money.verifyCashLedger().ok,true);});
it('one mission owner cannot provision duplicate personal Contra accounts for more agents',async()=>{await auth();authority.accountId='second-account';const second=new ContraWorkflow({...source,accountId:'second-account'},receiver);await assert.rejects(second.authorizeAccount(owner,{agentId:other,reviewRef:'synthetic',expiresAt:new Date(Date.now()+3600000).toISOString()}),/exclusive_account_conflict/);assert.equal(db.all('SELECT * FROM mission_contra_accounts').length,1);});
for(const stage of ['project','delivery','payout','receiving'] as const)it(`unauthenticated ${stage} is not provider/receiving proof`,async()=>{
  const id=await confirmed();({project,delivery,payout,receiving}[stage]).authenticityVerified=false;await assert.rejects(settle(id));noCash();
});
for(const kind of ['compensation','cash_advance','tip','refund','expense_cancellation'])it(`${kind} cannot masquerade as customer-paid project work`,async()=>{const id=await confirmed();payout.lines[0].kind=kind as 'project_release';await assert.rejects(settle(id));noCash();});
it('a completed project still in fundsStatus is not confirmed payment or cash',async()=>{const id=await prepared();project.state='completed';project.independentNetCents=18500;await assert.rejects(w.observePayment(owner,id));noCash();});
it('an active project marked cleared cannot bypass actual project completion',async()=>{const id=await prepared();project.fundsStatus='released';project.independentNetCents=18500;await assert.rejects(w.observePayment(owner,id));noCash();});
it('withdrawal fee, seller deduction and receiving fee are separately attributed',async()=>{const id=await confirmed();assert.equal(payout.lines[0].grossCents,20000);assert.equal(payout.lines[0].feeCents,1500);assert.equal(payout.payoutFeeCents,300);assert.equal(receiving.feeCents,100);await settle(id);assert.equal(balance(),18100);});
for(const fee of [-1,0,1.5,17000,NaN])it(`invalid/mismatched withdrawal deduction ${fee} never credits cash`,async()=>{const id=await confirmed();payout.payoutFeeCents=fee;await assert.rejects(settle(id));noCash();});
it('seller earnings cannot change between confirmation and remittance',async()=>{const id=await confirmed();project.independentNetCents=15000;payout.lines[0].feeCents=5000;payout.lines[0].netCents=15000;await assert.rejects(settle(id));noCash();});
it('cancellation during receiving lookup blocks final admission',async()=>{const id=await confirmed();beforeReceiving=()=>{project.state='cancelled';};await assert.rejects(settle(id));noCash();});
it('withdrawal failure during receiving lookup blocks final admission',async()=>{const id=await confirmed();beforeReceiving=()=>{payout.state='pending';};await assert.rejects(settle(id));noCash();});
it('an unauthenticated reversal freezes rather than inventing a debit',async()=>{const id=await confirmed();await settle(id);reversal.authenticityVerified=false;await assert.rejects(w.reconcileReversal(owner,id,reversal.reversalExternalId));assert.equal(balance(),18100);assert.equal(money.ensureCashAccount().frozen,1);});
it('a provider-reported refund alone freezes booked funds but cannot debit the wallet',async()=>{const id=await confirmed();await settle(id);project.state='cancelled';await assert.rejects(w.observePayment(owner,id));assert.equal(balance(),18100);assert.equal(db.all("SELECT * FROM mission_money_receipts WHERE kind='reversal'").length,0);assert.equal(money.ensureCashAccount().frozen,1);});
const contraProjectFailures:Record<string,(p:ContraProject)=>void>={
  'undisclosed intermediary':p=>{p.directEngagementVerified=false;},
  'unverified worker classification':p=>{p.workerClassificationVerified=false;},
  'unsigned agreement':p=>{p.agreementSignedByBoth=false;},
  'unsupported activity':p=>{p.activity='recruiting' as 'software_development';},
  'unfunded escrow':p=>{p.escrowFundedCents=0;},
  'partial escrow':p=>{p.escrowFundedCents=10000;},
  'advance released before real work':p=>{p.upfrontReleasedCents=1000;},
  'released before work':p=>{p.releasedGrossCents=20000;},
  'missing agreement identity':p=>{p.agreementId='';},
  'invalid signed agreement hash':p=>{p.agreementHash='not-a-hash';},
  'milestone contract':p=>{p.kind='milestones' as 'one_time_fixed_escrow';},
  'recurring invoice contract':p=>{p.kind='fixed_invoice' as 'one_time_fixed_escrow';},
};
for(const [label,mutate] of Object.entries(contraProjectFailures))it(`Contra rejects ${label}`,async()=>{await auth();mutate(project);await assert.rejects(w.assign(owner,project.projectId));assert.equal(db.all('SELECT * FROM mission_contra_work').length,0);noCash();});
it('a client-mode account cannot stand in for the contracting Independent',async()=>{authority.role='client' as 'independent';await assert.rejects(auth());noCash();});
it('one countersigned agreement cannot be assigned to two projects',async()=>{await assigned();project.projectId='second-project';await assert.rejects(w.assign(owner,project.projectId),/exclusive_project/);assert.equal(db.all('SELECT * FROM mission_contra_work').length,1);});
it('agreement identity and exact terms remain bound after assignment',async()=>{const row=await assigned(),id=String(row.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'synthetic-review');project.agreementHash=sha256('different terms');await assert.rejects(w.beginManualDelivery(owner,id),/project_changed/);});
it('delivery evidence for another agreement is not accepted',async()=>{const id=await prepared();delivery.agreementId='other';await assert.rejects(w.confirmDelivery(owner,id,delivery.submissionId));noCash();});
const acceptanceFailures:Record<string,(p:ContraProject)=>void>={
  'automatic timeout acceptance':p=>{p.clientAcceptance='automatic';},
  'still pending acceptance':p=>{p.clientAcceptance='pending';},
  'wrong delivered bytes accepted':p=>{p.acceptedDeliveryHash=sha256('different work');},
  'partial release':p=>{p.releasedGrossCents=10000;},
  'missing release ID':p=>{p.paymentId=null;},
  'a different release ID':p=>{p.paymentId='other';},
};
for(const [label,mutate] of Object.entries(acceptanceFailures))it(`Contra ${label} cannot enter mission cash`,async()=>{const id=await confirmed();mutate(project);await assert.rejects(settle(id));noCash();});
for(const field of ['agreementId','paymentId'] as const)it(`remittance must bind exact ${field}`,async()=>{const id=await confirmed();payout.lines[0][field]='other';await assert.rejects(settle(id));noCash();});
it('USDC payout is not USD settlement',async()=>{const id=await confirmed();receiving.currency='USDC';await assert.rejects(settle(id));noCash();});
it('converted receipt cannot bypass the no-FX lane by displaying USD',async()=>{const id=await confirmed();receiving.fxApplied=true;await assert.rejects(settle(id));noCash();});
it('changing acceptance while the bank lookup awaits blocks admission',async()=>{const id=await confirmed();beforeReceiving=()=>{project.clientAcceptance='automatic';};await assert.rejects(settle(id));noCash();});
it('changing signed terms while bank verification awaits blocks admission',async()=>{const id=await confirmed();beforeReceiving=()=>{project.agreementHash=sha256('amended agreement');};await assert.rejects(settle(id));noCash();});
it('payment identifiers cannot change between confirmation and observation',async()=>{const id=await confirmed();project.paymentId='another-release';await assert.rejects(w.observePayment(owner,id));noCash();});
it('real release and payout still do not admit funds without a bank movement',async()=>{const id=await confirmed();await w.observePayout(owner,id,payout.payoutId);receiving.state='pending';await assert.rejects(settle(id));noCash();assert.equal(db.get<Row>('SELECT state FROM mission_contra_payouts')!.state,'observed');});
it('booked payment uncertainty cannot silently overwrite its original release ID',async()=>{const id=await confirmed();await settle(id);project.paymentId='substitute';await assert.rejects(w.observePayment(owner,id));assert.equal(balance(),18100);assert.equal(db.get<Row>('SELECT payment_id FROM mission_contra_work WHERE id=?',[id])!.payment_id,'synthetic-payment');assert.equal(money.ensureCashAccount().frozen,1);});
