import {randomUUID} from 'node:crypto';
import path from 'node:path';import os from 'node:os';
process.env.ZA141251SA_DATABASE_URL=process.env.PG_TEST_DATABASE_URL||`file:${path.join(os.tmpdir(),`customer-work-${randomUUID()}.db`)}`;
process.env.ZA141251SA_SESSION_SECRET='synthetic-contra-tests-not-live-credentials';
import {before,beforeEach,after,it} from 'node:test';import assert from 'node:assert/strict';
import type {ContraAuthority,ContraProject,ContraDelivery,ContraRemittance,ContraReceivingProof,ContraReversal,ContraProvider,ContraUsdReceiver} from './contra-contracts';
const {ContraWorkflow}=require('./contra-workflow') as typeof import('./contra-workflow');
const {missionDb:db,applyMissionMigrations,sha256,verifyMissionAudit}=require('../database') as typeof import('../database');
const money=require('../money') as typeof import('../money');
const {updatePolicy,setKillSwitch}=require('../policy') as typeof import('../policy');
const owner={kind:'owner' as const,id:'contra-fixture-owner'}, agent='contra-fixture-agent', other='contra-fixture-other';
const keepAlive=setInterval(()=>{},1000);
let authority:ContraAuthority,project:ContraProject,delivery:ContraDelivery,payout:ContraRemittance,receiving:ContraReceivingProof,reversal:ContraReversal;
let source:ContraProvider,receiver:ContraUsdReceiver,w:InstanceType<typeof ContraWorkflow>,beforeReceiving:(()=>void|Promise<void>)|undefined;
const now=()=>new Date().toISOString();
const tables=['mission_customer_events','mission_customer_requests','mission_customer_suppressions','mission_fiverr_work','mission_fiverr_accounts','mission_upwork_work','mission_upwork_accounts','mission_contra_events','mission_contra_payouts','mission_contra_work','mission_contra_accounts','mission_earning_jobs','mission_money_receipts','mission_cash_liabilities','mission_cash_entries','mission_money_transfers','mission_money_operations','mission_money_grants','mission_money_opportunities','mission_cash_accounts'];
before(()=>{applyMissionMigrations();db.run("INSERT INTO mission_owner (id,email,password_hash,role,status) VALUES (?,'fixture-contra@example.test','fixture','owner','active')",[owner.id]);for(const id of [agent,other])db.run("INSERT INTO mission_agents (id,slug,name,role_key,depth,generation,status,mission_role,origin_platform) VALUES (?,?,'Synthetic fixture','specialist',0,'custom','active','worker','fixture')",[id,id]);});
beforeEach(()=>{
  setKillSwitch(false,owner.id);for(const t of tables)db.run(`DELETE FROM ${t}`);
  updatePolicy({currency:'USD',killSwitch:false,autonomousEnabled:true,maxDailySpendCents:100000,maxExpenseCents:10000,requireApprovalAboveCents:500},owner.id);
  for(const id of [agent,other])money.setMoneyGrant(owner,id,{spendLimitCents:0,delegationCents:0,canCreate:false,expiresAt:new Date(Date.now()+86400000).toISOString(),status:'active'});
  const identity={accountId:'synthetic-account'},proof={evidenceRef:'synthetic-proof-not-money',verifiedAt:now(),authenticityVerified:true};
  authority={...identity,...proof,missionOwnerId:owner.id,ownerControlVerified:true,role:'independent',accountType:'individual',identityVerified:true,eligible:true,workflow:'human_assisted',goodStanding:true,evidenceUseAuthorized:true,projectReadApproved:true,deliveryReadApproved:true,paymentReadApproved:true,durableRecordsApproved:true,permissionExpiresAt:new Date(Date.now()+86400000).toISOString()};
  project={...identity,...proof,projectId:'synthetic-project',agreementId:'synthetic-agreement',agreementHash:sha256('synthetic signed agreement'),directEngagementVerified:true,workerClassificationVerified:true,activity:'software_development',upfrontReleasedCents:0,releasedGrossCents:0,clientAcceptance:'pending',acceptedDeliveryHash:null,paymentId:null,clientId:'synthetic-client',scopeHash:sha256('synthetic scope'),kind:'one_time_fixed_escrow',currency:'USD',state:'active',independentClientVerified:true,agreementSignedByBoth:true,rightsCleared:true,fundsStatus:'held',suspended:false,disputed:false,aiAssistanceAllowed:true,clientDataUseAllowed:true,grossCents:20000,escrowFundedCents:20000,independentNetCents:0};
  delivery={...identity,...proof,projectId:project.projectId,agreementId:project.agreementId,clientId:project.clientId,submissionId:'synthetic-submission',submittedAt:now(),state:'submitted',content:'// Synthetic test artifact, not paid work\nexport const answer = 42;'};
  payout={...identity,...proof,payoutId:'synthetic-payout',state:'paid',complete:true,currency:'USD',payoutFeeCents:300,netCents:18200,lines:[{kind:'project_release',projectId:project.projectId,agreementId:project.agreementId,paymentId:'synthetic-payment',currency:'USD',grossCents:20000,feeCents:1500,netCents:18500}]};
  receiving={...identity,...proof,source:'contra',payoutId:payout.payoutId,rail:'synthetic-bank',receivingAccount:'synthetic-mission-account',externalId:'synthetic-credit',state:'settled',direction:'credit',currency:'USD',missionOwnershipVerified:true,grossCents:18200,feeCents:100,netCents:18100,availableBalanceCents:1000000,fxApplied:false};
  reversal={...identity,...proof,source:'contra',payoutId:payout.payoutId,rail:receiving.rail,receivingAccount:receiving.receivingAccount,originalExternalId:receiving.externalId,reversalExternalId:'synthetic-debit',state:'settled',direction:'debit',currency:'USD',missionOwnershipVerified:true,amountCents:18100};
  source={...identity,authority:async()=>structuredClone(authority),project:async()=>structuredClone(project),delivery:async()=>structuredClone(delivery),remittance:async()=>structuredClone(payout)};
  beforeReceiving=undefined;receiver={rail:receiving.rail,receivingAccount:receiving.receivingAccount,verify:async()=>{const snapshot=structuredClone(receiving);await beforeReceiving?.();return snapshot;},reversal:async()=>structuredClone(reversal)};
  w=new ContraWorkflow(source,receiver);
});
after(()=>{try{db.close();}finally{clearInterval(keepAlive);}});

const {CustomerWork}=require('./customer-work') as typeof import('./customer-work');
const {fulfillService,listingPack}=require('./service-offers') as typeof import('./service-offers');
import type {CustomerRequestInput} from './customer-work';
import {runInNewContext} from 'node:vm';
const commercial=new CustomerWork();
const input=():CustomerRequestInput=>({serviceId:'json-validation',origin:'direct',customerRef:project.clientId,sourceRef:'synthetic-explicit-request',observedAt:now(),reviewRef:'synthetic-owner-review',consentExpiresAt:new Date(Date.now()+3600000).toISOString(),brief:'Synthetic requirement for a reusable validation tool, not an actual customer',configuration:{required:['id','name'],uniqueKey:'id'},quoteCents:20000,explicitRequestReviewed:true,contactPermissionReviewed:true,lawfulPurposeReviewed:true,dataRightsReviewed:true,nonSensitiveDataOnly:true,automationPermissionReviewed:true});
const noCash=()=>{assert.equal(Number(money.ensureCashAccount().available_cents),0);assert.equal(db.all('SELECT * FROM mission_money_receipts').length,0);};
const record=()=>commercial.record(owner,input());
async function bound(){const d=record();project.scopeHash=String(d.scope_hash);await w.authorizeAccount(owner,{agentId:agent,reviewRef:'synthetic',expiresAt:new Date(Date.now()+3600000).toISOString()});const work=await w.assign(owner,project.projectId);commercial.bind(owner,String(d.id),'contra',String(work.id));return {id:String(d.id),workId:String(work.id)};}
async function produced(){const d=await bound();const out=commercial.produce({kind:'agent',id:agent},d.id,'[{"id":1,"name":"Example"},{"id":1,"name":""}]');commercial.approve(owner,d.id,out.artifactHash,'synthetic-quality-review');return {...d,out};}
async function delivered(){const d=await produced();delivery.content=d.out.artifact;const draft=w.draft(owner,d.workId,delivery.content);w.approve(owner,d.workId,String(draft.content_hash),'synthetic');await w.beginManualDelivery(owner,d.workId);delivery.submittedAt=now();await w.confirmDelivery(owner,d.workId,delivery.submissionId);return d;}
async function paid(){const d=await delivered();project.state='completed';project.fundsStatus='released';project.independentNetCents=18500;project.releasedGrossCents=20000;project.clientAcceptance='explicit';project.acceptedDeliveryHash=sha256(delivery.content);project.paymentId='synthetic-payment';await w.observePayment(owner,d.workId);return d;}
const settle=(id:string)=>w.reconcile(owner,id,payout.payoutId,receiving.externalId);
it('capability inventory and unpublished price packs never claim customers or earnings',()=>{const o=commercial.overview(owner);assert.equal(o.totalRecords,0);assert.equal(o.automaticOutreach,false);assert.equal(o.publishingEnabled,false);for(const offer of o.offers){const p=commercial.listing(owner,offer.id,20000);assert.equal(p.published,false);assert.equal(p.customersAcquired,false);assert.match(p.text,/not earnings/);}noCash();});
it('sample preview performs useful work without fabricating a customer or paid job',()=>{const out=commercial.preview(owner,'json-validation','[{"id":1},{"id":1}]',{required:['id'],uniqueKey:'id'},true,true);assert.equal(out.classification,'owner_supplied_sample_not_customer_work');assert.equal(JSON.parse(out.artifact).report.totalIssues,1);assert.equal(db.all('SELECT * FROM mission_customer_requests').length,0);noCash();});
it('delivered reusable validator reproduces the real local algorithm without embedded customer data',()=>{const out=fulfillService('json-validation','[{"id":1,"name":"private sample"},{"id":1,"name":""}]',{required:['id','name'],uniqueKey:'id'});const pack=JSON.parse(out.artifact);const validate=runInNewContext(pack.files['validator.mjs'].replace('export ','')+';validateRecords');const result=validate([{id:1,name:'private sample'},{id:1,name:''}],{required:['id','name'],uniqueKey:'id'});assert.equal(JSON.stringify(result),JSON.stringify(pack.report));assert.equal(out.artifact.includes('private sample'),false);assert.equal(pack.report.recordsChanged,0);assert.equal(out.artifactHash,sha256(out.artifact));});
it('HTML work is an offline limited source check, never a browser or certification claim',()=>{const out=fulfillService('html-release-check','<html><title> </title><h1>Hi</h1><img src="https://example.invalid/x"><script>throw new Error("DO NOT RUN")</script>',null);const r=JSON.parse(out.artifact);assert.equal(r.report.checks.nonemptyTitle,false);assert.equal(r.report.checks.imagesWithoutAlt,1);assert.equal(r.networkRequests,0);assert.match(r.report.limitations,/No browser/);});
it('JSON report handles absent fields, invalid and type-distinct IDs, formula warnings and nonfinite numbers',()=>{const out=fulfillService('json-validation','[{"id":1,"name":"=SUM(A1)"},{"id":"1"},{"id":null},{"id":1e309}]',{required:['id','name'],uniqueKey:'id'});const r=JSON.parse(out.artifact).report;assert.ok(r.issues.some((x:{code:string})=>x.code==='spreadsheet_formula_risk_review'));assert.ok(r.issues.some((x:{code:string})=>x.code==='non_finite_number'));assert.equal(r.issues.some((x:{code:string})=>x.code==='duplicate_key'),false);});
it('large issue sets are bounded and explicitly truncated',()=>{const r=JSON.parse(fulfillService('json-validation',JSON.stringify(Array.from({length:500},()=>({}))),{required:['id'],uniqueKey:'id'}).artifact).report;assert.equal(r.totalIssues,1000);assert.equal(r.issues.length,200);assert.equal(r.truncated,true);});
for(const spec of [null,{}, {required:[],uniqueKey:'id'},{required:['id','id'],uniqueKey:'id'},{required:['constructor'],uniqueKey:'constructor'},{required:['id'],uniqueKey:'other'},{required:['x;process.exit()'],uniqueKey:'x;process.exit()'}])it(`rejects invalid validator configuration ${JSON.stringify(spec)}`,()=>{assert.throws(()=>fulfillService('json-validation','[{}]',spec));noCash();});
for(const data of ['', 'invalid','{}','[]','[null]','[[]]', 'x'.repeat(131073)])it(`rejects unsupported input ${data.length} bytes`,()=>{assert.throws(()=>fulfillService('json-validation',data,{required:['id'],uniqueKey:'id'}));});
for(const price of [0,-1,1.5,NaN,1000001])it(`rejects invalid proposed price ${price}`,()=>{assert.throws(()=>listingPack('json-validation',price));noCash();});
for(const flag of ['explicitRequestReviewed','contactPermissionReviewed','lawfulPurposeReviewed','dataRightsReviewed','nonSensitiveDataOnly','automationPermissionReviewed'] as const)it(`requires owner review of ${flag}, never caller payment claims`,()=>{const i=input();i[flag]=false;assert.throws(()=>commercial.record(owner,i),/review_required/);assert.equal(db.all('SELECT * FROM mission_customer_requests').length,0);noCash();});
for(const field of ['sourceRef','customerRef','reviewRef','brief'] as const)it(`missing ${field} cannot become an inquiry`,()=>{const i=input();i[field]='';assert.throws(()=>commercial.record(owner,i));noCash();});
for(const date of ['invalid','2000-01-01',new Date(Date.now()+86400000).toISOString()])it(`invalid observation date ${date}`,()=>{assert.throws(()=>commercial.record(owner,{...input(),observedAt:date}));noCash();});
for(const date of ['invalid','2000-01-01',new Date(Date.now()+8*86400000).toISOString()])it(`invalid permission expiry ${date}`,()=>{assert.throws(()=>commercial.record(owner,{...input(),consentExpiresAt:date}));noCash();});
it('all customer-management and sample actions are private owner actions',()=>{const a={kind:'agent' as const,id:agent};for(const f of [()=>commercial.record(a,input()),()=>commercial.listing(a,'json-validation',100),()=>commercial.overview(a),()=>commercial.preview(a,'html-release-check','<title>x</title>',null,true,true),()=>commercial.response(a,'id'),()=>commercial.bind(a,'id','contra','w'),()=>commercial.stop(a,'id','ref'),()=>commercial.approve(a,'id','hash','ref')])assert.throws(f,/owner_required/);});
it('duplicate demand references cannot inflate customer counts',()=>{record();assert.throws(()=>record(),/duplicate_request/);assert.equal(commercial.overview(owner).totalRecords,1);noCash();});
it('manual reply is tied to an explicit request and never sent',()=>{const d=record();const r=commercial.response(owner,String(d.id));assert.equal(r.sent,false);assert.match(r.content,/Your requested brief/);assert.equal(commercial.detail(owner,String(d.id)).request.response,r.content);assert.throws(()=>commercial.response(owner,String(d.id)),/already_prepared/);noCash();});
it('opt-out persists across new requests and restarts; no unsubscribe bypass',()=>{const d=record();commercial.stop(owner,String(d.id),'synthetic-opt-out');assert.throws(()=>commercial.response(owner,String(d.id)));assert.throws(()=>new CustomerWork().record(owner,{...input(),sourceRef:'other'}),/suppressed/);noCash();});
it('expired contact permission blocks responses and contract binding',async()=>{const d=await bound();db.run('UPDATE mission_customer_requests SET consent_expires_at=? WHERE id=?',['2000-01-01',d.id]);assert.throws(()=>commercial.produce(owner,d.id,'[{}]'),/expired/);noCash();});
it('kill switch stops acquisition and local work without creating transactions',()=>{setKillSwitch(true,owner.id);assert.throws(()=>record(),/policy_blocked/);assert.throws(()=>commercial.listing(owner,'json-validation',100),/policy_blocked/);assert.throws(()=>commercial.preview(owner,'html-release-check','<title>x</title>',null,true,true),/policy_blocked/);noCash();});
for(const route of ['fiverr','upwork'])it(`direct-origin clients are not silently moved to ${route}`,()=>{const d=record();assert.throws(()=>commercial.bind(owner,String(d.id),route,'missing'),/diversion/);noCash();});
for(const origin of ['fiverr','upwork','contra'] as const)it(`platform-origin ${origin} customers cannot be diverted to another platform`,()=>{const d=commercial.record(owner,{...input(),origin});assert.throws(()=>commercial.bind(owner,String(d.id),origin==='contra'?'fiverr':'contra','missing'),/diversion/);noCash();});
it('an unverified inquiry is never allowed to execute customer work',()=>{const d=record();assert.throws(()=>commercial.produce(owner,String(d.id),'[{}]'));assert.equal(commercial.progress(owner,String(d.id)).stage,'owner_recorded_inquiry');noCash();});
it('missing provider work cannot be replaced by owner claims of a paid order',()=>{const d=record();assert.throws(()=>commercial.bind(owner,String(d.id),'contra','invented'),/missing/);noCash();});
for(const field of ['client_id','scope_hash','gross_cents'] as const)it(`contract must bind actual ${field}`,async()=>{const d=await bound();db.run(`UPDATE mission_contra_work SET ${field}=? WHERE id=?`,[field==='gross_cents'?1:'other',d.workId]);assert.throws(()=>commercial.produce(owner,d.id,'[{}]'),/mismatch/);noCash();});
it('account authority and assigned grant are required for local agent execution',async()=>{const d=await bound();assert.throws(()=>commercial.produce({kind:'agent',id:other},d.id,'[{}]'),/assigned_agent/);db.run("UPDATE mission_money_grants SET status='revoked' WHERE agent_id=?",[agent]);assert.throws(()=>commercial.produce({kind:'agent',id:agent},d.id,'[{}]'),/authority_inactive/);noCash();});
it('disabled autonomy blocks agent execution, without preventing owner-controlled work',async()=>{const d=await bound();updatePolicy({autonomousEnabled:false},owner.id);assert.throws(()=>commercial.produce({kind:'agent',id:agent},d.id,'[{}]'));commercial.produce(owner,d.id,'[{}]');noCash();});
it('revoked provider account blocks new work',async()=>{const d=await bound();w.revokeAccount(owner);assert.throws(()=>commercial.produce(owner,d.id,'[{}]'),/not_authorized/);noCash();});
it('a completed binding cannot be repointed to a different contract',async()=>{const d=await bound();assert.throws(()=>commercial.bind(owner,d.id,'contra','other'),/immutable/);noCash();});
it('same contract cannot be attributed to two inquiries',async()=>{const d=await bound();const another=commercial.record(owner,{...input(),sourceRef:'request2'});assert.throws(()=>commercial.bind(owner,String(another.id),'contra',d.workId),/exclusive/);noCash();});
it('human approval binds immutable output; cannot regenerate or approve different bytes',async()=>{const d=await bound();const out=commercial.produce(owner,d.id,'[{}]');assert.throws(()=>commercial.approve(owner,d.id,sha256('wrong'),'review'),/mismatch/);commercial.approve(owner,d.id,out.artifactHash,'review');assert.throws(()=>commercial.produce(owner,d.id,'[{"id":2}]'));noCash();});
it('local output and provider payment alone never become real mission cash',async()=>{const d=await paid();await w.observePayout(owner,d.workId,payout.payoutId);assert.equal(commercial.progress(owner,d.id).stage,'provider_payment_confirmed_not_cash');assert.equal(commercial.progress(owner,d.id).receivedNetUsdCents,0);noCash();});
it('customer → actual validator work → provider payment → independent USD → wallet, without a second credit',async()=>{const d=await paid();await settle(d.workId);const progress=commercial.progress(owner,d.id);assert.equal(progress.receivedNetUsdCents,18100);assert.equal(progress.stage,'verified_usd_received');assert.equal(progress.cashCreditedByThisModule,false);assert.equal(Number(money.ensureCashAccount().available_cents),18100);commercial.progress(owner,d.id);new CustomerWork().overview(owner);assert.equal(Number(money.ensureCashAccount().available_cents),18100);assert.equal(verifyMissionAudit().ok,true);});
it('pending bank movement cannot convert a quoted price to earnings',async()=>{const d=await paid();receiving.state='pending';await assert.rejects(settle(d.workId));assert.equal(commercial.progress(owner,d.id).receivedNetUsdCents,0);noCash();});
it('opt-out blocks further work but does not erase legitimately received cash history',async()=>{const d=await paid();await settle(d.workId);commercial.stop(owner,d.id,'opt-out');const p=commercial.progress(owner,d.id);assert.equal(p.contactStopped,true);assert.equal(p.receivedNetUsdCents,18100);assert.throws(()=>commercial.produce(owner,d.id,'[{}]'));});
it('settlement uncertainty is not displayed as currently verified earnings',async()=>{const d=await paid();await settle(d.workId);project.state='cancelled';await assert.rejects(w.observePayment(owner,d.workId));const p=commercial.progress(owner,d.id);assert.equal(p.reviewRequired,true);assert.equal(p.receivedNetUsdCents,0);assert.equal(p.historicalReceivedNetUsdCents,18100);});
it('partial and full verified reversals reduce attributed net receipts',async()=>{const d=await paid();await settle(d.workId);reversal.amountCents=10000;await w.reconcileReversal(owner,d.workId,reversal.reversalExternalId);assert.equal(commercial.progress(owner,d.id).receivedNetUsdCents,0);assert.equal(commercial.progress(owner,d.id).historicalReceivedNetUsdCents,8100);reversal.amountCents=8100;reversal.reversalExternalId='synthetic-second-debit';await w.reconcileReversal(owner,d.workId,reversal.reversalExternalId);assert.equal(commercial.progress(owner,d.id).historicalReceivedNetUsdCents,0);});
it('delivered artifact cannot be substituted while attributing a real receipt',async()=>{const d=await paid();await settle(d.workId);db.run('UPDATE mission_customer_requests SET artifact_hash=? WHERE id=?',[sha256('other'),d.id]);assert.equal(commercial.progress(owner,d.id).receivedNetUsdCents,0);});
it('receipt-shaped local metadata without a completed money job/ledger is never earnings',async()=>{const d=await paid();await w.observePayout(owner,d.workId,payout.payoutId);db.run("UPDATE mission_contra_payouts SET state='booked',receipt_id='fake',net_cents=18100");db.run("INSERT INTO mission_money_receipts (provider,external_id,fingerprint,kind,amount_cents,agent_id,created_at) VALUES ('contra-settlement','fake','synthetic','earning',18100,?,?)",[agent,now()]);assert.equal(commercial.progress(owner,d.id).receivedNetUsdCents,0);assert.equal(Number(money.ensureCashAccount().available_cents),0);});
it('cross-category inventory describes acquisition, value and real payment, never verified leads',()=>{const catalog=commercial.overview(owner).channelInventory;assert.equal(catalog.length,10);for(const row of catalog){assert.equal(row.missionEligibilityVerified,false);assert.equal(row.automaticAcquisition,false);assert.equal(row.status,'conditional_channel_not_a_verified_lead');for(const field of ['customerOrigin','value','paymentGeneration','settlement','human','automation'] as const)assert.ok(row[field].length>20);assert.ok(row.evidence.every(x=>x.startsWith('https://')));}noCash();});
for(const c of ['fiverr','upwork'] as const)it(`same-origin ${c} requests bind only the corresponding authenticated buyer/account/work scope`,()=>{
 const d=commercial.record(owner,{...input(),origin:c}),expiry=new Date(Date.now()+3600000).toISOString();
 if(c==='fiverr'){
  db.run("INSERT INTO mission_fiverr_accounts (account_id,agent_id,state,expires_at,review_ref,approved_by,authority_hash) VALUES ('fixture-fiverr-account',?,'authorized',?,'synthetic',?,'synthetic')",[agent,expiry,owner.id]);
 }else db.run("INSERT INTO mission_upwork_accounts (account_id,tenant_id,agent_id,state,expires_at,review_ref,approved_by,authority_hash) VALUES ('fixture-upwork-account','synthetic-tenant',?,'authorized',?,'synthetic',?,'synthetic')",[agent,expiry,owner.id]);
 const op=money.approveOpportunity(owner,{title:'Synthetic normalized connector record',evidenceUrl:'https://example.test/synthetic',activity:'software_development',provider:`${c}-settlement`});
 if(c==='fiverr')db.run("INSERT INTO mission_fiverr_work (id,account_id,order_id,buyer_id,scope_hash,gross_cents,opportunity_id,state) VALUES ('synthetic-fiverr-work','fixture-fiverr-account','synthetic-order',?,?,20000,?,'authorized')",[d.customer_ref,d.scope_hash,op.id]);
 else db.run("INSERT INTO mission_upwork_work (id,account_id,tenant_id,contract_id,milestone_id,client_id,scope_hash,gross_cents,opportunity_id,state) VALUES ('synthetic-upwork-work','fixture-upwork-account','synthetic-tenant','synthetic-contract','synthetic-milestone',?,?,20000,?,'authorized')",[d.customer_ref,d.scope_hash,op.id]);
 commercial.bind(owner,String(d.id),c,`synthetic-${c}-work`);assert.equal(commercial.progress(owner,String(d.id)).stage,'connector_backed_contract');commercial.produce({kind:'agent',id:agent},String(d.id),'[{"id":1,"name":"Example"}]');noCash();
});
for(const type of ['account_expired','agent_frozen','treasury_frozen','consent_stopped'])it(`new client work fails closed for ${type}`,async()=>{const d=await bound();if(type==='account_expired')db.run("UPDATE mission_contra_accounts SET expires_at='2000-01-01'");if(type==='agent_frozen')money.freezeCash(owner,agent,true);if(type==='treasury_frozen'){money.ensureCashAccount();money.freezeCash(owner,'treasury',true);}if(type==='consent_stopped')commercial.stop(owner,d.id,'synthetic-opt-out');assert.throws(()=>commercial.produce(owner,d.id,'[{}]'));noCash();});
it('no arbitrary connector/table name or unsupported service can activate work',()=>{const d=record();for(const c of ['__proto__','contra;DELETE FROM mission_agents','toptal','unknown'])assert.throws(()=>commercial.bind(owner,String(d.id),c,'id'),/unsupported/);assert.throws(()=>commercial.listing(owner,'fake-customer-generation',100));noCash();});
it('corrupt delivered content or cash ledger cannot be reported as a verified conversion',async()=>{const d=await paid();await settle(d.workId);db.run('UPDATE mission_customer_requests SET artifact=? WHERE id=?',['other',d.id]);assert.equal(commercial.progress(owner,d.id).receivedNetUsdCents,0);db.run('UPDATE mission_customer_requests SET artifact=? WHERE id=?',[d.out.artifact,d.id]);db.run("UPDATE mission_cash_accounts SET available_cents=1 WHERE id='treasury'");assert.equal(commercial.progress(owner,d.id).receivedNetUsdCents,0);});

it('input corrections before human approval create a new artifact hash and preserve review history',async()=>{const d=await bound();const first=commercial.produce(owner,d.id,'[{}]'),second=commercial.produce(owner,d.id,'[{"id":1,"name":"Example"}]');assert.notEqual(first.artifactHash,second.artifactHash);assert.throws(()=>commercial.approve(owner,d.id,first.artifactHash,'stale review'),/mismatch/);commercial.approve(owner,d.id,second.artifactHash,'current review');assert.equal(db.all("SELECT id FROM mission_customer_events WHERE request_id=? AND stage='work_produced'",[d.id]).length,2);noCash();});

it('direct inquiries exist before platform onboarding; only an explicit identity review can bind the eventual client',async()=>{const d=commercial.record(owner,{...input(),customerRef:'synthetic-consented-contact'});project.scopeHash=String(d.scope_hash);await w.authorizeAccount(owner,{agentId:agent,reviewRef:'synthetic',expiresAt:new Date(Date.now()+3600000).toISOString()});const work=await w.assign(owner,project.projectId);assert.throws(()=>commercial.bind(owner,String(d.id),'contra',String(work.id)),/invalid_text/);commercial.bind(owner,String(d.id),'contra',String(work.id),'synthetic-contact-to-contract-identity-review');const detail=commercial.detail(owner,String(d.id));assert.equal(detail.request.customer_ref,'synthetic-consented-contact');assert.equal(detail.request.bound_client_ref,project.clientId);assert.equal(detail.progress.inquiryAuthenticity,'owner_declared_not_independently_verified');commercial.stop(owner,String(d.id),'synthetic-opt-out');assert.throws(()=>commercial.record(owner,{...input(),customerRef:'synthetic-consented-contact',sourceRef:'another-request'}),/suppressed/);noCash();});
