/** Reviewed commercial mechanisms, NOT acquired customers or verified open jobs.
 * Public program evidence is not mission account eligibility or automation permission.
 * Review: 2026-09-20. No catalog record is executable demand or a cash opportunity.
 */
export const CUSTOMER_CHANNELS = [
 {id:'marketplace-services',priority:1,category:'Freelancing / client services',customerOrigin:'Buyers search Fiverr Gigs or Upwork Project Catalog; actual inbound requests',value:'Bounded software deliverables, validation tools, release checks and bug fixes',paymentGeneration:'Buyer accepts and purchases a genuine scoped order or funded contract',settlement:'Originating platform → existing verified connector → independently received net USD → mission treasury',human:'Authentic eligible seller; owner reviews listing, scope, skills, price and delivery',automation:'Local permitted assistance only; human publishing, negotiation and platform actions; no unsolicited bulk proposals',evidence:['https://support.upwork.com/hc/en-us/articles/10408677826963-What-is-Project-Catalog-on-Upwork','https://help.fiverr.com/hc/en-us/articles/34998793899665-Using-AI-on-Fiverr-Guidelines-for-freelancers-and-clients']},
 {id:'consented-referrals',priority:1,category:'Direct-client services',customerOrigin:'A genuine customer-initiated inquiry or an introduction with recipient permission; none supplied yet',value:'Useful fixed-scope work solving the customer’s documented problem',paymentGeneration:'Real independently acquired client signs and pays a USD agreement',settlement:'Eligible direct client may use existing Contra chain; no off-platform diversion of marketplace customers',human:'Owner verifies introduction, contact permission, identity, data rights and actual agreement',automation:'Prepare one reply locally; manual approved contact only; suppression and expiry apply',evidence:['https://help.contra.com/en/articles/9322763-paid-projects']},
 {id:'agency-services',priority:2,category:'Agency / SEO / marketing / design / automation',customerOrigin:'Explicit requests, opted-in referrals or genuine existing clients requesting new work',value:'Authorized audits, original designs, analytics and workflow implementation; no ranking guarantees',paymentGeneration:'Client buys an agreed deliverable or genuine ongoing service',settlement:'Eligible platform/processor payment and independent USD receipt; broader service types need fulfillment support',human:'Competent accountable owner, scoped access rights and work-specific approval',automation:'Only contract-permitted assistance; no fake reviews, scraping, mass outreach or unauthorized client-system changes',evidence:['https://help.fiverr.com/hc/en-us/articles/34998793899665-Using-AI-on-Fiverr-Guidelines-for-freelancers-and-clients']},
 {id:'research-data',priority:2,category:'Research / data services',customerOrigin:'Clients seeking analysis of their own or lawfully licensed information',value:'Reproducible validation, source-backed findings and useful analysis; no invented results',paymentGeneration:'Client accepts a priced deliverable, not an unsolicited report',settlement:'A genuine service payment through an eligible route, then independently verified USD',human:'Owner reviews lawful purpose, dataset rights, confidentiality, competence and conclusions',automation:'Bounded offline processing of authorized data; no harvesting personal information',evidence:['https://support.upwork.com/hc/en-us/articles/10408677826963-What-is-Project-Catalog-on-Upwork']},
 {id:'remote-work',priority:3,category:'Remote paid work',customerOrigin:'Authentic employer vacancies; Toptal matching only after genuine talent admission',value:'Actual skilled human work with contract-permitted agent assistance',paymentGeneration:'Employer/client pays accepted work or genuine human billable time',settlement:'Approved payroll/talent payout → independently verified USD; Toptal lane already exists',human:'Real applicant, qualifications, interviews, country/work eligibility and tax compliance',automation:'No impersonation, automated interviews or converting agent runtime into human hours',evidence:['https://www.toptal.com/freelance-jobs/faq']},
 {id:'digital-products',priority:3,category:'Digital products',customerOrigin:'Owner-built audience/referrals; Gumroad Discover only after its actual-sales and review requirements',value:'Original reusable tools, templates or educational material, not copied inventory',paymentGeneration:'An independent buyer purchases a useful product',settlement:'Eligible merchant payout with actual deductions; USD price does not prove USD receipt',human:'Authentic merchant, IP clearance, support/refunds, tax and country eligibility',automation:'Product preparation subject to rights; manual listing unless approved API permission exists; no self-purchases',evidence:['https://gumroad.com/help/article/79-gumroad-discover','https://gumroad.com/help/article/13-getting-paid']},
 {id:'commerce',priority:3,category:'E-commerce / made-to-order digital goods',customerOrigin:'Genuine marketplace search or owner-approved storefront traffic',value:'Original seller-designed downloads or commissioned digital files',paymentGeneration:'Buyer places a real order and receives the promised goods',settlement:'Actual platform payout after fees/refunds, then independently verified USD',human:'Eligible shop, lawful payout destination, ownership, fulfillment and customer support',automation:'No counterfeit listings or fake reviews; no inventory purchases or ads authorized here',evidence:['https://help.etsy.com/hc/en-us/articles/115015628347-How-to-Manage-Your-Digital-Listings']},
 {id:'tutoring-consulting',priority:4,category:'Tutoring / consulting',customerOrigin:'Students selecting authentic tutors or clients requesting qualified advice',value:'Actual human teaching or consultation; agents may prepare authorized materials',paymentGeneration:'Genuine paid completed sessions; Preply first trial lesson yields no tutor earnings',settlement:'Eligible provider withdrawal and independently verified USD; not merely a lesson balance',human:'Real qualified tutor/consultant, appropriate safeguarding and platform admission',automation:'No agent pretending to be the human tutor, fake credentials or automatic session attendance',evidence:['https://help.preply.com/en/articles/4171348-when-and-how-you-get-paid-for-lessons']},
 {id:'affiliate',priority:4,category:'Affiliate commissions',customerOrigin:'A real audience uses useful original content and purchases from a merchant',value:'Truthful disclosed recommendations relevant to that audience',paymentGeneration:'Merchant validates an attributable legitimate conversion',settlement:'Approved commission payout through existing Awin controls → independent USD receipt',human:'Approved publishing property, advertiser program, ownership, disclosures and eligible receiver',automation:'Program-authorized publishing only; no fake traffic or self-conversions; owner has no approved property',evidence:['https://www.awin.com/gb/publishers/content-creator-influencer']},
 {id:'content',priority:4,category:'Content monetization',customerOrigin:'People genuinely discover and value original videos/articles; real sponsors or subscribers',value:'Original useful content and audience value, not engagement farming',paymentGeneration:'Approved ad revenue, genuine sponsorship or subscription payment',settlement:'Actual eligible payout, independently verified USD; no ad estimates counted',human:'Owned publishing channel, rights, monetization review and payment eligibility',automation:'Originality and platform-specific rules; no fake engagement or mass-produced low-value content',evidence:['https://support.google.com/youtube/answer/72851?hl=en']},
].map(channel=>Object.freeze({...channel,status:'conditional_channel_not_a_verified_lead',missionEligibilityVerified:false,automaticAcquisition:false}));
