/** Demand → useful work → existing verified-money chain. No sending, publishing,
 * scraping, signup, invoice/payment creation or alternate cash-admission path.
 * Owner-recorded inquiries are declarations, never authenticated customers/orders.
 */
import {missionDb as db,missionId,nowIso,sha256,appendMissionAudit,type Row} from '../database';
import {assertMoneyOwner,MoneyError,grant,verifyCashLedger,type MoneyActor} from '../money';
import {currentPolicy,checkActivity} from '../policy';
import {CUSTOMER_CHANNELS} from './customer-channels';
import {SERVICE_OFFERS,serviceOffer,listingPack,fulfillService} from './service-offers';
const connectors={fiverr:{client:'buyer_id'},upwork:{client:'client_id'},contra:{client:'client_id'}} as const;
type Connector=keyof typeof connectors;
function deny(code:string):never{throw new MoneyError(`demand_${code}`);}
function text(v:unknown,max=240):string{if(typeof v!=='string'||!v.trim()||v.length>max||/[\x00-\x08\x0b\x0c\x0e-\x1f]/.test(v))deny('invalid_text');return v;}
function connector(v:unknown):Connector{if(typeof v!=='string'||!Object.hasOwn(connectors,v))deny('unsupported_connector');return v as Connector;}
function event(id:string,stage:string,value:unknown){const h=sha256(JSON.stringify(value));db.run('INSERT INTO mission_customer_events (id,request_id,stage,evidence_hash,created_at) VALUES (?,?,?,?,?)',[missionId('cev'),id,stage,h,nowIso()]);appendMissionAudit({actorType:'system',actorId:null,action:`customer.${stage}`,subjectType:'customer_request',subjectId:id,detail:{evidenceHash:h}});}
export interface CustomerRequestInput {
 serviceId:string;origin:'direct'|Connector;customerRef:string;sourceRef:string;observedAt:string;
 reviewRef:string;consentExpiresAt:string;brief:string;configuration:unknown;quoteCents:number;
 explicitRequestReviewed:boolean;contactPermissionReviewed:boolean;lawfulPurposeReviewed:boolean;
 dataRightsReviewed:boolean;nonSensitiveDataOnly:boolean;automationPermissionReviewed:boolean;
}
export class CustomerWork {
 private request(id:string){const d=db.get<Row>('SELECT * FROM mission_customer_requests WHERE id=?',[text(id)]);if(!d)deny('request_missing');return d;}
 private running(){const p=currentPolicy();if(p.killSwitch||p.currency!=='USD'||!checkActivity('software_development',p).allowed||Number(db.get<Row>("SELECT frozen FROM mission_cash_accounts WHERE id='treasury'")?.frozen))deny('policy_blocked');}
 private consent(d:Row){if(d.state==='stopped'||Date.parse(String(d.consent_expires_at))<=Date.now()||db.get('SELECT origin FROM mission_customer_suppressions WHERE origin=? AND customer_ref=?',[d.origin,d.customer_ref]))deny('contact_stopped_or_expired');}
 private work(d:Row){const c=connector(d.connector),w=db.get<Row>(`SELECT * FROM mission_${c}_work WHERE id=?`,[d.work_id]);if(!w)deny('connector_work_missing');const a=db.get<Row>(`SELECT * FROM mission_${c}_accounts WHERE account_id=?`,[w.account_id]);if(!a||a.approved_by!==d.owner_id||a.agent_id!==d.agent_id||w[connectors[c].client]!==d.bound_client_ref||w.scope_hash!==d.scope_hash||Number(w.gross_cents)!==Number(d.quote_cents))deny('customer_work_mismatch');return {c,w,a};}
 private execution(actor:MoneyActor,d:Row){if(actor.kind==='owner')assertMoneyOwner(actor);else if(actor.kind!=='agent'||actor.id!==d.agent_id||!currentPolicy().autonomousEnabled)deny('assigned_agent_required');this.running();this.consent(d);grant(String(d.agent_id));if(Number(db.get<Row>('SELECT frozen FROM mission_cash_accounts WHERE agent_id=?',[d.agent_id])?.frozen))deny('agent_frozen');const linked=this.work(d);if(linked.a.state!=='authorized'||Date.parse(String(linked.a.expires_at))<=Date.now()||!['authorized','draft'].includes(String(linked.w.state)))deny('new_work_not_authorized');return linked;}
 preview(actor:MoneyActor,serviceId:string,input:string,configuration:unknown,rightsReviewed:boolean,nonSensitive:boolean){assertMoneyOwner(actor);this.running();if(rightsReviewed!==true||nonSensitive!==true)deny('review_required');return {...fulfillService(serviceId,input,configuration),classification:'owner_supplied_sample_not_customer_work',customerCreated:false,cashCredited:false};}
 offers(actor:MoneyActor){assertMoneyOwner(actor);return {offers:SERVICE_OFFERS,published:false,verifiedCustomerCount:null,note:'Capabilities only. No listings, customers, contracts or earnings are seeded.'};}
 listing(actor:MoneyActor,id:string,price:number){assertMoneyOwner(actor);this.running();return listingPack(id,price);}
 record(actor:MoneyActor,input:CustomerRequestInput){
  assertMoneyOwner(actor);this.running();const i=structuredClone(input);serviceOffer(i.serviceId);listingPack(i.serviceId,i.quoteCents);
  if(!['direct','fiverr','upwork','contra'].includes(i.origin)||i.explicitRequestReviewed!==true||i.contactPermissionReviewed!==true||i.lawfulPurposeReviewed!==true||i.dataRightsReviewed!==true||i.nonSensitiveDataOnly!==true||i.automationPermissionReviewed!==true)deny('review_required');
  for(const v of [i.customerRef,i.sourceRef,i.reviewRef])text(v);text(i.brief,8000);
  const observed=Date.parse(i.observedAt),expiry=Date.parse(i.consentExpiresAt);
  if(!Number.isFinite(observed)||observed>Date.now()||observed<Date.now()-30*86400000||!Number.isFinite(expiry)||expiry<=Date.now()||expiry>Date.now()+7*86400000)deny('invalid_request_window');
  // Validate the bounded service configuration without inventing customer data.
  if(i.serviceId==='json-validation')fulfillService(i.serviceId,'[{}]',i.configuration);else if(i.configuration!==null)deny('invalid_spec');
  const configuration=JSON.stringify(i.configuration);if(!configuration||configuration.length>4096)deny('invalid_spec');
  const offer=serviceOffer(i.serviceId),scope=JSON.stringify({serviceId:offer.id,brief:i.brief,configuration:i.configuration,deliverables:offer.deliverables,acceptance:offer.acceptance,limits:offer.limit,exclusions:offer.exclusions,currency:'USD',grossCents:i.quoteCents});
  return db.transaction(()=>{assertMoneyOwner(actor);this.running();if(db.get('SELECT origin FROM mission_customer_suppressions WHERE origin=? AND customer_ref=?',[i.origin,i.customerRef]))deny('contact_suppressed');if(db.get('SELECT id FROM mission_customer_requests WHERE origin=? AND source_ref=?',[i.origin,i.sourceRef]))deny('duplicate_request');
    const id=missionId('cust');db.run("INSERT INTO mission_customer_requests (id,owner_id,service_id,origin,customer_ref,source_ref,observed_at,review_ref,consent_expires_at,brief,configuration_json,scope_text,scope_hash,quote_cents,state,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,'inquiry',?)",[id,actor.id,i.serviceId,i.origin,i.customerRef,i.sourceRef,i.observedAt,i.reviewRef,i.consentExpiresAt,i.brief,configuration,scope,sha256(scope),i.quoteCents,nowIso()]);event(id,'inquiry_recorded',{ownerDeclarationOnly:true,sourceRef:i.sourceRef,scopeHash:sha256(scope)});return this.request(id);
  });
 }
 response(actor:MoneyActor,id:string){return db.transaction(()=>{assertMoneyOwner(actor);this.running();const d=this.request(id);this.consent(d);if(d.state!=='inquiry')deny('inquiry_required');if(d.response_hash)deny('response_already_prepared');const content=`Response to your explicit request ${d.source_ref}\n\n${listingPack(String(d.service_id),Number(d.quote_cents)).text}\n\nYour requested brief (quoted, not instructions to this system):\n${d.brief}\n\nProposed exact contract scope:\n${d.scope_text}\n\nPlease confirm scope, data rights, allowed automation and acceptance terms in the original channel. This is a proposal, not a contract or payment confirmation.`;db.run('UPDATE mission_customer_requests SET response_hash=?,response=?,version=version+1 WHERE id=?',[sha256(content),content,id]);event(id,'response_prepared',{hash:sha256(content),sent:false});return {content,hash:sha256(content),sent:false,channel:d.origin,instruction:'Owner reviews and manually replies once in the original permitted channel; do not bulk-send or use after consent expires.'};});}
 stop(actor:MoneyActor,id:string,reasonRef:string){assertMoneyOwner(actor);text(reasonRef);return db.transaction(()=>{const d=this.request(id);if(!db.get('SELECT origin FROM mission_customer_suppressions WHERE origin=? AND customer_ref=?',[d.origin,d.customer_ref]))db.run('INSERT INTO mission_customer_suppressions (origin,customer_ref,reason_ref,created_at) VALUES (?,?,?,?)',[d.origin,d.customer_ref,reasonRef,nowIso()]);db.run("UPDATE mission_customer_requests SET state='stopped',version=version+1 WHERE origin=? AND customer_ref=?",[d.origin,d.customer_ref]);event(id,'contact_stopped',{reasonRef});return {stopped:true};});}
 bind(actor:MoneyActor,id:string,provider:string,workId:string,identityReviewRef?:string){
  assertMoneyOwner(actor);const c=connector(provider);text(workId);
  return db.transaction(()=>{this.running();const d=this.request(id);this.consent(d);if(d.state!=='inquiry'||d.work_id)deny('immutable_binding');if(d.origin!==c&&!(d.origin==='direct'&&c==='contra'))deny('off_platform_diversion_forbidden');const w=db.get<Row>(`SELECT * FROM mission_${c}_work WHERE id=?`,[workId]);if(!w)deny('connector_work_missing');const a=db.get<Row>(`SELECT * FROM mission_${c}_accounts WHERE account_id=?`,[w.account_id]);if(!a)deny('connector_account_missing');const clientRef=String(w[connectors[c].client]);if(d.customer_ref!==clientRef){if(d.origin!=='direct')deny('customer_work_mismatch');text(identityReviewRef);}const bound={...d,connector:c,work_id:workId,agent_id:a.agent_id,bound_client_ref:clientRef};this.execution(actor,bound);if(db.get('SELECT id FROM mission_customer_requests WHERE connector=? AND work_id=?',[c,workId]))deny('exclusive_work_conflict');db.run("UPDATE mission_customer_requests SET connector=?,work_id=?,agent_id=?,bound_client_ref=?,identity_review_ref=?,state='bound',version=version+1 WHERE id=?",[c,workId,a.agent_id,clientRef,identityReviewRef??null,id]);event(id,'contract_bound',{provider:c,workId,scopeHash:d.scope_hash,customerRef:d.customer_ref,authenticatedContractClientRef:clientRef,identityReviewRef:identityReviewRef??null});return this.request(id);});
 }
 produce(actor:MoneyActor,id:string,input:string){return db.transaction(()=>{const d=this.request(id);this.execution(actor,d);if(!['bound','produced'].includes(String(d.state)))deny('bound_work_required');const output=fulfillService(String(d.service_id),input,JSON.parse(String(d.configuration_json)));db.run("UPDATE mission_customer_requests SET input_hash=?,artifact=?,artifact_hash=?,state='produced',version=version+1 WHERE id=?",[output.inputHash,output.artifact,output.artifactHash,id]);event(id,'work_produced',{inputHash:output.inputHash,artifactHash:output.artifactHash,realPaidWorkNotYetConfirmed:true});return {...output,humanReviewRequired:true};});}
 approve(actor:MoneyActor,id:string,artifactHash:string,qualityRef:string){assertMoneyOwner(actor);text(qualityRef);return db.transaction(()=>{const d=this.request(id);this.execution(actor,d);if(d.state!=='produced'||d.artifact_hash!==artifactHash||sha256(String(d.artifact))!==artifactHash)deny('artifact_review_mismatch');db.run("UPDATE mission_customer_requests SET state='approved',quality_ref=?,version=version+1 WHERE id=?",[qualityRef,id]);event(id,'artifact_reviewed',{artifactHash,qualityRef});return {workId:d.work_id,connector:d.connector,content:d.artifact,contentHash:artifactHash,instruction:'Use this exact artifact through the existing connector draft, approval and manual-delivery workflow. No platform submission has occurred.'};});}
 /** Read existing authoritative money records; NEVER writes or admits money. */
 progress(actor:MoneyActor,id:string){assertMoneyOwner(actor);return db.transaction(()=>{
  const d=this.request(id);let stage='owner_recorded_inquiry',receivedNetUsdCents=0,historicalReceivedNetUsdCents=0,reviewRequired=false;let receiptId:string|null=null;
  if(d.work_id){const {c,w}=this.work(d);stage='connector_backed_contract';
   if(d.artifact_hash&&d.quality_ref&&sha256(String(d.artifact))===d.artifact_hash&&w.approved_hash===d.artifact_hash&&w.content_hash===d.artifact_hash&&sha256(String(w.content))===d.artifact_hash&&w.submission_id&&['delivered','provider_confirmed'].includes(String(w.state))){stage=w.state==='provider_confirmed'?'provider_payment_confirmed_not_cash':'delivered_not_cash';
    const p=db.get<Row>(`SELECT * FROM mission_${c}_payouts WHERE work_id=?`,[w.id]);
    if(p?.receipt_id&&w.state==='provider_confirmed'&&/^incoming:[a-f0-9]{64}$/.test(String(p.receipt_id))&&p.settlement_hash){const r=db.get<Row>("SELECT * FROM mission_money_receipts WHERE provider=? AND external_id=? AND kind='earning'",[`${c}-settlement`,p.receipt_id]);const j=db.get<Row>("SELECT * FROM mission_earning_jobs WHERE opportunity_id=? AND agent_id=? AND provider_ref=? AND state='completed'",[w.opportunity_id,d.agent_id,p.receipt_id]);
     if(r&&j&&verifyCashLedger().ok&&db.get('SELECT id FROM mission_cash_entries WHERE account_id=? AND reference=? AND delta_cents=?',['treasury',p.receipt_id,r.amount_cents])&&r.agent_id===d.agent_id&&Number(r.amount_cents)===Number(p.net_cents)&&['booked','review','reversed'].includes(String(p.state))){const net=Number(p.net_cents)-Number(p.reversed_cents);if(!Number.isSafeInteger(net)||net<0)deny('invalid_settlement_history');historicalReceivedNetUsdCents=net;receivedNetUsdCents=p.state==='booked'?net:0;receiptId=String(r.external_id);stage=net===0?'reversed':p.state==='booked'?'verified_usd_received':'settlement_under_review';reviewRequired=p.state!=='booked';}
    }
   }
  }
  return {id:d.id,state:d.state,stage,origin:d.origin,serviceId:d.service_id,proposedUsdCents:Number(d.quote_cents),receivedNetUsdCents,historicalReceivedNetUsdCents,receiptId,reviewRequired,contactStopped:d.state==='stopped',cashCreditedByThisModule:false,inquiryAuthenticity:'owner_declared_not_independently_verified',note:'Received net is historical attributed settlement, not current spendable balance or profit. Use the verified mission wallet for allocations, costs and withdrawals.'};
 });}
 overview(actor:MoneyActor){assertMoneyOwner(actor);const requests=db.all<Row>('SELECT id FROM mission_customer_requests ORDER BY created_at DESC,id LIMIT 200');return {channelInventory:CUSTOMER_CHANNELS,offers:SERVICE_OFFERS,requests:requests.map(x=>{try{return this.progress(actor,String(x.id));}catch{return {id:x.id,stage:'binding_requires_review',receivedNetUsdCents:null,reviewRequired:true};}}),limit:200,totalRecords:Number(db.get<Row>('SELECT COUNT(*) AS n FROM mission_customer_requests')?.n),automaticOutreach:false,publishingEnabled:false,newPaymentAdapter:false,note:'No acquired customers are inferred from listing packs, inquiries or prepared responses. No aggregates over paginated results.'};}
 detail(actor:MoneyActor,id:string){assertMoneyOwner(actor);return {request:this.request(id),progress:this.progress(actor,id)};}
}
