import {randomUUID} from 'node:crypto';
import path from 'node:path';import os from 'node:os';
process.env.ZA141251SA_DATABASE_URL=process.env.PG_TEST_DATABASE_URL||`file:${path.join(os.tmpdir(),`toptal-${randomUUID()}.db`)}`;
process.env.ZA141251SA_SESSION_SECRET='synthetic-toptal-tests-not-live-credentials';
import {before,beforeEach,after,it} from 'node:test';import assert from 'node:assert/strict';
import type {ToptalAuthority,ToptalPeriod,ToptalDelivery,ToptalRemittance,ToptalReceivingProof,ToptalReversal,ToptalProvider,ToptalUsdReceiver} from './toptal-contracts';
const {ToptalWorkflow,readToptalProof,configuredToptalWorkflow}=require('./toptal-workflow') as typeof import('./toptal-workflow');
const {missionDb:db,applyMissionMigrations,sha256,verifyMissionAudit}=require('../database') as typeof import('../database');
const money=require('../money') as typeof import('../money');
const {updatePolicy,setKillSwitch}=require('../policy') as typeof import('../policy');
import type {Row} from '../database';
const owner={kind:'owner' as const,id:'toptal-fixture-owner'}, agent='toptal-fixture-agent', other='toptal-fixture-other';
const keepAlive=setInterval(()=>{},1000);
let authority:ToptalAuthority,period:ToptalPeriod,delivery:ToptalDelivery,payout:ToptalRemittance,receiving:ToptalReceivingProof,reversal:ToptalReversal;
let source:ToptalProvider,receiver:ToptalUsdReceiver,w:InstanceType<typeof ToptalWorkflow>,beforeReceiving:(()=>void|Promise<void>)|undefined;
const now=()=>new Date().toISOString();
const tables=['mission_toptal_time','mission_toptal_events','mission_toptal_payouts','mission_toptal_work','mission_toptal_accounts','mission_earning_jobs','mission_money_receipts','mission_cash_liabilities','mission_cash_entries','mission_money_transfers','mission_money_operations','mission_money_grants','mission_money_opportunities','mission_cash_accounts'];
before(()=>{applyMissionMigrations();db.run("INSERT INTO mission_owner (id,email,password_hash,role,status) VALUES (?,'fixture-toptal@example.test','fixture','owner','active')",[owner.id]);for(const id of [agent,other])db.run("INSERT INTO mission_agents (id,slug,name,role_key,depth,generation,status,mission_role,origin_platform) VALUES (?,?,'Synthetic fixture','specialist',0,'custom','active','worker','fixture')",[id,id]);});
beforeEach(()=>{
  setKillSwitch(false,owner.id);for(const t of tables)db.run(`DELETE FROM ${t}`);
  updatePolicy({currency:'USD',killSwitch:false,autonomousEnabled:true,maxDailySpendCents:100000,maxExpenseCents:10000,requireApprovalAboveCents:500},owner.id);
  for(const id of [agent,other])money.setMoneyGrant(owner,id,{spendLimitCents:0,delegationCents:0,canCreate:false,expiresAt:new Date(Date.now()+86400000).toISOString(),status:'active'});
  const identity={accountId:'synthetic-account'},proof={evidenceRef:'synthetic-proof-not-money',verifiedAt:now(),authenticityVerified:true};
  authority={...identity,...proof,missionOwnerId:owner.id,ownerControlVerified:true,role:'talent',screenedTalentVerified:true,accountType:'individual',identityVerified:true,eligible:true,workflow:'human_assisted',goodStanding:true,evidenceUseAuthorized:true,periodReadApproved:true,deliveryReadApproved:true,paymentReadApproved:true,durableRecordsApproved:true,permissionExpiresAt:new Date(Date.now()+86400000).toISOString()};
  const end = Math.floor(Date.now()/60000)*60000-60000;
  period={...identity,...proof,periodId:'synthetic-period',engagementId:'synthetic-engagement',agreementId:'synthetic-agreement',agreementHash:sha256('synthetic signed engagement'),signedEngagementVerified:true,workerClassificationVerified:true,activity:'software_development',paymentStatus:'unpaid',payableWorkAccepted:false,acceptedDeliveryHash:null,paymentId:null,clientId:'synthetic-client',scopeHash:sha256('synthetic scope'),kind:'hourly',currency:'USD',state:'active',independentClientVerified:true,rightsCleared:true,trial:false,suspended:false,disputed:false,providerAssistanceAllowed:true,aiAssistanceAllowed:true,clientDataUseAllowed:true,rateCents:5000,authorizedMinutes:300,periodStart:new Date(end-6*3600000).toISOString(),periodEnd:new Date(end).toISOString(),grossCents:0,talentNetCents:0,timesheetId:null,timesheetApproved:false,timesheetApprovedAt:null,humanWorkVerified:false,nonOverlappingWorkVerified:false,agentRuntimeExcluded:false,billedMinutes:0,workIntervals:[]};
  delivery={...identity,...proof,engagementId:period.engagementId,channelApproved:true,periodId:period.periodId,agreementId:period.agreementId,clientId:period.clientId,submissionId:'synthetic-submission',submittedAt:now(),state:'submitted',content:'// Synthetic test artifact, not paid work\nexport const answer = 42;'};
  payout={...identity,...proof,payoutId:'synthetic-payout',state:'paid',complete:true,currency:'USD',payoutFeeCents:300,netCents:19700,lines:[{kind:'hourly_work',engagementId:period.engagementId,timesheetId:'synthetic-timesheet',periodId:period.periodId,agreementId:period.agreementId,paymentId:'synthetic-payment',currency:'USD',grossCents:20000,feeCents:0,netCents:20000}]};
  receiving={...identity,...proof,source:'toptal',payoutId:payout.payoutId,rail:'synthetic-bank',receivingAccount:'synthetic-mission-account',externalId:'synthetic-credit',state:'settled',direction:'credit',currency:'USD',missionOwnershipVerified:true,grossCents:19700,feeCents:100,netCents:19600,availableBalanceCents:1000000,fxApplied:false};
  reversal={...identity,...proof,source:'toptal',payoutId:payout.payoutId,rail:receiving.rail,receivingAccount:receiving.receivingAccount,originalExternalId:receiving.externalId,reversalExternalId:'synthetic-debit',state:'settled',direction:'debit',currency:'USD',missionOwnershipVerified:true,amountCents:19600};
  source={...identity,authority:async()=>structuredClone(authority),period:async()=>structuredClone(period),delivery:async()=>structuredClone(delivery),remittance:async()=>structuredClone(payout)};
  beforeReceiving=undefined;receiver={rail:receiving.rail,receivingAccount:receiving.receivingAccount,verify:async()=>{const snapshot=structuredClone(receiving);await beforeReceiving?.();return snapshot;},reversal:async()=>structuredClone(reversal)};
  w=new ToptalWorkflow(source,receiver);
});
after(()=>{try{db.close();}finally{clearInterval(keepAlive);}});
const auth=(id=agent)=>w.authorizeAccount(owner,{agentId:id,reviewRef:'synthetic-human-review',expiresAt:new Date(Date.now()+3600000).toISOString()});
async function assigned(){await auth();return w.assign(owner,period.periodId);}
async function prepared(){const row=await assigned(),draft=w.draft(owner,String(row.id),delivery.content);w.approve(owner,String(row.id),String(draft.content_hash),'synthetic-human-quality-review');await w.beginManualDelivery(owner,String(row.id));delivery.submittedAt=now();delivery.verifiedAt=now();await w.confirmDelivery(owner,String(row.id),delivery.submissionId);return String(row.id);}
function paidPeriod() {
  period.state='completed';period.paymentStatus='paid';period.payableWorkAccepted=true;period.acceptedDeliveryHash=sha256(delivery.content);
  period.grossCents=20000;period.talentNetCents=20000;period.paymentId='synthetic-payment';period.timesheetId='synthetic-timesheet';period.timesheetApproved=true;period.timesheetApprovedAt=now();
  period.humanWorkVerified=true;period.nonOverlappingWorkVerified=true;period.agentRuntimeExcluded=true;period.billedMinutes=240;
  period.workIntervals=[{start:period.periodStart,end:new Date(Date.parse(period.periodStart)+4*3600000).toISOString()}];
}
async function confirmed(){const id=await prepared();paidPeriod();await w.observePayment(owner,id);return id;}
const settle=(id:string)=>w.reconcile(owner,id,payout.payoutId,receiving.externalId);
const balance=()=>Number(money.ensureCashAccount().available_cents);
const noCash=()=>{assert.equal(balance(),0);assert.equal(db.all('SELECT * FROM mission_money_receipts').length,0);assert.equal(db.all('SELECT * FROM mission_earning_jobs').length,0);};
it('default factory stays blocked; no credential flag registers a cash or spend provider',async()=>{const off=configuredToptalWorkflow();assert.equal(off.overview(owner).cashBridgeEnabled,false);assert.equal(off.overview(owner).lifecycle.length,9);await assert.rejects(off.inspect(owner,'period'),/not_configured/);noCash();});
it('all commands require an actual active mission owner, not agent or owner-looking ID',async()=>{
  const actor={kind:'agent' as const,id:agent};assert.throws(()=>w.overview(actor),/owner_required/);await assert.rejects(w.inspect(actor,'period'),/owner_required/);await assert.rejects(w.authorizeAccount(actor,{agentId:agent,reviewRef:'fake',expiresAt:now()}),/owner_required/);await assert.rejects(w.reconcile(actor,'work','p','e'),/owner_required/);await assert.rejects(w.reconcileReversal(actor,'work','r'),/owner_required/);
});
const permissionFailures:Record<string,(a:ToptalAuthority)=>void>={
  'not screened':a=>{a.screenedTalentVerified=false;},'wrong role':a=>{a.role='client' as 'talent';},'no owner control':a=>{a.ownerControlVerified=false;},'different mission owner':a=>{a.missionOwnerId='other';},
  'no lawful record-use permission':a=>{a.evidenceUseAuthorized=false;},'no identity verification':a=>{a.identityVerified=false;},'no eligibility':a=>{a.eligible=false;},'suspended account':a=>{a.goodStanding=false;},
  'no period scope':a=>{a.periodReadApproved=false;},'no delivery scope':a=>{a.deliveryReadApproved=false;},'no payment scope':a=>{a.paymentReadApproved=false;},'no durable evidence permission':a=>{a.durableRecordsApproved=false;},
  'unauthenticated records':a=>{a.authenticityVerified=false;},'platform automation':a=>{a.workflow='bot' as 'human_assisted';},'wrong account':a=>{a.accountId='other';},
  'agency instead of individual':a=>{a.accountType='agency' as 'individual';},'expired permission':a=>{a.permissionExpiresAt='2000-01-01T00:00:00Z';},'stale evidence':a=>{a.verifiedAt='2000-01-01T00:00:00Z';},'future evidence':a=>{a.verifiedAt=new Date(Date.now()+60000).toISOString();},
};
for(const [name,mutate] of Object.entries(permissionFailures))it(`blocks ${name} before persisting provider-derived evidence`,async()=>{mutate(authority);await assert.rejects(auth());assert.equal(db.all('SELECT * FROM mission_toptal_accounts').length,0);assert.equal(db.all('SELECT * FROM mission_toptal_events').length,0);noCash();});
it('exclusive account and period assignments survive new workflow instances',async()=>{await auth();await assert.rejects(auth(other),/exclusive_account/);const row=await w.assign(owner,period.periodId);const next=new ToptalWorkflow(source,receiver);await assert.rejects(next.assign(owner,period.periodId),/exclusive_period/);assert.equal(db.all('SELECT * FROM mission_toptal_work').length,1);assert.ok(row.opportunity_id);});
it('inspection is non-executable and no stage before actual settlement credits cash',async()=>{assert.equal((await w.inspect(owner,period.periodId)).executable,false);const id=await confirmed();await w.observePayout(owner,id,payout.payoutId);noCash();});
const periodFailures:Record<string,(c:ToptalPeriod)=>void>={
 'unverified client':c=>{c.independentClientVerified=false;},'self purchase':c=>{c.clientId=c.accountId;},'missing rights':c=>{c.rightsCleared=false;},'foreign currency':c=>{c.currency='EUR';},'fixed price':c=>{c.kind='fixed' as 'hourly';},'unsigned engagement':c=>{c.signedEngagementVerified=false;},'trial work':c=>{c.trial=true;},'suspended':c=>{c.suspended=true;},'dispute':c=>{c.disputed=true;},'no client AI permission':c=>{c.aiAssistanceAllowed=false;},'no provider AI permission':c=>{c.providerAssistanceAllowed=false;},'no data permission':c=>{c.clientDataUseAllowed=false;},'wrong identity':c=>{c.accountId='other';},'cancelled':c=>{c.state='cancelled';},'inexact amount':c=>{c.grossCents=0.1;},'unverified classification':c=>{c.workerClassificationVerified=false;},'unsupported activity':c=>{c.activity='recruiting' as 'software_development';},'missing agreement':c=>{c.agreementId='';},'invalid terms hash':c=>{c.agreementHash='bad';},'missing engagement':c=>{c.engagementId='';},'inexact rate':c=>{c.rateCents=10.1;},'zero authorized time':c=>{c.authorizedMinutes=0;},'time cap exceeds window':c=>{c.authorizedMinutes=1000;},'invalid start':c=>{c.periodStart='bad';},'reversed window':c=>{c.periodEnd=c.periodStart;},'unsupported long period':c=>{c.periodEnd=new Date(Date.parse(c.periodStart)+8*86400000).toISOString();},'paid before work':c=>{c.grossCents=20000;},
};
for(const [name,mutate] of Object.entries(periodFailures))it(`rejects assignment: ${name}`,async()=>{await auth();mutate(period);await assert.rejects(w.assign(owner,period.periodId));assert.equal(db.all('SELECT * FROM mission_toptal_work').length,0);noCash();});
it('owner approvals bind exact real artifact bytes and freeze them after approval',async()=>{const r=await assigned(),id=String(r.id);await assert.rejects(w.beginManualDelivery(owner,id),/approved_work/);const draft=w.draft(owner,id,delivery.content);assert.throws(()=>w.approve(owner,id,sha256('wrong'),'review'),/approval_mismatch/);w.approve(owner,id,String(draft.content_hash),'review');assert.throws(()=>w.draft(owner,id,'replacement'),/immutable/);await w.beginManualDelivery(owner,id);await assert.rejects(w.beginManualDelivery(owner,id),/approved_work/);noCash();});
it('revocation while a delivery intent is awaiting proof blocks the outward handoff',async()=>{const r=await assigned(),id=String(r.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'review');source.period=async()=>{w.revokeAccount(owner);return period;};await assert.rejects(w.beginManualDelivery(owner,id),/authorization_required/);assert.equal(db.get<Row>('SELECT state FROM mission_toptal_work WHERE id=?',[id])!.state,'approved');});
it('changing the authorized scope prevents delivery',async()=>{const r=await assigned(),id=String(r.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'review');period.scopeHash=sha256('changed');await assert.rejects(w.beginManualDelivery(owner,id),/period_changed/);});
const deliveryFailures:Record<string,(d:ToptalDelivery)=>void>={'wrong bytes':d=>{d.content='metadata cannot prove bytes';},'wrong sender':d=>{d.accountId='other';},'wrong recipient':d=>{d.clientId='other';},'wrong submission':d=>{d.submissionId='other';},'wrong period':d=>{d.periodId='other';},'before authorization':d=>{d.submittedAt='2000-01-01T00:00:00Z';}};
for(const [name,mutate] of Object.entries(deliveryFailures))it(`delivery readback rejects ${name}`,async()=>{const r=await assigned(),id=String(r.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'review');await w.beginManualDelivery(owner,id);delivery.submittedAt=now();delivery.verifiedAt=now();mutate(delivery);await assert.rejects(w.confirmDelivery(owner,id,'synthetic-submission'));assert.equal(db.get<Row>('SELECT state FROM mission_toptal_work WHERE id=?',[id])!.state,'awaiting_manual_delivery');noCash();});
it('read-only manual delivery recovery remains possible after grant revocation without authorizing more work',async()=>{const id=await prepared();w.revokeAccount(owner);setKillSwitch(true,owner.id);await w.confirmDelivery(owner,id,delivery.submissionId);assert.throws(()=>w.draft(owner,id,'new'),/policy_blocked/);noCash();});
it('complete chain credits only independent receiving net USD, once across concurrent/restarted callers',async()=>{const id=await confirmed();const results=await Promise.all([settle(id),new ToptalWorkflow(source,receiver).reconcile(owner,id,payout.payoutId,receiving.externalId)]);assert.equal(results.filter(r=>!r.duplicated).length,1);assert.equal(balance(),19600);assert.equal(money.cashAccount(agent).available_cents,0);assert.equal((await settle(id)).duplicated,true);assert.equal(db.all('SELECT * FROM mission_earning_jobs').length,1);assert.equal(money.verifyCashLedger().ok,true);assert.equal(verifyMissionAudit().ok,true);});
it('earned settlement can be received after mission revocation/freeze without restoring spending authority',async()=>{const id=await confirmed();w.revokeAccount(owner);setKillSwitch(true,owner.id);await settle(id);assert.equal(balance(),19600);assert.throws(()=>money.allocateCash(owner,agent,1,'fixture'),/kill_switch/);});
const payoutFailures:Record<string,(p:ToptalRemittance)=>void>={'pending':p=>{p.state='pending';},'partial':p=>{p.complete=false;},'mixed currency':p=>{p.currency='EUR';},'unattributed extra line':p=>{p.lines.push({...p.lines[0]});},'wrong period':p=>{p.lines[0].periodId='other';},'invalid fees':p=>{p.lines[0].feeCents=-1;},'wrong total':p=>{p.netCents=17999;},'wrong gross':p=>{p.lines[0].grossCents=19000;p.lines[0].feeCents=1000;},'wrong payout':p=>{p.payoutId='other';},'wrong owner':p=>{p.accountId='other';}};
for(const [name,mutate] of Object.entries(payoutFailures))it(`payout ${name} is not cash`,async()=>{const id=await confirmed();mutate(payout);await assert.rejects(w.reconcile(owner,id,'synthetic-payout','synthetic-credit'),/blocked_or_uncertain/);noCash();});
const receivingFailures:Record<string,(r:ToptalReceivingProof)=>void>={'pending':r=>{r.state='pending';},'balance only':r=>{r.missionOwnershipVerified=false;},'non USD':r=>{r.currency='PKR';},'wrong source':r=>{r.source='freelancer' as 'toptal';},'wrong account':r=>{r.receivingAccount='other';},'wrong rail':r=>{r.rail='other';},'wrong movement':r=>{r.externalId='other';},'wrong provider account':r=>{r.accountId='other';},'wrong direction':r=>{r.direction='debit' as 'credit';},'wrong payout':r=>{r.payoutId='other';},'fee mismatch':r=>{r.feeCents=0;},'gross mismatch':r=>{r.grossCents=19600;r.feeCents=0;},'insufficient bank funds':r=>{r.availableBalanceCents=19599;},'stale':r=>{r.verifiedAt='2000-01-01T00:00:00Z';},'future':r=>{r.verifiedAt=new Date(Date.now()+60000).toISOString();}};
for(const [name,mutate] of Object.entries(receivingFailures))it(`receiving ${name} cannot credit or leave partial bookkeeping`,async()=>{const id=await confirmed();mutate(receiving);await assert.rejects(w.reconcile(owner,id,'synthetic-payout','synthetic-credit'),/blocked_or_uncertain/);noCash();assert.equal(db.all('SELECT * FROM mission_toptal_payouts').length,0);});
it('missing receiving adapter cannot be substituted by provider balance or caller flags',async()=>{const id=await confirmed();await assert.rejects(new ToptalWorkflow(source).reconcile(owner,id,payout.payoutId,receiving.externalId),/not_configured/);noCash();});
it('provider permission loss during independent proof lookup blocks commit',async()=>{const id=await confirmed();beforeReceiving=()=>{authority.evidenceUseAuthorized=false;};await assert.rejects(settle(id),/blocked_or_uncertain/);noCash();});
it('work changes while bank lookup awaits block atomic admission',async()=>{const id=await confirmed();beforeReceiving=()=>{db.run('UPDATE mission_toptal_work SET approved_hash=? WHERE id=?',[sha256('changed'),id]);};await assert.rejects(settle(id),/blocked_or_uncertain/);noCash();});
it('a deactivated owner cannot admit funds after an await',async()=>{const id=await confirmed();beforeReceiving=()=>{db.run("UPDATE mission_owner SET status='disabled' WHERE id=?",[owner.id]);};try{await assert.rejects(settle(id),/owner_required/);noCash();}finally{db.run("UPDATE mission_owner SET status='active' WHERE id=?",[owner.id]);}});
it('one physical bank movement cannot be credited by two connectors',async()=>{const id=await confirmed(),externalId='incoming:'+sha256(JSON.stringify([receiving.rail,receiving.receivingAccount,receiving.externalId]));db.run("INSERT INTO mission_money_receipts (provider,external_id,fingerprint,kind,amount_cents,created_at) VALUES ('awin-settlement',?,'synthetic','earning',19600,?)",[externalId,now()]);await assert.rejects(settle(id),/blocked_or_uncertain/);assert.equal(balance(),0);assert.equal(db.all('SELECT * FROM mission_toptal_payouts').length,0);});
it('a booked payout cannot be assigned another receiving transfer or payout ID',async()=>{const id=await confirmed();await settle(id);receiving.externalId='other';await assert.rejects(settle(id),/blocked_or_uncertain/);assert.equal(balance(),19600);assert.equal(money.ensureCashAccount().frozen,1);});
it('changed or missing booked payment proof freezes access, not an invented debit',async()=>{const id=await confirmed();await settle(id);period.talentNetCents=0;await assert.rejects(w.observePayment(owner,id),/payment_unconfirmed/);assert.equal(balance(),19600);assert.equal(money.ensureCashAccount().frozen,1);});
it('duplicate reconciliation checks current bank sufficiency, not only original receipt',async()=>{const id=await confirmed();await settle(id);receiving.availableBalanceCents=0;await assert.rejects(settle(id),/blocked_or_uncertain/);assert.equal(balance(),19600);assert.equal(money.ensureCashAccount().frozen,1);});
it('independent reversals are exact, bounded and idempotent',async()=>{const id=await confirmed();await settle(id);assert.equal((await w.reconcileReversal(owner,id,reversal.reversalExternalId)).duplicated,false);assert.equal(balance(),0);assert.equal((await w.reconcileReversal(owner,id,reversal.reversalExternalId)).duplicated,true);assert.equal(money.verifyCashLedger().ok,true);assert.equal(verifyMissionAudit().ok,true);});
it('partial reversals cannot exceed original actual net and cannot restore earning credit',async()=>{const id=await confirmed();await settle(id);reversal.amountCents=10000;await w.reconcileReversal(owner,id,reversal.reversalExternalId);assert.equal(balance(),9600);reversal.reversalExternalId='second';await assert.rejects(w.reconcileReversal(owner,id,'second'),/blocked_or_uncertain/);assert.equal(balance(),9600);await assert.rejects(settle(id),/blocked_or_uncertain/);});
for(const field of ['missionOwnershipVerified','currency','source','state','originalExternalId','reversalExternalId','receivingAccount'] as const)it(`reversal rejects unverified ${field}`,async()=>{const id=await confirmed();await settle(id);(reversal as unknown as Record<string,unknown>)[field]=field==='missionOwnershipVerified'?false:'other';await assert.rejects(w.reconcileReversal(owner,id,'synthetic-debit'),/blocked_or_uncertain/);assert.equal(balance(),19600);});
it('original credit ID cannot masquerade as a reversal',async()=>{const id=await confirmed();await settle(id);await assert.rejects(w.reconcileReversal(owner,id,receiving.externalId),/original_settlement_required/);assert.equal(balance(),19600);});
it('adapter errors and getter failures cannot disclose credentials',async()=>{const id=await confirmed();source.remittance=async()=>{throw new Error('credential-SYNTHETIC-DO-NOT-EXPOSE');};await assert.rejects(settle(id),e=>e instanceof Error&&!e.message.includes('credential-'));source.authority=async()=>Object.defineProperty({...authority},'eligible',{enumerable:true,get(){throw new Error('credential-SYNTHETIC-DO-NOT-EXPOSE');}});await assert.rejects(auth(),e=>e instanceof Error&&e.message==='toptal_verification_unavailable');noCash();});
it('proof deadline aborts ignored/late adapters and cannot admit later data',async t=>{t.mock.timers.enable({apis:['setTimeout']});let signal:AbortSignal|undefined,resolve!:(value:{n:number})=>void;const waiting=readToptalProof(s=>{signal=s;return new Promise(r=>{resolve=r;});});const rejected=assert.rejects(waiting,/verification_unavailable/);await Promise.resolve();await Promise.resolve();t.mock.timers.tick(30001);await rejected;assert.equal(signal!.aborted,true);resolve({n:1});await Promise.resolve();noCash();});
it('pending provider payout observations never become cash and cannot be rebound to other work',async()=>{const id=await confirmed();payout.state='pending';assert.equal((await w.observePayout(owner,id,payout.payoutId)).cashCredited,false);await assert.rejects(settle(id));noCash();payout.state='paid';await settle(id);payout.payoutId='new-id';receiving.payoutId='new-id';await assert.rejects(settle(id));assert.equal(balance(),19600);});
it('owner authority and grant expiry are checked after account verification awaits',async()=>{source.authority=async()=>{db.run("UPDATE mission_money_grants SET status='revoked' WHERE agent_id=?",[agent]);return authority;};await assert.rejects(auth());assert.equal(db.all('SELECT * FROM mission_toptal_accounts').length,0);});
it('lost booked delivery evidence freezes funds without inventing a bank debit',async()=>{const id=await confirmed();await settle(id);delivery.content='different';await assert.rejects(w.confirmDelivery(owner,id,delivery.submissionId),/delivery_unconfirmed/);assert.equal(balance(),19600);assert.equal(money.ensureCashAccount().frozen,1);});
it('verified reversal preserves nonnegative isolated ledgers after owner allocation',async()=>{const id=await confirmed();await settle(id);money.allocateCash(owner,agent,15000,'synthetic-allocation');await w.reconcileReversal(owner,id,reversal.reversalExternalId);assert.ok(db.all<Row>('SELECT available_cents,held_cents FROM mission_cash_accounts').every(a=>Number(a.available_cents)>=0&&Number(a.held_cents)>=0));assert.equal(money.verifyCashLedger().ok,true);});
it('one mission owner cannot provision duplicate personal Toptal accounts for more agents',async()=>{await auth();authority.accountId='second-account';const second=new ToptalWorkflow({...source,accountId:'second-account'},receiver);await assert.rejects(second.authorizeAccount(owner,{agentId:other,reviewRef:'synthetic',expiresAt:new Date(Date.now()+3600000).toISOString()}),/exclusive_account_conflict/);assert.equal(db.all('SELECT * FROM mission_toptal_accounts').length,1);});
for(const stage of ['period','delivery','payout','receiving'] as const)it(`unauthenticated ${stage} is not provider/receiving proof`,async()=>{
  const id=await confirmed();({period,delivery,payout,receiving}[stage]).authenticityVerified=false;await assert.rejects(settle(id));noCash();
});
for(const kind of ['compensation','cash_advance','tip','refund','expense_cancellation'])it(`${kind} cannot masquerade as customer-paid period work`,async()=>{const id=await confirmed();payout.lines[0].kind=kind as 'hourly_work';await assert.rejects(settle(id));noCash();});
it('a completed period without approved timesheet is not confirmed payment or cash',async()=>{const id=await prepared();period.state='completed';period.talentNetCents=20000;await assert.rejects(w.observePayment(owner,id));noCash();});
it('an active period marked paid cannot bypass actual period completion',async()=>{const id=await prepared();period.paymentStatus='paid';period.talentNetCents=20000;await assert.rejects(w.observePayment(owner,id));noCash();});
it('withdrawal fee, talent deduction and receiving fee are separately attributed',async()=>{const id=await confirmed();assert.equal(payout.lines[0].grossCents,20000);assert.equal(payout.lines[0].feeCents,0);assert.equal(payout.payoutFeeCents,300);assert.equal(receiving.feeCents,100);await settle(id);assert.equal(balance(),19600);});
for(const fee of [-1,0,1.5,17000,NaN])it(`invalid/mismatched withdrawal deduction ${fee} never credits cash`,async()=>{const id=await confirmed();payout.payoutFeeCents=fee;await assert.rejects(settle(id));noCash();});
it('talent earnings cannot change between confirmation and remittance',async()=>{const id=await confirmed();period.talentNetCents=15000;payout.lines[0].feeCents=5000;payout.lines[0].netCents=15000;await assert.rejects(settle(id));noCash();});
it('cancellation during receiving lookup blocks final admission',async()=>{const id=await confirmed();beforeReceiving=()=>{period.state='cancelled';};await assert.rejects(settle(id));noCash();});
it('withdrawal failure during receiving lookup blocks final admission',async()=>{const id=await confirmed();beforeReceiving=()=>{payout.state='pending';};await assert.rejects(settle(id));noCash();});
it('an unauthenticated reversal freezes rather than inventing a debit',async()=>{const id=await confirmed();await settle(id);reversal.authenticityVerified=false;await assert.rejects(w.reconcileReversal(owner,id,reversal.reversalExternalId));assert.equal(balance(),19600);assert.equal(money.ensureCashAccount().frozen,1);});
it('a provider-reported refund alone freezes booked funds but cannot debit the wallet',async()=>{const id=await confirmed();await settle(id);period.state='cancelled';await assert.rejects(w.observePayment(owner,id));assert.equal(balance(),19600);assert.equal(db.all("SELECT * FROM mission_money_receipts WHERE kind='reversal'").length,0);assert.equal(money.ensureCashAccount().frozen,1);});

const timeFailures:Record<string,(p:ToptalPeriod)=>void>={
  'unapproved timesheet':p=>{p.timesheetApproved=false;},
  'unaccepted payable work':p=>{p.payableWorkAccepted=false;},
  'unverified human performance':p=>{p.humanWorkVerified=false;},
  'unverified non-overlap':p=>{p.nonOverlappingWorkVerified=false;},
  'agent runtime billed as human time':p=>{p.agentRuntimeExcluded=false;},
  'missing timesheet identity':p=>{p.timesheetId=null;},
  'missing talent payment identity':p=>{p.paymentId=null;},
  'missing approval timestamp':p=>{p.timesheetApprovedAt=null;},
  'premature approval':p=>{p.timesheetApprovedAt=p.periodStart;},
  'future approval':p=>{p.timesheetApprovedAt=new Date(Date.now()+60000).toISOString();},
  'absent human intervals':p=>{p.workIntervals=[];},
  'duplicate human intervals':p=>{p.workIntervals.push({...p.workIntervals[0]});},
  'invalid interval date':p=>{p.workIntervals[0].start='invalid';},
  'reversed interval':p=>{p.workIntervals[0].start=p.workIntervals[0].end;},
  'out-of-period time':p=>{p.workIntervals[0].start=new Date(Date.parse(p.periodStart)-60000).toISOString();},
  'work after period close':p=>{p.workIntervals[0].end=new Date(Date.parse(p.periodEnd)+60000).toISOString();},
  'fractional minute':p=>{p.workIntervals[0].end=new Date(Date.parse(p.workIntervals[0].end)+1).toISOString();},
  'billed total exceeds actual work':p=>{p.billedMinutes=241;},
  'billed total above authorized cap':p=>{p.billedMinutes=301;},
  'invoice higher than rate times actual minutes':p=>{p.grossCents=20001;},
  'wrong accepted bytes':p=>{p.acceptedDeliveryHash=sha256('other work');},
  'unpaid provider balance':p=>{p.paymentStatus='unpaid';},
};
for(const [label,mutate] of Object.entries(timeFailures))it(`provider confirmation rejects ${label} with no partial time reservation`,async()=>{
  const id=await prepared();paidPeriod();mutate(period);await assert.rejects(w.observePayment(owner,id),/payment_unconfirmed/);
  assert.equal(db.all('SELECT * FROM mission_toptal_time').length,0);assert.equal(db.get<Row>('SELECT state FROM mission_toptal_work WHERE id=?',[id])!.state,'delivered');noCash();
});
for(const field of ['agreementId','engagementId','timesheetId','paymentId'] as const)it(`remittance binds exact ${field}`,async()=>{const id=await confirmed();payout.lines[0][field]='other';await assert.rejects(settle(id));noCash();});
for(const field of ['agreementHash','engagementId','rateCents','authorizedMinutes','periodStart','periodEnd'] as const)it(`authorized hourly ${field} is immutable`,async()=>{
  const row=await assigned(),id=String(row.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'synthetic-review');
  if(field==='rateCents'||field==='authorizedMinutes')period[field]++;else if(field==='agreementHash')period[field]=sha256('different');else if(field==='periodStart'||field==='periodEnd')period[field]=new Date(Date.parse(period[field])-60000).toISOString();else period[field]='other';
  await assert.rejects(w.beginManualDelivery(owner,id));noCash();
});
it('unapproved client delivery channel is not proof of real delivery',async()=>{const id=await prepared();delivery.channelApproved=false;await assert.rejects(w.confirmDelivery(owner,id,delivery.submissionId));noCash();});
it('preauthorization is a time/rate ceiling, never accrued revenue or cash',async()=>{const row=await assigned();assert.equal(Number(row.gross_cents),0);assert.equal(row.talent_net_cents,null);assert.equal(row.timesheet_id,null);noCash();});
it('actual approved noncontiguous time, below the ceiling, is accepted exactly once',async()=>{
  const id=await prepared();paidPeriod();const start=Date.parse(period.periodStart);
  period.workIntervals=[{start:period.periodStart,end:new Date(start+2*3600000).toISOString()},{start:new Date(start+3*3600000).toISOString(),end:new Date(start+5*3600000).toISOString()}];
  await w.observePayment(owner,id);await w.observePayment(owner,id);assert.equal(db.all('SELECT * FROM mission_toptal_time').length,2);await settle(id);assert.equal(balance(),19600);
});
it('fractional-cent remuneration is unsupported rather than silently rounded or estimated',async()=>{
  period.rateCents=5001;const id=await prepared();paidPeriod();period.billedMinutes=1;period.workIntervals[0].end=new Date(Date.parse(period.periodStart)+60000).toISOString();period.grossCents=83;period.talentNetCents=83;
  await assert.rejects(w.observePayment(owner,id));noCash();
});
it('changed paid timesheet cannot substitute equal-priced but different human hours',async()=>{const id=await confirmed();period.workIntervals[0].start=new Date(Date.parse(period.workIntervals[0].start)+60000).toISOString();period.workIntervals[0].end=new Date(Date.parse(period.workIntervals[0].end)+60000).toISOString();await assert.rejects(settle(id));noCash();});
it('time evidence changing during receiver lookup blocks wallet admission',async()=>{const id=await confirmed();beforeReceiving=()=>{period.timesheetId='other';};await assert.rejects(settle(id));noCash();});
it('delivery evidence changing during receiver lookup blocks wallet admission',async()=>{const id=await confirmed();beforeReceiving=()=>{delivery.content='changed';};await assert.rejects(settle(id));noCash();});
it('USDC and FX-converted receipts are outside this USD-only lane',async()=>{const id=await confirmed();receiving.currency='USDC';await assert.rejects(settle(id));receiving.currency='USD';receiving.fxApplied=true;await assert.rejects(settle(id));noCash();});
it('a lost booked timesheet freezes cash without fabricating a debit',async()=>{const id=await confirmed();await settle(id);period.timesheetApproved=false;await assert.rejects(w.observePayment(owner,id));assert.equal(balance(),19600);assert.equal(money.ensureCashAccount().frozen,1);assert.equal(db.all("SELECT * FROM mission_money_receipts WHERE kind='reversal'").length,0);});
async function nextEngagement(){
  period.humanWorkVerified=false;period.nonOverlappingWorkVerified=false;period.agentRuntimeExcluded=false;period.acceptedDeliveryHash=null;period.periodId='synthetic-period-2';period.engagementId='synthetic-engagement-2';period.state='active';period.paymentStatus='unpaid';period.grossCents=0;period.talentNetCents=0;period.paymentId=null;period.timesheetId=null;period.timesheetApproved=false;period.timesheetApprovedAt=null;period.payableWorkAccepted=false;period.billedMinutes=0;period.workIntervals=[];
  delivery.periodId=period.periodId;delivery.engagementId=period.engagementId;delivery.submissionId='synthetic-submission-2';
  return prepared();
}
it('two engagements cannot bill the same human interval even under different IDs after restart',async()=>{
  await confirmed();const id=await nextEngagement();paidPeriod();period.paymentId='synthetic-payment-2';period.timesheetId='synthetic-timesheet-2';
  await assert.rejects(new ToptalWorkflow(source,receiver).observePayment(owner,id));assert.equal(db.all('SELECT * FROM mission_toptal_time').length,1);noCash();
});
it('separate non-overlapping human time may support another genuine engagement, not extra agent identities',async()=>{
  await confirmed();const id=await nextEngagement();paidPeriod();period.paymentId='synthetic-payment-2';period.timesheetId='synthetic-timesheet-2';period.billedMinutes=120;period.grossCents=10000;period.talentNetCents=10000;period.workIntervals=[{start:new Date(Date.parse(period.periodStart)+4*3600000).toISOString(),end:period.periodEnd}];
  await w.observePayment(owner,id);assert.equal(db.all('SELECT * FROM mission_toptal_time').length,2);noCash();
});
it('a provider talent-payment ID cannot fund two engagement periods',async()=>{
  await confirmed();const id=await nextEngagement();paidPeriod();period.timesheetId='synthetic-timesheet-2';period.billedMinutes=120;period.grossCents=10000;period.talentNetCents=10000;period.workIntervals=[{start:new Date(Date.parse(period.periodStart)+4*3600000).toISOString(),end:period.periodEnd}];
  await assert.rejects(w.observePayment(owner,id));assert.equal(db.all('SELECT * FROM mission_toptal_time').length,1);noCash();
});
it('a provider-approved timesheet ID cannot fund two engagement periods',async()=>{
  await confirmed();const id=await nextEngagement();paidPeriod();period.paymentId='synthetic-payment-2';period.billedMinutes=120;period.grossCents=10000;period.talentNetCents=10000;period.workIntervals=[{start:new Date(Date.parse(period.periodStart)+4*3600000).toISOString(),end:period.periodEnd}];
  await assert.rejects(w.observePayment(owner,id));assert.equal(db.all('SELECT * FROM mission_toptal_time').length,1);noCash();
});

it('aliases cannot assign the same engagement period to multiple work items',async()=>{await assigned();period.periodId='alias';await assert.rejects(w.assign(owner,period.periodId),/exclusive_period/);assert.equal(db.all('SELECT * FROM mission_toptal_work').length,1);noCash();});
