import {randomUUID} from 'node:crypto';
import path from 'node:path';import os from 'node:os';
process.env.ZA141251SA_DATABASE_URL=process.env.PG_TEST_DATABASE_URL||`file:${path.join(os.tmpdir(),`upwork-${randomUUID()}.db`)}`;
process.env.ZA141251SA_SESSION_SECRET='synthetic-upwork-tests-not-live-credentials';
import {before,beforeEach,after,it} from 'node:test';import assert from 'node:assert/strict';
import type {UpworkAuthority,UpworkContract,UpworkDelivery,UpworkRemittance,UpworkReceivingProof,UpworkReversal,UpworkProvider,UpworkUsdReceiver} from './upwork-contracts';
const {UpworkWorkflow,readUpworkProof,configuredUpworkWorkflow}=require('./upwork-workflow') as typeof import('./upwork-workflow');
const {UpworkApiReadProbe}=require('./upwork-api') as typeof import('./upwork-api');
const {missionDb:db,applyMissionMigrations,sha256,verifyMissionAudit}=require('../database') as typeof import('../database');
const money=require('../money') as typeof import('../money');
const {updatePolicy,setKillSwitch}=require('../policy') as typeof import('../policy');
import type {Row} from '../database';
const owner={kind:'owner' as const,id:'upwork-fixture-owner'}, agent='upwork-fixture-agent', other='upwork-fixture-other';
const keepAlive=setInterval(()=>{},1000);
let authority:UpworkAuthority,contract:UpworkContract,delivery:UpworkDelivery,payout:UpworkRemittance,receiving:UpworkReceivingProof,reversal:UpworkReversal;
let source:UpworkProvider,receiver:UpworkUsdReceiver,w:InstanceType<typeof UpworkWorkflow>,beforeReceiving:(()=>void|Promise<void>)|undefined;
const now=()=>new Date().toISOString();
const tables=['mission_upwork_events','mission_upwork_payouts','mission_upwork_work','mission_upwork_accounts','mission_upwork_api_limits','mission_earning_jobs','mission_money_receipts','mission_cash_liabilities','mission_cash_entries','mission_money_transfers','mission_money_operations','mission_money_grants','mission_money_opportunities','mission_cash_accounts'];
before(()=>{applyMissionMigrations();db.run("INSERT INTO mission_owner (id,email,password_hash,role,status) VALUES (?,'fixture-upwork@example.test','fixture','owner','active')",[owner.id]);for(const id of [agent,other])db.run("INSERT INTO mission_agents (id,slug,name,role_key,depth,generation,status,mission_role,origin_platform) VALUES (?,?,'Synthetic fixture','specialist',0,'custom','active','worker','fixture')",[id,id]);});
beforeEach(()=>{
  setKillSwitch(false,owner.id);for(const t of tables)db.run(`DELETE FROM ${t}`);
  updatePolicy({currency:'USD',killSwitch:false,autonomousEnabled:true,maxDailySpendCents:100000,maxExpenseCents:10000,requireApprovalAboveCents:500},owner.id);
  for(const id of [agent,other])money.setMoneyGrant(owner,id,{spendLimitCents:0,delegationCents:0,canCreate:false,expiresAt:new Date(Date.now()+86400000).toISOString(),status:'active'});
  const identity={accountId:'synthetic-account',tenantId:'synthetic-tenant'},proof={evidenceRef:'synthetic-proof-not-money',verifiedAt:now()};
  authority={...identity,...proof,missionOwnerId:owner.id,ownerControlVerified:true,accountType:'individual',identityVerified:true,eligible:true,lifetimeUsdCents:2500000,jobSuccessScore:90,goodStanding:true,internalApiUseApproved:true,contractReadApproved:true,deliveryReadApproved:true,paymentReadApproved:true,durableRecordsApproved:true,permissionExpiresAt:new Date(Date.now()+86400000).toISOString()};
  contract={...identity,...proof,contractId:'synthetic-contract',milestoneId:'synthetic-milestone',clientId:'synthetic-client',scopeHash:sha256('synthetic scope'),kind:'fixed',currency:'USD',state:'active',acceptedByBoth:true,hasAgency:false,suspended:false,disputed:false,aiAssistanceAllowed:true,clientDataUseAllowed:true,grossCents:20000,fundedCents:20000,releasedCents:0};
  delivery={...identity,...proof,contractId:contract.contractId,milestoneId:contract.milestoneId,clientId:contract.clientId,submissionId:'synthetic-submission',submittedAt:now(),state:'submitted',content:'// Synthetic test artifact, not paid work\nexport const answer = 42;'};
  payout={...identity,...proof,payoutId:'synthetic-payout',state:'paid',complete:true,currency:'USD',netCents:18000,lines:[{contractId:contract.contractId,milestoneId:contract.milestoneId,currency:'USD',grossCents:20000,feeCents:2000,netCents:18000}]};
  receiving={...identity,...proof,source:'upwork',payoutId:payout.payoutId,rail:'synthetic-bank',receivingAccount:'synthetic-mission-account',externalId:'synthetic-credit',state:'settled',direction:'credit',currency:'USD',missionOwnershipVerified:true,grossCents:18000,feeCents:100,netCents:17900,availableBalanceCents:1000000};
  reversal={...identity,...proof,source:'upwork',payoutId:payout.payoutId,rail:receiving.rail,receivingAccount:receiving.receivingAccount,originalExternalId:receiving.externalId,reversalExternalId:'synthetic-debit',state:'settled',direction:'debit',currency:'USD',missionOwnershipVerified:true,amountCents:17900};
  source={...identity,authority:async()=>structuredClone(authority),contract:async()=>structuredClone(contract),delivery:async()=>structuredClone(delivery),remittance:async()=>structuredClone(payout)};
  beforeReceiving=undefined;receiver={rail:receiving.rail,receivingAccount:receiving.receivingAccount,verify:async()=>{const snapshot=structuredClone(receiving);await beforeReceiving?.();return snapshot;},reversal:async()=>structuredClone(reversal)};
  w=new UpworkWorkflow(source,receiver);
});
after(()=>{try{db.close();}finally{clearInterval(keepAlive);}});
const auth=(id=agent)=>w.authorizeAccount(owner,{agentId:id,reviewRef:'synthetic-human-review',expiresAt:new Date(Date.now()+3600000).toISOString()});
async function assigned(){await auth();return w.assign(owner,contract.contractId,contract.milestoneId);}
async function prepared(){const row=await assigned(),draft=w.draft(owner,String(row.id),delivery.content);w.approve(owner,String(row.id),String(draft.content_hash),'synthetic-human-quality-review');await w.beginManualDelivery(owner,String(row.id));delivery.submittedAt=now();delivery.verifiedAt=now();await w.confirmDelivery(owner,String(row.id),delivery.submissionId);return String(row.id);}
async function confirmed(){const id=await prepared();contract.releasedCents=20000;await w.observePayment(owner,id);return id;}
const settle=(id:string)=>w.reconcile(owner,id,payout.payoutId,receiving.externalId);
const balance=()=>Number(money.ensureCashAccount().available_cents);
const noCash=()=>{assert.equal(balance(),0);assert.equal(db.all('SELECT * FROM mission_money_receipts').length,0);assert.equal(db.all('SELECT * FROM mission_earning_jobs').length,0);};
it('default factory stays blocked; no credential flag registers a cash or spend provider',async()=>{const off=configuredUpworkWorkflow();assert.equal(off.overview(owner).cashBridgeEnabled,false);assert.equal(off.overview(owner).lifecycle.length,9);await assert.rejects(off.inspect(owner,'contract','milestone'),/not_configured/);noCash();});
it('all commands require an actual active mission owner, not agent or owner-looking ID',async()=>{
  const actor={kind:'agent' as const,id:agent};assert.throws(()=>w.overview(actor),/owner_required/);await assert.rejects(w.inspect(actor,'c','m'),/owner_required/);await assert.rejects(w.authorizeAccount(actor,{agentId:agent,reviewRef:'fake',expiresAt:now()}),/owner_required/);await assert.rejects(w.reconcile(actor,'work','p','e'),/owner_required/);await assert.rejects(w.reconcileReversal(actor,'work','r'),/owner_required/);
});
const permissionFailures:Record<string,(a:UpworkAuthority)=>void>={
  'no owner control':a=>{a.ownerControlVerified=false;},'different mission owner':a=>{a.missionOwnerId='other';},
  'no provider API approval':a=>{a.internalApiUseApproved=false;},'no identity verification':a=>{a.identityVerified=false;},'no eligibility':a=>{a.eligible=false;},'suspended account':a=>{a.goodStanding=false;},
  'no contract scope':a=>{a.contractReadApproved=false;},'no delivery scope':a=>{a.deliveryReadApproved=false;},'no payment scope':a=>{a.paymentReadApproved=false;},'no durable evidence permission':a=>{a.durableRecordsApproved=false;},
  'below API earnings/spend criterion':a=>{a.lifetimeUsdCents=2499999;},'below JSS criterion':a=>{a.jobSuccessScore=89;},'invalid JSS':a=>{a.jobSuccessScore=NaN;},'wrong account':a=>{a.accountId='other';},'wrong tenant':a=>{a.tenantId='other';},
  'agency instead of individual':a=>{a.accountType='agency' as 'individual';},'expired permission':a=>{a.permissionExpiresAt='2000-01-01T00:00:00Z';},'stale evidence':a=>{a.verifiedAt='2000-01-01T00:00:00Z';},'future evidence':a=>{a.verifiedAt=new Date(Date.now()+60000).toISOString();},
};
for(const [name,mutate] of Object.entries(permissionFailures))it(`blocks ${name} before persisting API-derived evidence`,async()=>{mutate(authority);await assert.rejects(auth());assert.equal(db.all('SELECT * FROM mission_upwork_accounts').length,0);assert.equal(db.all('SELECT * FROM mission_upwork_events').length,0);noCash();});
it('exclusive account and contract assignments survive new workflow instances',async()=>{await auth();await assert.rejects(auth(other),/exclusive_account/);const row=await w.assign(owner,contract.contractId,contract.milestoneId);const next=new UpworkWorkflow(source,receiver);await assert.rejects(next.assign(owner,contract.contractId,contract.milestoneId),/exclusive_contract/);assert.equal(db.all('SELECT * FROM mission_upwork_work').length,1);assert.ok(row.opportunity_id);});
it('inspection is non-executable and no stage before actual settlement credits cash',async()=>{assert.equal((await w.inspect(owner,contract.contractId,contract.milestoneId)).executable,false);const id=await confirmed();await w.observePayout(owner,id,payout.payoutId);noCash();});
const contractFailures:Record<string,(c:UpworkContract)=>void>={
 'agency contract':c=>{c.hasAgency=true;},'foreign currency':c=>{c.currency='EUR';},'hourly work':c=>{c.kind='hourly' as 'fixed';},'unaccepted offer':c=>{c.acceptedByBoth=false;},'unfunded work':c=>{c.fundedCents=0;},'suspended contract':c=>{c.suspended=true;},'dispute':c=>{c.disputed=true;},'no AI permission':c=>{c.aiAssistanceAllowed=false;},'no data permission':c=>{c.clientDataUseAllowed=false;},'wrong identity':c=>{c.accountId='other';},'cancelled':c=>{c.state='cancelled';},'inexact gross':c=>{c.grossCents=20000.1;},
};
for(const [name,mutate] of Object.entries(contractFailures))it(`rejects assignment: ${name}`,async()=>{await auth();mutate(contract);await assert.rejects(w.assign(owner,contract.contractId,contract.milestoneId));assert.equal(db.all('SELECT * FROM mission_upwork_work').length,0);noCash();});
it('owner approvals bind exact real artifact bytes and freeze them after approval',async()=>{const r=await assigned(),id=String(r.id);await assert.rejects(w.beginManualDelivery(owner,id),/approved_work/);const draft=w.draft(owner,id,delivery.content);assert.throws(()=>w.approve(owner,id,sha256('wrong'),'review'),/approval_mismatch/);w.approve(owner,id,String(draft.content_hash),'review');assert.throws(()=>w.draft(owner,id,'replacement'),/immutable/);await w.beginManualDelivery(owner,id);await assert.rejects(w.beginManualDelivery(owner,id),/approved_work/);noCash();});
it('revocation while a delivery intent is awaiting proof blocks the outward handoff',async()=>{const r=await assigned(),id=String(r.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'review');source.contract=async()=>{w.revokeAccount(owner);return contract;};await assert.rejects(w.beginManualDelivery(owner,id),/authorization_required/);assert.equal(db.get<Row>('SELECT state FROM mission_upwork_work WHERE id=?',[id])!.state,'approved');});
it('changing the authorized scope prevents delivery',async()=>{const r=await assigned(),id=String(r.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'review');contract.scopeHash=sha256('changed');await assert.rejects(w.beginManualDelivery(owner,id),/contract_changed/);});
const deliveryFailures:Record<string,(d:UpworkDelivery)=>void>={'wrong bytes':d=>{d.content='metadata cannot prove bytes';},'wrong sender':d=>{d.accountId='other';},'wrong recipient':d=>{d.clientId='other';},'wrong submission':d=>{d.submissionId='other';},'wrong contract':d=>{d.contractId='other';},'wrong milestone':d=>{d.milestoneId='other';},'before authorization':d=>{d.submittedAt='2000-01-01T00:00:00Z';}};
for(const [name,mutate] of Object.entries(deliveryFailures))it(`delivery readback rejects ${name}`,async()=>{const r=await assigned(),id=String(r.id),d=w.draft(owner,id,delivery.content);w.approve(owner,id,String(d.content_hash),'review');await w.beginManualDelivery(owner,id);delivery.submittedAt=now();delivery.verifiedAt=now();mutate(delivery);await assert.rejects(w.confirmDelivery(owner,id,'synthetic-submission'));assert.equal(db.get<Row>('SELECT state FROM mission_upwork_work WHERE id=?',[id])!.state,'awaiting_manual_delivery');noCash();});
it('read-only manual delivery recovery remains possible after grant revocation without authorizing more work',async()=>{const id=await prepared();w.revokeAccount(owner);setKillSwitch(true,owner.id);await w.confirmDelivery(owner,id,delivery.submissionId);assert.throws(()=>w.draft(owner,id,'new'),/policy_blocked/);noCash();});
it('complete chain credits only independent receiving net USD, once across concurrent/restarted callers',async()=>{const id=await confirmed();const results=await Promise.all([settle(id),new UpworkWorkflow(source,receiver).reconcile(owner,id,payout.payoutId,receiving.externalId)]);assert.equal(results.filter(r=>!r.duplicated).length,1);assert.equal(balance(),17900);assert.equal(money.cashAccount(agent).available_cents,0);assert.equal((await settle(id)).duplicated,true);assert.equal(db.all('SELECT * FROM mission_earning_jobs').length,1);assert.equal(money.verifyCashLedger().ok,true);assert.equal(verifyMissionAudit().ok,true);});
it('earned settlement can be received after mission revocation/freeze without restoring spending authority',async()=>{const id=await confirmed();w.revokeAccount(owner);setKillSwitch(true,owner.id);await settle(id);assert.equal(balance(),17900);assert.throws(()=>money.allocateCash(owner,agent,1,'fixture'),/kill_switch/);});
const payoutFailures:Record<string,(p:UpworkRemittance)=>void>={'pending':p=>{p.state='pending';},'partial':p=>{p.complete=false;},'mixed currency':p=>{p.currency='EUR';},'unattributed extra line':p=>{p.lines.push({...p.lines[0]});},'wrong project':p=>{p.lines[0].contractId='other';},'invalid fees':p=>{p.lines[0].feeCents=-1;},'wrong total':p=>{p.netCents=17999;},'wrong gross':p=>{p.lines[0].grossCents=19000;p.lines[0].feeCents=1000;},'wrong payout':p=>{p.payoutId='other';},'wrong owner':p=>{p.accountId='other';}};
for(const [name,mutate] of Object.entries(payoutFailures))it(`payout ${name} is not cash`,async()=>{const id=await confirmed();mutate(payout);await assert.rejects(w.reconcile(owner,id,'synthetic-payout','synthetic-credit'),/blocked_or_uncertain/);noCash();});
const receivingFailures:Record<string,(r:UpworkReceivingProof)=>void>={'pending':r=>{r.state='pending';},'balance only':r=>{r.missionOwnershipVerified=false;},'non USD':r=>{r.currency='PKR';},'wrong source':r=>{r.source='freelancer' as 'upwork';},'wrong account':r=>{r.receivingAccount='other';},'wrong rail':r=>{r.rail='other';},'wrong movement':r=>{r.externalId='other';},'wrong provider account':r=>{r.accountId='other';},'wrong tenant':r=>{r.tenantId='other';},'wrong direction':r=>{r.direction='debit' as 'credit';},'wrong payout':r=>{r.payoutId='other';},'fee mismatch':r=>{r.feeCents=0;},'gross mismatch':r=>{r.grossCents=17900;r.feeCents=0;},'insufficient bank funds':r=>{r.availableBalanceCents=17899;},'stale':r=>{r.verifiedAt='2000-01-01T00:00:00Z';},'future':r=>{r.verifiedAt=new Date(Date.now()+60000).toISOString();}};
for(const [name,mutate] of Object.entries(receivingFailures))it(`receiving ${name} cannot credit or leave partial bookkeeping`,async()=>{const id=await confirmed();mutate(receiving);await assert.rejects(w.reconcile(owner,id,'synthetic-payout','synthetic-credit'),/blocked_or_uncertain/);noCash();assert.equal(db.all('SELECT * FROM mission_upwork_payouts').length,0);});
it('missing receiving adapter cannot be substituted by provider balance or caller flags',async()=>{const id=await confirmed();await assert.rejects(new UpworkWorkflow(source).reconcile(owner,id,payout.payoutId,receiving.externalId),/not_configured/);noCash();});
it('provider permission loss during independent proof lookup blocks commit',async()=>{const id=await confirmed();beforeReceiving=()=>{authority.internalApiUseApproved=false;};await assert.rejects(settle(id),/blocked_or_uncertain/);noCash();});
it('work changes while bank lookup awaits block atomic admission',async()=>{const id=await confirmed();beforeReceiving=()=>{db.run('UPDATE mission_upwork_work SET approved_hash=? WHERE id=?',[sha256('changed'),id]);};await assert.rejects(settle(id),/blocked_or_uncertain/);noCash();});
it('a deactivated owner cannot admit funds after an await',async()=>{const id=await confirmed();beforeReceiving=()=>{db.run("UPDATE mission_owner SET status='disabled' WHERE id=?",[owner.id]);};try{await assert.rejects(settle(id),/owner_required/);noCash();}finally{db.run("UPDATE mission_owner SET status='active' WHERE id=?",[owner.id]);}});
it('one physical bank movement cannot be credited by two connectors',async()=>{const id=await confirmed(),externalId='incoming:'+sha256(JSON.stringify([receiving.rail,receiving.receivingAccount,receiving.externalId]));db.run("INSERT INTO mission_money_receipts (provider,external_id,fingerprint,kind,amount_cents,created_at) VALUES ('awin-settlement',?,'synthetic','earning',17900,?)",[externalId,now()]);await assert.rejects(settle(id),/blocked_or_uncertain/);assert.equal(balance(),0);assert.equal(db.all('SELECT * FROM mission_upwork_payouts').length,0);});
it('a booked payout cannot be assigned another receiving transfer or payout ID',async()=>{const id=await confirmed();await settle(id);receiving.externalId='other';await assert.rejects(settle(id),/blocked_or_uncertain/);assert.equal(balance(),17900);assert.equal(money.ensureCashAccount().frozen,1);});
it('changed or missing booked payment proof freezes access, not an invented debit',async()=>{const id=await confirmed();await settle(id);contract.releasedCents=0;await assert.rejects(w.observePayment(owner,id),/payment_unconfirmed/);assert.equal(balance(),17900);assert.equal(money.ensureCashAccount().frozen,1);});
it('duplicate reconciliation checks current bank sufficiency, not only original receipt',async()=>{const id=await confirmed();await settle(id);receiving.availableBalanceCents=0;await assert.rejects(settle(id),/blocked_or_uncertain/);assert.equal(balance(),17900);assert.equal(money.ensureCashAccount().frozen,1);});
it('independent reversals are exact, bounded and idempotent',async()=>{const id=await confirmed();await settle(id);assert.equal((await w.reconcileReversal(owner,id,reversal.reversalExternalId)).duplicated,false);assert.equal(balance(),0);assert.equal((await w.reconcileReversal(owner,id,reversal.reversalExternalId)).duplicated,true);assert.equal(money.verifyCashLedger().ok,true);assert.equal(verifyMissionAudit().ok,true);});
it('partial reversals cannot exceed original actual net and cannot restore earning credit',async()=>{const id=await confirmed();await settle(id);reversal.amountCents=9000;await w.reconcileReversal(owner,id,reversal.reversalExternalId);assert.equal(balance(),8900);reversal.reversalExternalId='second';await assert.rejects(w.reconcileReversal(owner,id,'second'),/blocked_or_uncertain/);assert.equal(balance(),8900);await assert.rejects(settle(id),/blocked_or_uncertain/);});
for(const field of ['missionOwnershipVerified','currency','source','state','originalExternalId','reversalExternalId','tenantId','receivingAccount'] as const)it(`reversal rejects unverified ${field}`,async()=>{const id=await confirmed();await settle(id);(reversal as unknown as Record<string,unknown>)[field]=field==='missionOwnershipVerified'?false:'other';await assert.rejects(w.reconcileReversal(owner,id,'synthetic-debit'),/blocked_or_uncertain/);assert.equal(balance(),17900);});
it('original credit ID cannot masquerade as a reversal',async()=>{const id=await confirmed();await settle(id);await assert.rejects(w.reconcileReversal(owner,id,receiving.externalId),/original_settlement_required/);assert.equal(balance(),17900);});
it('adapter errors and getter failures cannot disclose credentials',async()=>{const id=await confirmed();source.remittance=async()=>{throw new Error('credential-SYNTHETIC-DO-NOT-EXPOSE');};await assert.rejects(settle(id),e=>e instanceof Error&&!e.message.includes('credential-'));source.authority=async()=>Object.defineProperty({...authority},'eligible',{enumerable:true,get(){throw new Error('credential-SYNTHETIC-DO-NOT-EXPOSE');}});await assert.rejects(auth(),e=>e instanceof Error&&e.message==='upwork_verification_unavailable');noCash();});
it('proof deadline aborts ignored/late adapters and cannot admit later data',async t=>{t.mock.timers.enable({apis:['setTimeout']});let signal:AbortSignal|undefined,resolve!:(value:{n:number})=>void;const waiting=readUpworkProof(s=>{signal=s;return new Promise(r=>{resolve=r;});});const rejected=assert.rejects(waiting,/verification_unavailable/);await Promise.resolve();await Promise.resolve();t.mock.timers.tick(30001);await rejected;assert.equal(signal!.aborted,true);resolve({n:1});await Promise.resolve();noCash();});
it('read probe binds fixed official origin/tenant, minimizes fields, has no cash effect',async()=>{let calls=0;const client=new UpworkApiReadProbe('test-fixture-key','synthetic-tenant',()=>{},async(url,init)=>{calls++;assert.equal(url,'https://api.upwork.com/graphql');assert.equal(init!.redirect,'error');assert.equal((init!.headers as Record<string,string>)['X-Upwork-API-TenantId'],'synthetic-tenant');assert.equal((init!.headers as Record<string,string>).Authorization,'Bearer test-fixture-key');assert.ok(!String(init!.body).includes('mutation'));return new Response(JSON.stringify({data:{companySelector:{items:[{organizationId:'synthetic-tenant'}]}}}));});assert.deepEqual(await client.contextMembership(),{tenantId:'synthetic-tenant',identityOrKycVerified:false});assert.equal(calls,1);noCash();});
it('probe approval, HTTP/GraphQL errors, redirection, oversized data and tenant mismatch fail closed',async()=>{let calls=0;const no=new UpworkApiReadProbe('synthetic','tenant',()=>{throw new Error('approval absent');},async()=>{calls++;return new Response('{}');});await assert.rejects(no.contextMembership());assert.equal(calls,0);for(const response of [new Response('{}',{status:429}),new Response(JSON.stringify({data:{companySelector:{items:[{organizationId:'tenant'}]}},errors:[{message:'SYNTHETIC-secret'}]})),new Response('x'.repeat(65537)),new Response(JSON.stringify({data:{companySelector:{items:[]}}}))]){const p=new UpworkApiReadProbe('synthetic','tenant',()=>{},async()=>response);await assert.rejects(p.contextMembership(),e=>e instanceof Error&&!e.message.includes('SYNTHETIC-secret'));}});
it('probe requests use durable shared limits across instances, not a polling loop',async()=>{db.run("INSERT INTO mission_upwork_api_limits (bucket,bucket_start,hits) VALUES ('minute',?,60)",[Math.floor(Date.now()/60000)*60000]);let calls=0;const p=new UpworkApiReadProbe('synthetic','tenant',()=>{},async()=>{calls++;return new Response('{}');});await assert.rejects(p.contextMembership(),/rate_limited/);assert.equal(calls,0);});
it('probe awaits asynchronous permission instead of sending while approval is unresolved',async()=>{let calls=0;const p=new UpworkApiReadProbe('synthetic','tenant',async()=>{await Promise.resolve();throw new Error('SYNTHETIC-private-approval-error');},async()=>{calls++;return new Response('{}');});await assert.rejects(p.contextMembership(),e=>e instanceof Error&&!e.message.includes('SYNTHETIC-private'));assert.equal(calls,0);});
it('probe contract header keeps term and rollup IDs distinct and is never ownership/payment proof',async()=>{const p=new UpworkApiReadProbe('synthetic','tenant',()=>{},async(_url,init)=>{const body=JSON.parse(String(init!.body));assert.deepEqual(body.variables,{termId:'term'});assert.match(body.query,/contractByTerm/);return new Response(JSON.stringify({data:{contractByTerm:{id:'rollup',kind:'FIXED_PRICE',status:'ACTIVE'}}}));});const h=await p.contractHeader('term');assert.equal(h.id,'rollup');assert.equal(h.requestedTermId,'term');assert.equal(h.executable,false);assert.equal(h.paymentVerified,false);noCash();});
it('pending provider payout observations never become cash and cannot be rebound to other work',async()=>{const id=await confirmed();payout.state='pending';assert.equal((await w.observePayout(owner,id,payout.payoutId)).cashCredited,false);await assert.rejects(settle(id));noCash();payout.state='paid';await settle(id);payout.payoutId='new-id';receiving.payoutId='new-id';await assert.rejects(settle(id));assert.equal(balance(),17900);});
it('owner authority and grant expiry are checked after account verification awaits',async()=>{source.authority=async()=>{db.run("UPDATE mission_money_grants SET status='revoked' WHERE agent_id=?",[agent]);return authority;};await assert.rejects(auth());assert.equal(db.all('SELECT * FROM mission_upwork_accounts').length,0);});
it('lost booked delivery evidence freezes funds without inventing a bank debit',async()=>{const id=await confirmed();await settle(id);delivery.content='different';await assert.rejects(w.confirmDelivery(owner,id,delivery.submissionId),/delivery_unconfirmed/);assert.equal(balance(),17900);assert.equal(money.ensureCashAccount().frozen,1);});
it('verified reversal preserves nonnegative isolated ledgers after owner allocation',async()=>{const id=await confirmed();await settle(id);money.allocateCash(owner,agent,17000,'synthetic-allocation');await w.reconcileReversal(owner,id,reversal.reversalExternalId);assert.ok(db.all<Row>('SELECT available_cents,held_cents FROM mission_cash_accounts').every(a=>Number(a.available_cents)>=0&&Number(a.held_cents)>=0));assert.equal(money.verifyCashLedger().ok,true);});
it('one mission owner cannot provision duplicate personal Upwork accounts for more agents',async()=>{await auth();authority.accountId='second-account';const second=new UpworkWorkflow({...source,accountId:'second-account'},receiver);await assert.rejects(second.authorizeAccount(owner,{agentId:other,reviewRef:'synthetic',expiresAt:new Date(Date.now()+3600000).toISOString()}),/exclusive_account_conflict/);assert.equal(db.all('SELECT * FROM mission_upwork_accounts').length,1);});
