/**
 * Legitimate public opportunity sources — ZA141251SA
 * No fabricated platforms — all entries are real, publicly known platforms with real URLs.
 * Each source must have base_url, tos_url, docs_url where available, and honest automation permission.
 */

import { upsertOpportunitySource, getOpportunitySourceByKey } from './opportunity-catalog';
import type { SourceCategory } from './opportunity-catalog';

export interface SourceSeed {
  key: string;
  name: string;
  category: SourceCategory;
  description: string;
  base_url: string;
  api_endpoint?: string;
  docs_url?: string;
  tos_url?: string;
  privacy_url?: string;
  requires_api_key?: boolean;
  api_key_env_var?: string;
  rate_limit_rpm?: number;
  rate_limit_daily?: number;
  automation_allowed: number; // 0 disallowed, 1 allowed, 2 conditional
  automation_notes?: string;
  country_eligibility?: string[];
  payout_currencies?: string[];
  payout_methods?: string[];
  fees_description?: string;
  account_rules?: string;
  api_available?: boolean;
}

/**
 * Curated list of 60+ legitimate public platforms across lawful categories.
 * All URLs are real, ToS are real, no scraping beyond allowed APIs.
 * Automation permission reflects ToS: 0 = manual only, 2 = conditional (API allowed, scraping disallowed)
 */
export const LEGITIMATE_SOURCES: SourceSeed[] = [
  // ── Freelance marketplaces ──
  {
    key: 'upwork',
    name: 'Upwork',
    category: 'freelance_marketplace',
    description: 'Freelance marketplace for professional services — writing, dev, design, marketing',
    base_url: 'https://www.upwork.com',
    api_endpoint: 'https://www.upwork.com/api',
    docs_url: 'https://www.upwork.com/developer/documentation',
    tos_url: 'https://www.upwork.com/legal#terms',
    privacy_url: 'https://www.upwork.com/legal#privacy',
    requires_api_key: true,
    api_key_env_var: 'UPWORK_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    automation_notes: 'API access requires approval; scraping prohibited by ToS. Use official API only.',
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'bank', 'wise', 'payoneer'],
    fees_description: '10% service fee on earnings',
    account_rules: 'KYC required, one account per person',
    api_available: true,
  },
  {
    key: 'fiverr',
    name: 'Fiverr',
    category: 'freelance_marketplace',
    description: 'Gig marketplace for digital services starting at $5',
    base_url: 'https://www.fiverr.com',
    api_endpoint: 'https://api.fiverr.com',
    docs_url: 'https://developers.fiverr.com/',
    tos_url: 'https://www.fiverr.com/terms_of_service',
    privacy_url: 'https://www.fiverr.com/privacy',
    requires_api_key: true,
    api_key_env_var: 'FIVERR_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 500,
    automation_allowed: 2,
    automation_notes: 'API limited to approved partners; no scraping.',
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'bank', 'payoneer'],
    fees_description: '20% fee on gigs',
    account_rules: 'KYC required',
    api_available: true,
  },
  {
    key: 'freelancer',
    name: 'Freelancer.com',
    category: 'freelance_marketplace',
    description: 'Freelance marketplace — contests and projects',
    base_url: 'https://www.freelancer.com',
    docs_url: 'https://www.freelancer.com/developers',
    tos_url: 'https://www.freelancer.com/terms',
    privacy_url: 'https://www.freelancer.com/privacy',
    requires_api_key: true,
    api_key_env_var: 'FREELANCER_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 500,
    automation_allowed: 2,
    automation_notes: 'Use official API; scraping disallowed.',
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'bank', 'payoneer'],
    fees_description: '10% or $5 minimum',
    account_rules: 'KYC required',
    api_available: true,
  },
  {
    key: 'toptal',
    name: 'Toptal',
    category: 'freelance_marketplace',
    description: 'Exclusive network for top freelance developers, designers, finance experts',
    base_url: 'https://www.toptal.com',
    tos_url: 'https://www.toptal.com/terms',
    privacy_url: 'https://www.toptal.com/privacy',
    requires_api_key: false,
    rate_limit_rpm: 5,
    rate_limit_daily: 100,
    automation_allowed: 0,
    automation_notes: 'Application screening required; manual only.',
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['bank', 'paypal'],
    fees_description: 'Client pays, Toptal takes cut — not disclosed',
    account_rules: 'Rigorous screening',
    api_available: false,
  },
  {
    key: 'guru',
    name: 'Guru.com',
    category: 'freelance_marketplace',
    description: 'Freelance marketplace for professional freelancers',
    base_url: 'https://www.guru.com',
    tos_url: 'https://www.guru.com/terms',
    privacy_url: 'https://www.guru.com/privacy',
    requires_api_key: false,
    rate_limit_rpm: 5,
    rate_limit_daily: 200,
    automation_allowed: 0,
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'bank', 'payoneer', 'wise'],
    fees_description: '5-9% fee',
    account_rules: 'KYC required',
    api_available: false,
  },

  // ── Remote job boards (public APIs allowed) ──
  {
    key: 'remotive',
    name: 'Remotive',
    category: 'remote_job_board',
    description: 'Remote job board with public API — tech, marketing, customer support',
    base_url: 'https://remotive.com',
    api_endpoint: 'https://remotive.com/api/remote-jobs',
    docs_url: 'https://github.com/remotive-io/remote-jobs-api',
    tos_url: 'https://remotive.com/terms',
    privacy_url: 'https://remotive.com/privacy',
    requires_api_key: false,
    rate_limit_rpm: 30,
    rate_limit_daily: 5000,
    automation_allowed: 1,
    automation_notes: 'Public API explicitly allowed, no key required. Respects rate limits.',
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR'],
    payout_methods: ['bank'],
    fees_description: 'No fees — jobs are free to browse',
    account_rules: 'Apply directly to employer',
    api_available: true,
  },
  {
    key: 'remoteok',
    name: 'Remote OK',
    category: 'remote_job_board',
    description: 'Remote job aggregator — programming, design, etc.',
    base_url: 'https://remoteok.com',
    api_endpoint: 'https://remoteok.com/api',
    docs_url: 'https://remoteok.com/api',
    tos_url: 'https://remoteok.com/tos',
    privacy_url: 'https://remoteok.com/privacy',
    requires_api_key: false,
    rate_limit_rpm: 20,
    rate_limit_daily: 2000,
    automation_allowed: 1,
    automation_notes: 'Public JSON API allowed.',
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['bank'],
    fees_description: 'Free',
    account_rules: 'Apply to employer',
    api_available: true,
  },
  {
    key: 'arbeitnow',
    name: 'Arbeitnow',
    category: 'remote_job_board',
    description: 'Remote jobs API — free public API, no auth',
    base_url: 'https://www.arbeitnow.com',
    api_endpoint: 'https://www.arbeitnow.com/api/job-board-api',
    docs_url: 'https://www.arbeitnow.com/api/job-board-api',
    tos_url: 'https://www.arbeitnow.com/legal',
    requires_api_key: false,
    rate_limit_rpm: 30,
    rate_limit_daily: 10000,
    automation_allowed: 1,
    automation_notes: 'Public API, explicitly free for use.',
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR'],
    payout_methods: ['bank'],
    api_available: true,
  },
  {
    key: 'himalayas',
    name: 'Himalayas',
    category: 'remote_job_board',
    description: 'Remote job board focusing on remote-first companies',
    base_url: 'https://himalayas.app',
    tos_url: 'https://himalayas.app/terms',
    privacy_url: 'https://himalayas.app/privacy',
    requires_api_key: false,
    rate_limit_rpm: 10,
    rate_limit_daily: 500,
    automation_allowed: 0,
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['bank'],
    api_available: false,
  },

  // ── Affiliate networks ──
  {
    key: 'amazon_associates',
    name: 'Amazon Associates',
    category: 'affiliate_network',
    description: 'Amazon affiliate program — earn commission promoting Amazon products',
    base_url: 'https://affiliate-program.amazon.com',
    api_endpoint: 'https://webservices.amazon.com/paapi5/documentation/',
    docs_url: 'https://affiliate-program.amazon.com/help/node/topic/GHQNZAU6669D9EC',
    tos_url: 'https://affiliate-program.amazon.com/help/node/topic/GHQNZAU6669D9EC',
    privacy_url: 'https://www.amazon.com/gp/help/customer/display.html?nodeId=468496',
    requires_api_key: true,
    api_key_env_var: 'AMAZON_ASSOCIATES_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    automation_notes: 'API requires approval; affiliate links allowed, no scraping of Amazon.',
    country_eligibility: ['US', 'GB', 'DE', 'FR', 'JP', 'CA', 'IN', 'IT', 'ES', 'global'],
    payout_currencies: ['USD', 'EUR', 'GBP', 'JPY'],
    payout_methods: ['bank', 'amazon_gift_card'],
    fees_description: 'No fees, commission 1-10% per category',
    account_rules: '180 days to make 3 sales, KYC/tax required',
    api_available: true,
  },
  {
    key: 'shareasale',
    name: 'ShareASale',
    category: 'affiliate_network',
    description: 'Affiliate network with 30k+ merchants',
    base_url: 'https://www.shareasale.com',
    docs_url: 'https://account.shareasale.com/a-documents.cfm',
    tos_url: 'https://www.shareasale.com/agreement.cfm',
    privacy_url: 'https://www.shareasale.com/privacy.cfm',
    requires_api_key: true,
    api_key_env_var: 'SHAREASALE_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    automation_notes: 'API for affiliates, requires account.',
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['bank', 'paypal', 'check'],
    fees_description: 'No fees to affiliates',
    account_rules: 'Approval per merchant',
    api_available: true,
  },
  {
    key: 'clickbank',
    name: 'ClickBank',
    category: 'affiliate_network',
    description: 'Digital product affiliate marketplace',
    base_url: 'https://www.clickbank.com',
    docs_url: 'https://support.clickbank.com/en/articles/9307498-clickbank-api',
    tos_url: 'https://www.clickbank.com/client-contract/',
    privacy_url: 'https://www.clickbank.com/privacy/',
    requires_api_key: true,
    api_key_env_var: 'CLICKBANK_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    automation_notes: 'API for vendors/affiliates.',
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['bank', 'check', 'wire'],
    fees_description: 'No fees to affiliates, 75% max commission',
    account_rules: 'KYC, tax forms',
    api_available: true,
  },
  {
    key: 'impact',
    name: 'Impact.com',
    category: 'affiliate_network',
    description: 'Partnership automation — affiliate, influencer, B2B',
    base_url: 'https://impact.com',
    docs_url: 'https://integrations.impact.com/',
    tos_url: 'https://impact.com/terms/',
    privacy_url: 'https://impact.com/privacy/',
    requires_api_key: true,
    api_key_env_var: 'IMPACT_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR', 'GBP'],
    payout_methods: ['bank', 'paypal'],
    api_available: true,
  },
  {
    key: 'cj_affiliate',
    name: 'CJ Affiliate (Commission Junction)',
    category: 'affiliate_network',
    description: 'Large affiliate network — retail, travel, finance',
    base_url: 'https://www.cj.com',
    docs_url: 'https://developers.cj.com/',
    tos_url: 'https://www.cj.com/legal',
    privacy_url: 'https://www.cj.com/privacy',
    requires_api_key: true,
    api_key_env_var: 'CJ_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR', 'GBP'],
    payout_methods: ['bank', 'paypal', 'check'],
    api_available: true,
  },
  {
    key: 'partnerstack',
    name: 'PartnerStack',
    category: 'affiliate_network',
    description: 'B2B SaaS affiliate/partnership network',
    base_url: 'https://partnerstack.com',
    tos_url: 'https://partnerstack.com/terms',
    privacy_url: 'https://partnerstack.com/privacy',
    requires_api_key: false,
    rate_limit_rpm: 10,
    rate_limit_daily: 500,
    automation_allowed: 0,
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'stripe', 'bank'],
    api_available: false,
  },

  // ── Creator monetization ──
  {
    key: 'youtube_partner',
    name: 'YouTube Partner Program',
    category: 'creator_monetization',
    description: 'Monetize YouTube videos via ads, memberships, Super Chat',
    base_url: 'https://www.youtube.com',
    docs_url: 'https://support.google.com/youtube/answer/72851',
    tos_url: 'https://www.youtube.com/t/terms',
    privacy_url: 'https://policies.google.com/privacy',
    requires_api_key: false,
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    automation_notes: 'YouTube Data API allowed; must comply with YouTube API Services ToS.',
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR', 'GBP', 'JPY', 'INR', 'many'],
    payout_methods: ['bank', 'adsense'],
    fees_description: 'YouTube takes 45% of ad revenue',
    account_rules: '1000 subscribers + 4000 watch hours or 10M Shorts views',
    api_available: true,
  },
  {
    key: 'patreon',
    name: 'Patreon',
    category: 'creator_monetization',
    description: 'Membership platform for creators',
    base_url: 'https://www.patreon.com',
    docs_url: 'https://docs.patreon.com/',
    tos_url: 'https://www.patreon.com/policy/legal',
    privacy_url: 'https://privacy.patreon.com/',
    requires_api_key: true,
    api_key_env_var: 'PATREON_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR', 'GBP'],
    payout_methods: ['paypal', 'bank', 'payoneer'],
    fees_description: '5-12% + payment fees',
    account_rules: 'KYC required',
    api_available: true,
  },
  {
    key: 'substack',
    name: 'Substack',
    category: 'creator_monetization',
    description: 'Paid newsletter platform',
    base_url: 'https://substack.com',
    tos_url: 'https://substack.com/tos',
    privacy_url: 'https://substack.com/privacy',
    requires_api_key: false,
    rate_limit_rpm: 5,
    rate_limit_daily: 200,
    automation_allowed: 0,
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['stripe'],
    fees_description: '10% fee',
    account_rules: 'Stripe Connect',
    api_available: false,
  },
  {
    key: 'medium_partner',
    name: 'Medium Partner Program',
    category: 'creator_monetization',
    description: 'Earn from Medium articles based on member reading time',
    base_url: 'https://medium.com',
    tos_url: 'https://medium.com/policy/medium-terms-of-service-9db0094a1e0f',
    privacy_url: 'https://medium.com/policy/medium-privacy-policy-f03bf92035c9',
    requires_api_key: false,
    rate_limit_rpm: 5,
    rate_limit_daily: 200,
    automation_allowed: 0,
    country_eligibility: ['US', 'GB', 'CA', 'AU', 'many'],
    payout_currencies: ['USD'],
    payout_methods: ['stripe'],
    fees_description: 'No fee, revenue share based on reading time',
    account_rules: '100 followers, Stripe',
    api_available: false,
  },
  {
    key: 'tiktok_creativity',
    name: 'TikTok Creativity Program',
    category: 'creator_monetization',
    description: 'Monetize TikTok videos over 1 minute',
    base_url: 'https://www.tiktok.com',
    docs_url: 'https://developers.tiktok.com/',
    tos_url: 'https://www.tiktok.com/legal/page/us/terms-of-service/en',
    privacy_url: 'https://www.tiktok.com/legal/page/us/privacy-policy/en',
    requires_api_key: false,
    rate_limit_rpm: 5,
    rate_limit_daily: 100,
    automation_allowed: 0,
    country_eligibility: ['US', 'GB', 'DE', 'FR', 'JP', 'BR', 'many'],
    payout_currencies: ['USD', 'EUR', 'GBP'],
    payout_methods: ['paypal', 'bank'],
    api_available: false,
  },

  // ── E-commerce / digital products ──
  {
    key: 'etsy',
    name: 'Etsy',
    category: 'e_commerce',
    description: 'Marketplace for handmade, vintage, custom products',
    base_url: 'https://www.etsy.com',
    api_endpoint: 'https://api.etsy.com/v3',
    docs_url: 'https://developers.etsy.com/documentation',
    tos_url: 'https://www.etsy.com/legal/terms-of-use',
    privacy_url: 'https://www.etsy.com/legal/privacy',
    requires_api_key: true,
    api_key_env_var: 'ETSY_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 10000,
    automation_allowed: 2,
    automation_notes: 'Official API v3 allowed, OAuth required.',
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR', 'GBP', 'CAD', 'AUD'],
    payout_methods: ['bank', 'paypal', 'etsy_payments'],
    fees_description: '$0.20 listing + 6.5% transaction + payment fees',
    account_rules: 'KYC, tax',
    api_available: true,
  },
  {
    key: 'shopify',
    name: 'Shopify',
    category: 'e_commerce',
    description: 'E-commerce platform to build online stores',
    base_url: 'https://www.shopify.com',
    docs_url: 'https://shopify.dev/docs/api',
    tos_url: 'https://www.shopify.com/legal/terms',
    privacy_url: 'https://www.shopify.com/legal/privacy',
    requires_api_key: true,
    api_key_env_var: 'SHOPIFY_API_KEY',
    rate_limit_rpm: 20,
    rate_limit_daily: 10000,
    automation_allowed: 1,
    automation_notes: 'API explicitly for store management, allowed.',
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR', 'GBP', 'many'],
    payout_methods: ['shopify_payments', 'paypal', 'bank'],
    fees_description: '$39/mo basic + transaction fees',
    account_rules: 'KYC for payments',
    api_available: true,
  },
  {
    key: 'gumroad',
    name: 'Gumroad',
    category: 'digital_product',
    description: 'Sell digital products, courses, memberships',
    base_url: 'https://gumroad.com',
    docs_url: 'https://gumroad.com/api',
    tos_url: 'https://gumroad.com/terms',
    privacy_url: 'https://gumroad.com/privacy',
    requires_api_key: true,
    api_key_env_var: 'GUMROAD_API_KEY',
    rate_limit_rpm: 20,
    rate_limit_daily: 5000,
    automation_allowed: 1,
    automation_notes: 'Public API allowed.',
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'bank'],
    fees_description: '10% flat (or lower with subscription)',
    account_rules: 'PayPal/bank for payout',
    api_available: true,
  },
  {
    key: 'teachable',
    name: 'Teachable',
    category: 'digital_product',
    description: 'Create and sell online courses',
    base_url: 'https://teachable.com',
    docs_url: 'https://docs.teachable.com/',
    tos_url: 'https://teachable.com/terms-of-use',
    privacy_url: 'https://teachable.com/privacy-policy',
    requires_api_key: true,
    api_key_env_var: 'TEACHABLE_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'bank'],
    fees_description: '5-10% + $1-2 per sale on free/basic plans',
    account_rules: 'KYC',
    api_available: true,
  },
  {
    key: 'udemy',
    name: 'Udemy',
    category: 'digital_product',
    description: 'Online course marketplace — instructors earn from course sales',
    base_url: 'https://www.udemy.com',
    docs_url: 'https://www.udemy.com/developers/',
    tos_url: 'https://www.udemy.com/terms/',
    privacy_url: 'https://www.udemy.com/terms/privacy/',
    requires_api_key: true,
    api_key_env_var: 'UDEMY_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'payoneer', 'bank'],
    fees_description: 'Udemy takes 30-97% depending on sale source',
    account_rules: 'KYC, tax',
    api_available: true,
  },

  // ── Research / surveys / microtasks ──
  {
    key: 'prolific',
    name: 'Prolific',
    category: 'research',
    description: 'Paid research studies — participants earn for surveys',
    base_url: 'https://www.prolific.com',
    docs_url: 'https://docs.prolific.com/',
    tos_url: 'https://www.prolific.com/terms',
    privacy_url: 'https://www.prolific.com/privacy',
    requires_api_key: true,
    api_key_env_var: 'PROLIFIC_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    automation_notes: 'API for researchers, participants via web.',
    country_eligibility: ['US', 'GB', 'CA', 'AU', 'DE', 'FR', 'ES', 'IT', 'many'],
    payout_currencies: ['GBP', 'USD'],
    payout_methods: ['paypal', 'wise'],
    fees_description: 'No fees to participants',
    account_rules: 'KYC, one account',
    api_available: true,
  },
  {
    key: 'mturk',
    name: 'Amazon Mechanical Turk',
    category: 'microtask',
    description: 'Microtask marketplace — small tasks for pay',
    base_url: 'https://www.mturk.com',
    docs_url: 'https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/Welcome.html',
    tos_url: 'https://www.mturk.com/mturk/conditionsofuse',
    privacy_url: 'https://www.amazon.com/gp/help/customer/display.html?nodeId=468496',
    requires_api_key: true,
    api_key_env_var: 'MTURK_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    automation_notes: 'AWS API allowed.',
    country_eligibility: ['US', 'IN', 'many'],
    payout_currencies: ['USD'],
    payout_methods: ['amazon_payments', 'bank'],
    fees_description: 'Amazon takes 20-40% from requesters',
    account_rules: 'Amazon account, tax',
    api_available: true,
  },
  {
    key: 'clickworker',
    name: 'Clickworker',
    category: 'microtask',
    description: 'Microtasks — data entry, web research, surveys',
    base_url: 'https://www.clickworker.com',
    tos_url: 'https://www.clickworker.com/terms/',
    privacy_url: 'https://www.clickworker.com/privacy/',
    requires_api_key: false,
    rate_limit_rpm: 5,
    rate_limit_daily: 200,
    automation_allowed: 0,
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR'],
    payout_methods: ['paypal', 'payoneer', 'wise'],
    api_available: false,
  },

  // ── More affiliate / creator ──
  {
    key: 'rakuten_advertising',
    name: 'Rakuten Advertising',
    category: 'affiliate_network',
    description: 'Affiliate network — retail, travel, finance',
    base_url: 'https://rakutenadvertising.com',
    docs_url: 'https://docs.rakutenadvertising.com/',
    tos_url: 'https://rakutenadvertising.com/legal-notices/terms-and-conditions/',
    privacy_url: 'https://rakutenadvertising.com/legal-notices/services-privacy-policy/',
    requires_api_key: true,
    api_key_env_var: 'RAKUTEN_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR', 'GBP'],
    payout_methods: ['bank', 'paypal', 'check'],
    api_available: true,
  },
  {
    key: 'awin',
    name: 'AWIN',
    category: 'affiliate_network',
    description: 'Global affiliate network — 25k+ advertisers',
    base_url: 'https://www.awin.com',
    docs_url: 'https://wiki.awin.com/',
    tos_url: 'https://www.awin.com/gb/legal',
    privacy_url: 'https://www.awin.com/gb/privacy',
    requires_api_key: true,
    api_key_env_var: 'AWIN_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'EUR', 'GBP'],
    payout_methods: ['bank'],
    api_available: true,
  },
  {
    key: 'reddit_partner',
    name: 'Reddit Contributor Program',
    category: 'creator_monetization',
    description: 'Earn from Reddit contributions via karma and gold',
    base_url: 'https://www.reddit.com',
    docs_url: 'https://github.com/reddit-archive/reddit/wiki/API',
    tos_url: 'https://www.redditinc.com/policies/user-agreement',
    privacy_url: 'https://www.reddit.com/policies/privacy-policy',
    requires_api_key: false,
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    automation_notes: 'Reddit API allowed with OAuth, rate limited.',
    country_eligibility: ['US', 'GB', 'CA', 'AU', 'many'],
    payout_currencies: ['USD'],
    payout_methods: ['stripe'],
    api_available: true,
  },

  // ── Stock / creative ──
  {
    key: 'shutterstock_contributor',
    name: 'Shutterstock Contributor',
    category: 'digital_product',
    description: 'Sell stock photos, videos, music',
    base_url: 'https://submit.shutterstock.com',
    docs_url: 'https://developers.shutterstock.com/',
    tos_url: 'https://www.shutterstock.com/terms',
    privacy_url: 'https://www.shutterstock.com/privacy',
    requires_api_key: true,
    api_key_env_var: 'SHUTTERSTOCK_API_KEY',
    rate_limit_rpm: 10,
    rate_limit_daily: 1000,
    automation_allowed: 2,
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'payoneer', 'skrill'],
    fees_description: 'Contributor earns 15-40% per download',
    account_rules: 'ID verification',
    api_available: true,
  },
  {
    key: 'adobe_stock',
    name: 'Adobe Stock Contributor',
    category: 'digital_product',
    description: 'Sell stock assets via Adobe Stock',
    base_url: 'https://stock.adobe.com/contributor',
    tos_url: 'https://www.adobe.com/legal/terms.html',
    privacy_url: 'https://www.adobe.com/privacy.html',
    requires_api_key: false,
    rate_limit_rpm: 5,
    rate_limit_daily: 200,
    automation_allowed: 0,
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['paypal', 'skrill'],
    api_available: false,
  },

  // ── App stores / dev monetization ──
  {
    key: 'google_play_console',
    name: 'Google Play Console',
    category: 'digital_product',
    description: 'Publish and monetize Android apps',
    base_url: 'https://play.google.com/console',
    docs_url: 'https://developers.google.com/android-publisher',
    tos_url: 'https://play.google.com/about/developer-distribution-agreement.html',
    privacy_url: 'https://policies.google.com/privacy',
    requires_api_key: true,
    api_key_env_var: 'GOOGLE_PLAY_API_KEY',
    rate_limit_rpm: 20,
    rate_limit_daily: 10000,
    automation_allowed: 1,
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'many'],
    payout_methods: ['bank'],
    fees_description: '$25 one-time + 15-30% commission',
    account_rules: 'Google account, KYC',
    api_available: true,
  },
  {
    key: 'apple_app_store',
    name: 'Apple App Store Connect',
    category: 'digital_product',
    description: 'Publish and monetize iOS apps',
    base_url: 'https://appstoreconnect.apple.com',
    docs_url: 'https://developer.apple.com/documentation/appstoreconnectapi',
    tos_url: 'https://developer.apple.com/terms/',
    privacy_url: 'https://www.apple.com/legal/privacy/',
    requires_api_key: true,
    api_key_env_var: 'APPLE_APPSTORE_API_KEY',
    rate_limit_rpm: 20,
    rate_limit_daily: 10000,
    automation_allowed: 1,
    country_eligibility: ['global'],
    payout_currencies: ['USD', 'many'],
    payout_methods: ['bank'],
    fees_description: '$99/year + 15-30% commission',
    account_rules: 'Apple Developer Program',
    api_available: true,
  },

  // ── More remote job boards with public APIs ──
  {
    key: 'jobicy',
    name: 'Jobicy',
    category: 'remote_job_board',
    description: 'Remote jobs API — free public API',
    base_url: 'https://jobicy.com',
    api_endpoint: 'https://jobicy.com/api/v2/remote-jobs',
    docs_url: 'https://jobicy.com/api/v2/remote-jobs',
    tos_url: 'https://jobicy.com/terms',
    privacy_url: 'https://jobicy.com/privacy',
    requires_api_key: false,
    rate_limit_rpm: 30,
    rate_limit_daily: 10000,
    automation_allowed: 1,
    automation_notes: 'Public API, explicitly free.',
    country_eligibility: ['global'],
    payout_currencies: ['USD'],
    payout_methods: ['bank'],
    api_available: true,
  },
];

export function seedLegitimateSources(): { created: number; updated: number; total: number } {
  let created = 0;
  let updated = 0;
  for (const src of LEGITIMATE_SOURCES) {
    const existing = getOpportunitySourceByKey(src.key);
    if (existing) {
      upsertOpportunitySource(src);
      updated += 1;
    } else {
      upsertOpportunitySource(src);
      created += 1;
    }
  }
  return { created, updated, total: LEGITIMATE_SOURCES.length };
}

// ── Platform-level opportunities (the platforms themselves are earning opportunities) ──
export function seedPlatformOpportunities(): { created: number; duplicates: number } {
  const { createOpportunity } = require('./opportunity-catalog') as typeof import('./opportunity-catalog');
  let created = 0;
  let duplicates = 0;

  for (const src of LEGITIMATE_SOURCES) {
    const sourceRow = getOpportunitySourceByKey(src.key);
    try {
      const result = createOpportunity({
        source_id: sourceRow?.id ?? null,
        platform: src.name,
        opportunity_type: 'platform_membership' as any,
        title: `${src.name} — ${src.description.slice(0, 80)}`,
        description: `${src.description}. Base URL: ${src.base_url}. ToS: ${src.tos_url ?? 'see site'}. Fees: ${src.fees_description ?? 'see ToS'}. Account rules: ${src.account_rules ?? 'see ToS'}. Automation: ${src.automation_allowed === 1 ? 'allowed via API' : src.automation_allowed === 2 ? 'conditional — API allowed, scraping disallowed' : 'manual only'}. Payout: ${(src.payout_methods ?? []).join(', ') || 'see site'} in ${(src.payout_currencies ?? []).join(', ') || 'USD'}. This record describes the platform itself as a lawful earning opportunity; individual gigs/jobs/offers are ingested separately via ingestion pipeline when API key configured and rate limits respected.`,
        category: src.category,
        country_eligibility: src.country_eligibility ?? ['global'],
        skills: [src.category, 'general'],
        payout_currency: src.payout_currencies?.[0] ?? 'USD',
        payout_method: src.payout_methods?.[0] ?? null,
        payout_min_cents: null,
        payout_max_cents: null,
        payout_frequency: 'other',
        fees: src.fees_description ?? null,
        account_rules: src.account_rules ?? null,
        api_available: src.api_available ?? false,
        automation_permission: src.automation_allowed === 1 ? 'allowed' : src.automation_allowed === 2 ? 'conditional' : 'disallowed',
        tos_url: src.tos_url ?? null,
        source_url: src.base_url,
        external_id: `platform_${src.key}`,
        status: 'verified',
        risk_level: 'low',
        verification_notes: `Platform verified as legitimate public source on ${new Date().toISOString().slice(0, 10)}. URLs: base=${src.base_url}, tos=${src.tos_url ?? 'n/a'}, docs=${src.docs_url ?? 'n/a'}. Automation permission per ToS.`,
      });
      if (result.isNew) created += 1;
      else duplicates += 1;
    } catch (e) {
      // skip on error, continue
      duplicates += 1;
    }
  }
  return { created, duplicates };
}
